HansKristian-Work/vkd3d-proton

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/state.c
Addresses some annoyances I encountered while working on the binding model.
Drops OpenGL-related code since that will be just dead weight and untested anyway.
> Some vkd3d-shader cleanups

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
In preparation for the bindless implementation, this makes the following changes to UAV counter handling:
- UAV counters are packed into the root signature's descriptor set layout for now. This allows us to get rid of per-pipeline descriptor set layouts and pipeline layouts, and gretaly simplifies descriptor updates involving UAV counters.
- UAV counter bindings are passed to vkd3d-shader as regular resource bindings in order to avoid some duplication.
As part of the bindless implementation, I plan to rewrite `d3d12_command_list_update_descriptors` as well as `d3d12_root_signature_init` completely from scratch. While those parts are currently messy, they hopefully won't stay that way for long.
It's probably worth testing WoW with thsese patches, which I haven't done yet. SotTR and Metro …
> Temporary UAV counter rework

- libs/vkd3d/command.c
The primary purpose of this function was to invalidate UAV counters upon binding a pipeline. This is no longer an issue and we don't have any other per-pipeline bindings, so this function can be dropped.
Other bindings are invalidated via `d3d12_command_list_invalidate_root_parameters`.
> vkd3d: Remove d3d12_command_list_invalidate_bindings.

- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
Need this to support subgroup operations for SM 6.0.
> vkd3d: Attempt to create a Vulkan 1.1 instance and device.

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Currently, we leave descriptors undefined that are either left uninitialized by the application or have the wrong resource type bound. However, this causes issues when using descriptor update templates since we need to provide a valid view handle for all descriptors that are to be updated.
Providing these may then also improve stability with misbehaving applications that access an undefined descriptor in a shader.
Note that this is different from the explicit NULL descriptors that the application can create using `CreateShaderResourceView` and friends.
> vkd3d: Create NULL buffer and image views.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Implements initial support for bindless SRVs and Samplers, as well as dynamic and non-uniform descriptor indexing for Shader Model 5.1/6.0.
This consists of several parts, all of which depend on each other:
1. Shader compiler work to support these features, including some required additions to the interface between vkd3d and the shader compiler.
2. A complete rewrite of the root signature and resource binding code, which was needed since assumptions about the exact descriptor set layouts were duplicated in various places and the whole thing was barely maintainable, let alone extensible.
3. API-side additions to support bindless SRVs/Samplers.
The implementation passes both `test_bindless_srv_sm51` and `test_bindless_samplers_sm51` on AMDVLK as well as RADV with ACO (non-uniform indexing …
> Binding model: Bindless part 2

- libs/vkd3d-shader/spirv.c
- libs/vkd3d/state.c
Title.
Haven't managed to write a test for non-uniform/dynamic CBV indexing so far since that seems to crash the AMD driver, but it doesn't cause any test regression (`test_constant_buffer_sm51` uses CBVs in descriptor tables and still passes) and works in Resident Evil 2, which makes use of CBV descriptor ranges.
> vkd3d: Bindless CBV

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
We still use push constants if the total size of the root constants and descriptor table offsets is less than the device's maximum push constant size. Passes `test_bindless_full_root_parameters_sm51` on AMD drivers.
Further work is needed to make the root constant layout spec-compliant, but this is not a new issue and is already present in the push constant path.
> vkd3d: Use VK_EXT_inline_uniform_block for root constants etc. if necessary

- libs/vkd3d-shader/spirv.c
Unrolls the root constant buffer to something like the following:
```glsl
layout(push_constant)
uniform push_cb_t {
float cb0_0;
float cb0_1;
float cb1_0;
float cb1_1;
float cb1_2;
float cb1_3;
uint table0;
uint table1;
} push_cb;
```
This fixes issues where we would have misaligned and overlapping vec4 variables in the push constant buffer.
> vkd3d-shader: Rework constant buffer loads and root constant layout

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Avoids a potential issue where root descriptors and other static descriptors were being allocated as UPDATE_AFTER_BIND, which could lead to more pressure on maxUpdateAfterBindDescriptors limit.
> Split descriptor pool allocation based on usage.

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Older Nvidia generations up to Pascal don't support bindless uniform buffers.
Note that we don't expose `RESOURCE_BINDING_TIER_3` just yet on those GPUs since the code to determine d3d12 caps should probably be reworked as well. What should we check for?
Maybe something like the following:
- No bindless -> Tier 1
- Bindless SRV+Samplers -> Tier 2
- Bindless everything -> Tier 3
> vkd3d: Implement bindless CBV using SSBOs if necessary

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Title.
The idea here is to check D3D12 features after the device has otherwise been fully initialized, so that we can safely access all available information and don't have to duplicate code, or otherwise move partially initialized data structures around.
Also enables `RESOURCE_BINDING_TIER_3` on capable Nvidia GPUs.
> vkd3d: Clean up D3D12 feature and feature level detection.

- libs/vkd3d/command.c
Title. For SSBO we need `VK_ACCESS_SHADER_READ_BIT`.
> vkd3d: Fix barriers for bindless CBV-as-SSBO.

- libs/vkd3d/state.c
NVIDIA currently seems to have some issues with bindless CBV on Vulkan,
which have been reported. Somehow, bindless SSBO works around black
screen on SotTR, as well as some rendering glitches on Control.
AMD won't care since UBOs and SSBOs are basically the same thing.
> vkd3d: Always use CBV-as-SSBO path.

- libs/vkd3d/command.c
All attachments must be at least as large as the framebuffer, using a
max operator is not compliant with Vulkan.
> vkd3d: Use minimum width/height/layer framebuffer.

- libs/vkd3d/command.c
Demote this warning to TRACE only.
Control spams this alot.
> vkd3d: Disable index_buffer_strip_cut spam in normal runtime.

- libs/vkd3d-shader/spirv.c
- libs/vkd3d/state.c
Passes the bindless UAV test *without* counters on both RADV and AMDVLK.
We currently completely ignore UAV counters for unbounded UAV descriptor ranges in order to avoid out of memory errors. This is not a regression as unbounded UAV descriptor ranges were completely unsupported before.
> vkd3d: Bindless UAV

- libs/vkd3d/state.c
It's not clear why this is needed; depth-only rendering without a fragment shader is legal in Vulkan.
> vkd3d: Remove default pixel shader.

- tests/d3d12.c
> vkd3d: Fix integer cast warning in d3d12.c.

- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Uses `VK_KHR_buffer_device_address` to pass UAV counter addresses to shaders via an SSBO. This SSBO is part of the root descriptor set in order to avoid complexity around descriptor updates.
Passes `test_bindless_uav_counter_sm51` on RADV.
> vkd3d: Bindless UAV counters

- libs/vkd3d-shader/dxil.c
- libs/vkd3d/vulkan_procs.h
Passes test on NVIDIA at least without validation errors.
> Enable bindless UAV counters in DXIL.

- libs/vkd3d/device.c
Partially reverts 88437397978ee36fd479d3a8ca94d83e494d6367.
This was a bit premature as Nvidia does not expose VK_KHR_buffer_device_address in current Linux drivers yet, so we're needlessly locking users out of playing some games that work anyway.
> vkd3d: Don't require bindless UAV counters for RESOURCE_BINDING_TIER_3.

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
We were accidentally using an incorrect descriptor count.
Also, this checks whether we exceed the device limit for push descriptors and uses the fallback path if we do. This can in theory happen if the root signature has 32 root descriptors and bindless UAV counters are enabled.
> vkd3d: Fix UAV counter binding declaration.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
RenderDoc will disable `VK_KHR_buffer_device_address` on drivers that do not support the corresponding capture/replay feature, but would still fill in the feature structs, so we were still trying to use it. This would either crash RenderDoc or lead to unusable captures.
> vkd3d: Fix feature enablement for extensions

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12.c
Tested on NV with test suite, Metro, Control and WoW.
Queue submit out of order might not work as expected yet since we are currently serializing many virtual queues on top of one queue, but this feature does not seem to be used by much content out there. It would not work at any rate with current vkd3d as it stands anyways.
For now I'm keeping the old implementation around in case we need a fallback for certain drivers, but the goal is to remove the fallback path eventually.
Also, fix the test suite to not rely on non-monotonically increasing values. https://docs.microsoft.com/en-us/windows/win32/direct3d12/user-mode-heap-synchronization#fences specifies it as monotonically increasing, so not sure why tests don't follow that.
Fixes #65.
> Implement VK_KHR_timeline_semaphores

- README
- configure.ac
Implementing VK_KHR_timeline_semaphore extension requires vulkan
headers > 1.1.124.
Signed-off-by: Sveinar Søpler <cybermax@dexter.no>
> vkd3d: Require Vulkan headers > 1.1.124

- README
- configure.ac
VK_KHR_buffer_device_address requires Vulkan headers > 1.1.129
Signed-off-by: Sveinar Søpler <cybermax@dexter.no>
> vkd3d: Require vulkan headers > 1.1.129

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Basically replaces `D3D12_{GRAPHICS,COMPUTE}_PIPELINE_STATE_DESC` with a custom struct that we can extend as necessary. Needed to support newer rendering features exposed through the new CreatePipelineState API.
> vkd3d: Refactor pipeline state creation.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Disables dynamic states that are not needed by the pipeline to save some API calls. All dynamic state is now applied at draw time, which will be necessary anyway in case we have to implement shader-based copy operations.
Note that pipelines currently always use one viewport without issuing a warning, so for now, only support one in `RSSetViewports` as well. I have a change in the pipeline which lifts this restriction.
> vkd3d: Rework dynamic states.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Title. Moves things around a bit so that we only have to pass the dynamic state struct to look up the pipeline.
> vkd3d: Support multiple viewports.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Used by RE Engine games for a small potential performance gain.
> vkd3d: Implement depth bounds test.

- libs/vkd3d/resource.c
On NVIDIA we sometimes fail to place images on a heap because the memory
region was dedicated. Only bother trying this if heap flags only allow
buffers.
Fixes a GPU crash in The Division.
> vkd3d: Do not always attempt dedicated buffer allocation for heap.

- libs/vkd3d/command.c
Fixes one source of crashes in Monster Hunter World.
> vkd3d: Check whether root descriptors are defined.

- libs/vkd3d-shader/spirv.c
- libs/vkd3d/resource.c
Fixes more crashes that occur in the game, as well as a bunch of `fixme` messages and related rendering issues.
> Various Monster Hunter World fixes

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Prepares for a rewrite of queue submission, the legacy path is never
run in practice and will likely break in subtle ways.
> vkd3d: Remove legacy fence/semaphore path.

- libs/vkd3d/device.c
> vkd3d: Improve d3d12_device_SetResidencyPriority stub.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
D3D12 supports out-of-order signal and wait. So does Vulkan timeline
semaphores. However, in Vulkan we don't have an infinite amount of
virtual queues. We must potentially map multiple D3D12 queues on top of
Vulkan, which might lead to a deadlock when app attempts to
wait-before-signal if the two queues are mapped to the same physical
Vulkan queue.
In order to solve this, we need to hold back submissions until we know
it is safe to do so. To make this work in practice as simply as possible, each
ID3D12CommandQueue has its own submission thread, which will block on an
ID3D12Fence's pending timeline value for a Wait command. The main reason to use a
submission thread is that resolving this directly in
ID3D12CommandQueue::Signal is extremely tricky and potentially
needs recursively locking …
> vkd3d: Implement threaded submission queue.

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Maps the heap once during creation and fills it with zeroes, which seems to fix some font texture corruption in Resident Evil 2, and may slightly reduce CPU overhead in some games that call Map/Unmap very frequently as those functions are now essentially no-ops (except flush/invalidate on some platforms).
> Persistently map host-visible heaps

- libs/vkd3d/command.c
- libs/vkd3d/device.c
This fixes a couple of 32-bit compiler warnings, atleast for GCC-9.3.
eg.
```
libs/vkd3d/command.c:5722:11: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 7 has type ‘SIZE_T’ {aka ‘long unsigned int’} [-Wformat=]
5722 |     FIXME("iface %p, meta_command %p, parameter_data %p, parameter_size %zu stub!\n",
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5723 |             iface, meta_command, parameter_data, parameter_size);
|                                                  ~~~~~~~~~~~~~~
|                                                  |
|                                                  SIZE_T {aka long unsigned int}
```
Signed-off-by: Sveinar Søpler <cybermax@dexter.no>
> vkd3d: Fix 32-bit compiler warnings

- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Allows us to support border colors for both static and descriptor-based samplers, which fixes a whole bunch of warnings in various games (e.g. MHW, Control). The following caveats apply:
- D3D12 static border colors do not distinguish between float/uint border colors.
- Arbitrary border colors are not (yet) supported in the Vulkan API.
> Sampler rework

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
This shouldn't have any impact on performance on any recent-ish hardware since we stay within a format family. 
I'm exploiting this for shader-based depth<->color copies since we may need to be able to create an `R32_FLOAT` view for pretty much any `R32_*` image.
> Support CastingFullyTypedFormatSupported.

- include/vkd3d_windows.h
We will need to receive 2-byte WCHARs from apps.
> vkd3d: Enforce that WCHAR is actually a WCHAR.

- tests/d3d12.c
> vkd3d: Functions take void as argument type in C.

- libs/vkd3d/command.c
Fixes rendering issues in The Talos Principle.
We need to revisit this eventually in order to handle both binary occlusion queries as well as unavailable queries properly, but this will should for now.
> vkd3d: Apply heap offset to destination buffer in ResolveQueryData.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Fixes most validation errors related to image layouts, as well as some real-world issues like The Talos Priciple showing corruption with MSAA enabled.
Here's how it works:
- Based on the usage flags, a common layout is determined for each image resource.
- The common layout is always used for descriptors.
- For transfer operations, the images involved will be transitioned to the `TRANSFER_{SRC,DST}_OPTIMAL` layout before the transfer op itself, and back to their common layout afterwards.
- Color attachments are transitioned to `COLOR_ATTACHMENT_OPTIMAL` when beginning a render pass, and back to their common layout afterwards.
- Depth-stencil attachments are transitioned to the pipeline-specific DSV layout when beginning a render pass, and back to their common layout afterwards.
- …
> Barrier rework

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Optimizes useless barriers away and fixes performance regressions introduced with the barrier rework (only SotTR seems to be really affected).
> Suspend renderpasses

- include/vkd3d_d3d12.idl
- libs/vkd3d/command.c
- tests/d3d12.c
These pass on WARP and AMD's driver.
Functionality that isn't being tested yet includes the `CopyTiles` function as well as the new shader instructions. The latter are only required for Tier 2.
> Add tests for tiled resources

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Uses the new `VK_EXT_custom_border_color` extension added in the Vulkan 1.2.140 update. The test is going to fail on systems not supporting the extension for obvious reasons.
> Implement sampler border colors

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Title. Also fixes a bug when calling `UpdateTileMappings` for an image that has no mip tail.
> Implement CopyTiles

- configure.ac
Needed for VK_EXT_custom_border_color.
> configure: Check for 1.1.140 headers.

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Need float16_int8 and subgroup with extended types to implement new SM
6.2 features. For now, skip over SM 6.1 features until someone makes use
of them.
> vkd3d: Enable SM 6.2 features.

- libs/vkd3d/command.c
> vkd3d: Apply heap offsets for ExecuteIndirect buffers.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Allows us to skip a few annoying extension check in the memory allocation code.
We should aim for 1.2 later down the line in order to significantly reduce the extension spam, but considering the required driver support it's too early to do that.
> vkd3d: Require Vulkan 1.1.

- configure.ac
> configure.ac: Report that 1.2.140 is required, not 1.1.140.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Currently, when allocating a D3D12 heap for placed resources, we just pick a memory type, hope that all resources are going to be supported on it, and fail if the corresponding Vulkan heap is full on some drivers (see #124). Also, we unconditionally report `D3D12_RESOURCE_HEAP_TIER_2` even on Tier 1 hardware.
As a solution, figure out which memory types support which type of resource and use that information to find compatible memory types, and iterate over compatible memory types until the allocation succeeds.
This needs a bit more testing and I'll probably have to revisit the usage flags for the dummy resources we use to gather the memory type information, but generally seems to work on both my RX 480 and RTX 2060 systems.
> Memory allocation rework

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Gets rid of the full barrier on command buffer end.
Instead, do what D3D12 wants, which is to serialize all
ExecuteCommandLists. Simplify the existing timeline sempahore setup for
sparse queues and use it for all submissions.
> vkd3d: Serialize all queue submissions.

- Makefile.am
- configure.ac
- demos/demo_xcb.h
- include/vkd3d_sonames.h
- libs/vkd3d/device.c
- tests/d3d12_crosstest.h
There is no reason to not load Vulkan dynamically, otherwise, we must
have loader dev packages installed, which is not ideal.
> vkd3d: Remove dependency on linking directly against libvulkan.

- include/vkd3d_shader.h
- include/vkd3d_windows.h
- libs/vkd3d-shader/dxbc.c
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/trace.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d-utils/vkd3d_utils_private.h
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_main.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
This makes it consistent across tests and vkd3d.
> Make nameless unions really nameless

- include/private/vkd3d_atomic.h
- include/private/vkd3d_common.h
- include/private/vkd3d_spinlock.h
- libs/vkd3d/command.c
There is no stdatomic available on MSVC so let's clean things up.
This moves all the atomic helpers to vkd3d_atomic.h and implements all platform's spinlocks in entirely the same way.
> vkd3d: Refactor atomics

- libs/vkd3d/device.c
This isn't going to change. Drivers use this to do special things,
so changing it would probably cause a bunch of random problems anyway.
>  vkd3d: Remove PACKAGE_NAME usage for engine version

- libs/vkd3d-shader/spirv.c
> vkd3d-shader: Don't use return value semantics in void functions

- .gitignore
- .gitmodules
- Makefile.am
- build-win32.txt
- build-win64.txt
- configure.ac
- demos/demo.h
- demos/meson.build
- include/meson.build
- include/private/vkd3d_common.h
- include/private/vkd3d_threads.h
- include/vkd3d_windows.h
- libs/meson.build
- libs/vkd3d-common/meson.build
- libs/vkd3d-shader/meson.build
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader.def
- libs/vkd3d-utils/meson.build
- libs/vkd3d-utils/vkd3d_utils.def
- libs/vkd3d/meson.build
- libs/vkd3d/vkd3d.def
- meson.build
- meson_options.txt
- programs/meson.build
- tests/d3d12_crosstest.h
- tests/meson.build
- vkd3d_version.c.in
This moves VKD3D to build with the Meson build system.
This also builds dxil-spirv as a dependency, using Meson's CMake intergration.
This also makes vkd3d build fine on Windows, Native Linux and Cross-Building with MinGW64 :)
*(For cross-building vkd3d.dll with MinGW you will need to install mingw64-cmake in your package manager, fwiw chaotic-aur provides this package)*
> Move to Meson build system

- demos/demo.h
- tests/d3d12_crosstest.h
Revert removal of MinGW forceinline hacks.
They are necessary or MinGW fails to build.
> build: Fix MinGW build.

- include/private/vkd3d_debug.h
- libs/vkd3d-common/debug.c
- libs/vkd3d-shader/meson.build
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-utils/vkd3d_utils_main.c
- libs/vkd3d/vkd3d_main.c
- meson.build
I had to manually pull in the dependencies of `dxil-spirv` in Meson to link against; initially I thought that was because they weren't declared `PUBLIC` in CMake, but that didn't work either -- seems to be a bug with the Meson CMake integration.
This also tosses the `VKD3D_DEBUG_ENV_NAME` stuff that's really janky, it links back into vkd3d-common from the modules so you can set the env var to enable debugging per-module. Given this is static now we'd have two so that doesn't work anymore, so I just made it use `VKD3D_DEBUG` always which imo is much more sensible.
> vkd3d-shader: Build statically

- include/private/vkd3d_atomic.h
- include/private/vkd3d_spinlock.h
- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
- Implemented sequential consistency when compiling under MSVC and optimized the atomic code to be as efficient with memory  and compiler barriers as possible.
- Switched to using the `__atomic` builtins as opposed to C99's stdatomic because Clang requires that the variable be `_ATOMIC` when using that which creates problems.
- Defined our own memory orders to avoid potentially causing problems with other libraries or things that use vkd3d (and because we need a nice way to map these -> `__ATOMIC_RELEASE` etc
- Made `enqueued_fence_count` a uint32_t from a size_t -- this is probably what this was meant to be based on discussion on Discord.
> Misc. atomic fixes

- Makefile.am
- configure.ac
- libs/vkd3d-shader/spirv.c
Removes quite obsolete dependency on SPIRV-Tools, which, from what I was told, is unused anyway.
Affects only autotools–based builds, Meson never used it in the first place.
> Remove SPIRV-Tools

- build-win32.txt
- build-win64.txt
- libs/vkd3d-shader/meson.build
- meson.build
Removes the CMake dependency and solves some trouble building.
> build: Use Meson subproject for dxil-spirv

- libs/vkd3d-common/utf8.c
- libs/vkd3d/resource.c
- meson.build
Fix some signed comparison warnings and enable warning level 2 in Meson
(Equivalent to -Wall -Wextra)
Should help spot some of the enum issues we've had in the past...
> build: Enable warning level 2

- libs/vkd3d/vkd3d_main.c
This reverts commit 0384362065aa64650b01985195fde0f91401402d.
It is not allowed to use RS 1.1 serialization for the non-versioned
entry point. RS 1.1 serialization must use the versioned entry point.
Reverting this fixes the relevant test case in d3d12.c:12522.
> Revert "vkd3d: Add support for serializing root signature version 1.1"

- libs/d3d12/main.c
- meson.build
- Enable stdcall-alias and stdcall-fixup link flags when building for x86
- Declare exports as __declspec(dllexport) on MinGW
- Works around a bug where things exported in the .def do not have those exported correctly.
> Use stdcall alias on x86

- libs/d3d12/d3d12.def
These were originally copied from d3d12.crosslib.def but it turns out those are wrong.
> d3d12: Fix ordinal exports

- libs/vkd3d/command.c
Otherwise, if a render pass gets suspended twice in a row, we never emit the barrier because render_pass_suspended will be
set to false the second time. Fixes some validation errors in Hitman 2.
> vkd3d: Fix suspended render pass state tracking.

- Makefile.am
- README.md
- include/private/vkd3d_threads.h
- libs/d3d12/main.c
- libs/vkd3d-common/debug.c
Various refactors to be able to use pthread_once_t instead of spinlocks, also adds support for logging to a file instead of always logging to stderr.
> More logging improvements

- libs/vkd3d/swapchain.c
Changes the interface type to a more generic typedef, similar to the other d3d12 interfaces. SetHDRMetadata was basically copy-pasted from DXVK.
> Implement IDXGISwapChain4

- meson.build
Debian 10 ships 0.49.
Signed-off-by: Andrew Eikum <aeikum@codeweavers.com>
> build: Drop minimum meson version

- demos/demo_win32.h
- libs/vkd3d-shader/dxbc.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/swapchain.c
- meson.build
- programs/vkd3d-compiler/main.c
- tests/d3d12.c
- tests/d3d12_crosstest.h
Adds some warning disable flags to vkd3d (as well as dxil-spirv) to remove the more useless warnings MSVC emits. The more relevant warnings, GCC does not seem to catch with our current flags, so fixed them as well.
MSVC now compiles clean, so we should be able to catch actual stupid bugs now without being boggled down by 200+ warnings.
> Make MSVC compile clean

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Tries to make use of our existing render pass transitions where possible, and otherwise just emits a barrier transitioning away from ``UNDEFINED``.
> vkd3d: Implement DiscardResource.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12.c
- tests/d3d12_crosstest.h
Requires QueryPerformanceCounter to work properly, so no support on native Linux builds at the moment.
> vkd3d: Implement calibrated timestamps

- programs/vkd3d-compiler/meson.build
pthread_once is required everywhere now, so we have to include the threads dependency.
> programs: Fix building vkd3d-compiler.

- meson.build
Generates `/usr/lib64/pkgconfig/libvkd3d.pc` as:
```
prefix=/usr
libdir=${prefix}/lib64
includedir=${prefix}/include
Name: vkd3d
Description: The VKD3D 3D Graphics Library
Version: 1.1
Libs: -L${libdir} -lvkd3d
Cflags:-I${includedir}/vkd3d
```
> meson: generate pkgconfig files, install headers

- tests/meson.build
Doesn't build, and I can't really be arsed to figure out why right now. I don't think we're using this test anyway.
> meson: Drop d3d12_invalid_usage target.

- libs/vkd3d-shader/spirv.c
It's the argument to the opcode which consumes the final resource handle
or pointer which needs to marked as NonUniformEXT. Was missing this for
sampled images and bindless UAV counters.
> vkd3d-shader: Add NonUniformEXT decoration where required.

- meson.build
The `git describe` command currently fails because there are no tags yet. Using `--always` lets it fall back to the current commit hash.
Signed-off-by: Jens Peters <jp7677@gmail.com>
> build: Use the commit hash as fallback for the built-in version.

- libs/vkd3d/resource.c
Fixes a crash on drivers that don't support null descriptors.
Image UAVs and other descriptor types cannot have counters.
Signed-off-by: Philip Rebohle <philip.rebohle@tu-dortmund.de>
> vkd3d: Set counter buffer view to null view for buffer UAVs.

- libs/vkd3d/resource.c
Derp.
Removes the NULL check because it's legal to pass NULL to vkDestroy* functions.
> vkd3d: Don't destroy UAV counter view if it's the null view.

- README.md
- build-win32.txt
- build-win64.txt
This removes the wine dependency for cross-builds but adds a dependency for mingw-tools instead.
Signed-off-by: Jens Peters <jp7677@gmail.com>
> build: Use widl from mingw-tools.

- include/private/hashmap.h
- include/private/vkd3d_common.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- Eliminates reference counting views as well as the per-descriptor spin lock, which speeds up descriptor copies by a factor of 5 on RADV according to the microbenchmark.
- Views are now stored in an open addresing hash map as part of the resource they are created from.
- Non-static samplers are now stored globally per device, this also avoids duplicates.
Tested with Shadow of the Tomb Raider, Death Stranding, Control, Monster Hunter World.
Part 2 is going to refactor the actual Vulkan descriptor updates so that we can trim down the `d3d12_desc` struct, which may reduce overhead a bit further.
> Descriptor rework, Part 1

- libs/vkd3d-shader/dxil.c
Enable per-thread allocators in dxil-spirv to drop overhead with 100x or so.
> Massively reduce overhead in HZD shader compilation stage

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Deduplicates static samplers and uses a global descriptor pool for the static sampler sets used in root signatures, so we don't have to allocate them at bind time.
> Static sampler rework

- libs/vkd3d/resource.c
> vkd3d: Fix crash in validation layer when freeing static descriptor set.

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
These memory types might end up being used as fallback memory types,
which is problematic due to their tiny sizes, and unexpected performance
behavior. Generally, when we want to fallback, we should cleanly fall
back to system memory rather than a different device local type.
> vkd3d: Never attempt to use PCI-pinned memory types.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Need to handle large (> 4G) jumps in timeline value, which is not
supported by all implementations.
There is no good way to handle that, so rewrite and clean up timeline
semaphore handling by separating the timeline into a virtual timeline
(which can rewind and jump around arbitrarely) and a physical timeline
which increments by one each time.
> vkd3d: Rewrite timeline semaphore handling.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12.c
Title. Passes the already existing test for WriteBufferImmediate and silences log spam in Horizon Zero Dawn. Perf impact in that game seems acceptable even with the fallback path.
> Implement WriteBufferImmediate

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
There is no resource state associated with this, so emit the barrier at
the end of a command buffer based on trivial tracking.
> vkd3d: Emit host memory barrier as needed.

- libs/vkd3d/command.c
Fixes textures when inspecting items in the inventory in RE2 and RE3.
RE2 binds 5 vertex buffers and then draws using a pipeline that only uses 3 of those.
Because VKD3D only binds buffers that are in the `vertex_buffer_mask`, we only bind 3 of the 5 buffers. The `VKD3D_DYNAMIC_STATE_VERTEX_BUFFER` gets cleared though so when the game then sets a PSO that uses all 5 vertex buffers we need to actually bind all 5.
When actually binding the vertex buffers we just clear the `dirty_vbos` (or `dirty_vbo_strides`) bits that represent the buffers that actually got bound. So when switching pipelines we check whether there are `dirty_vbo` bits left and set `VKD3D_DYNAMIC_STATE_VERTEX_BUFFER`.
Alternatively we could just get rid of the pipeline vbo mask and bind all vertex buffers in the first …
> vkd3d: Set VKD3D_DYNAMIC_STATE_VERTEX_BUFFER when changing pipelines

- include/private/vkd3d_threads.h
- libs/vkd3d/device.c
- meson.build
Works around a winpthread bug with pthread_mutex_init on garbage data and improves performance by using raw SRW locks on all Win32 targets.
The memsets are a bit more dubious, but was reported to influence HZD behavior (the caps struct), and can't hurt ...
> vkd3d: Implement some MinGW workarounds

- libs/vkd3d/cache.c
Small oversight, reportedly fixes newly introduced crashes in HZD on older drivers.
> vkd3d: Don't call vkGetPipelineCacheData on a null handle.

- libs/vkd3d/state.c
Not relevant anymore, and should see good uplift on NV depending on
content.
> vkd3d: Remove bindless CBV workaround.

- libs/vkd3d/resource.c
Forgot to `git add` this change last time, which currently leads to build issues. Sorry about that.
> vkd3d: Remove d3d12_descriptor_heap_set_index_from_magic.

- libs/vkd3d/state.c
> vkd3d: Use VK_NULL_HANDLE instead of NULL for VkPipelineCache

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Eliminates a lot of the format lookups that kept happening in code that shouldn't probably be looking up formats.
NULL checks that have been removed were impossible anyway as there was already a `is_buffer` or equivalent check and it's impossible to have texture resources with NULL formats due to the desc validation.
> Keep track of resource's `vkd3d_format`

- libs/vkd3d/state.c
Just drop the VkSubpassDependency in this case to satisfy the validator,
since stages == 0 is not allowed. Observed the error in Metro and Death Stranding.
Fix #288.
> vkd3d: Fix validation error when render pass is used without attachment.

- include/vkd3d.h
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
For correctness, we will need to defer any initial resource state
handling to the queue timeline. Here, we will build an UNDEFINED ->
common layout barrier if (and only if):
- The resource is marked to care about initial layout transition.
- We are the first queue thread to observe that initial_transition
member is 1 (atomic exchange).
- The first use of the resource was not marked to be a discard.
E.g., if the first use of the resource is an alias barrier, we must
not emit an early barrier. The only we should do here is to clear the
initial_transition member, and leave it like that.
A command list maintains a list of d3d12_resources which *might* need a
transition. For the first frame a resource is used (or so), it will not
have the flag cleared yet, so multiple command lists might add …
> vkd3d: Rewrite initial resource state tracking

- include/private/vkd3d_atomic.h
- include/vkd3d_windows.h
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
We cannot compare resource pointers or view pointers,
since the pointers might have been recycled.
This leads to a scenario where we're not updating descriptors we're
supposed to, and the GPU reads a stale descriptor.
Fixes a GPU hang in Death Stranding (and possibly lots of other weird
crashes as well).
> Use descriptor cookies to avoid comparing against stale pointers

- libs/vkd3d/state.c
If rendering to A8 format, do not apply output swizzle in non-PS stages.
> vkd3d: Fix menu regression in RE2.

- include/vkd3d.h
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
The major change here is removing the concept of PRESENT_TRANSITION. This is broken design since we cannot deal with implicit state decay and promotion in case the application samples from it. We never hit this code path anyways in practice.
There is also no safe way to not use user buffers, so remove old code paths which dealt with that. At the very least, we need to guarantee round-robin behavior and buffer count behavior.
In the meta module, add some helpers to deal with swapchain render passes and pipelines.
Also, add a mechanism to queue up image memory barriers to a VkQueue which deals with initial state transition for swapchain images. The initial state for presentable images is COMMON/PRESENT, so technically, applications might present images which have never been rendered to.
> Rewrite how swapchains are blitted to screens.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Only on hardware where `minStorageBufferAlignment <= 4`, since we know nothing about root descriptors except their VA.
> Support raw SSBO path for root descriptors

- libs/vkd3d/meta.c
Signed-off-by: Philip Rebohle <philip.rebohle@tu-dortmund.de>
> vkd3d: Fix descriptor layout mismatch for ClearUAV.

- demos/demo_xcb.h
These failed to compile previously due to us removing INITIAL_STATE_TRANSITION and deprecating PRESENT_STATE_TRANSITION.
> demos: Fix compiling demos on Linux

- include/vkd3d.h
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/vkd3d_api.c
All this flag does is make resource creation fail.
> vkd3d: Remove VKD3D_RESOURCE_PRESENT_STATE_TRANSITION

- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
We cannot rely on alignment analysis since games are buggy and screw up
RAW vs structured on occasion.
> vkd3d: Do not perform any alignment analysis for SSBOs.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Now that bindless is a hard requirement for all D3D12 descriptor types, and after the introduction of binding set flags with the Raw SSBO work, we can just pick an arbitrary set to cram extra bindings into, such as the UAV counter address buffer, and soon the offset buffer for raw SSBOs. This way  we don't have to track and bind these at draw time.
> Move UAV counter address binding to bindless descriptor sets.

- libs/vkd3d/vkd3d_private.h
Ensures that lower bits of `d` won't interfere with pattern created by other arguments.
> vkd3d: Bit–shift last argument of MAKE_MAGIC

- include/private/hashmap.h
- include/private/vkd3d_common.h
- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Cursed workaround for SSBO alignment requirements on Nvidia. Should fix #266 for good.
At least the last commit should probably not be merged before DXIL support lands, since it may break games using DXIL shaders.
> Implement offset buffers

- libs/vkd3d/cache.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/vkd3d_private.h
- meson.build
- vkd3d_build.h.in
- vkd3d_version.c.in
- vkd3d_version.h.in
Version string is used in logging for information purposes, but pipelines blobs and libraries use `uint64_t`–based commit hash. Using fixed–size integer silences warnings about string length and makes storing build info a little more space–efficient.
The hash is obtained separately from version string and is shifted to the left by 4 bits if the working tree is dirty.
Supersedes PR #284.
> build: Use separate version string and build hash

- include/vkd3d_utils.h
- libs/vkd3d-utils/meson.build
- libs/vkd3d-utils/vkd3d-proton-utils.def
- libs/vkd3d-utils/vkd3d_utils_main.c
Use .defs for vkd3d-utils exports
Otherwise this won't work in MSVC because it'd technically be re-defining the D3D12 function prototypes with the decltypes.
There is no other nice way around this.
Closes #323
> vkd3d-utils: Fix building under MSVC

- demos/meson.build
- include/meson.build
- libs/d3d12/meson.build
- libs/vkd3d-shader/meson.build
- libs/vkd3d-utils/meson.build
- libs/vkd3d/meson.build
- programs/vkd3d-compiler/meson.build
- tests/meson.build
This makes headers a dependency rather than a generator target.
This also means we get proper dependency tracking of them between projects.
Supercedes: #225
> build: Only generate headers once

- build-linux32.txt
- package-release.sh
Replace this with our own build-linux32.txt
Closes: #336
> build: Eliminate need for x86-linux-gnu cross file

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Makes use of the per-resource view map for render targets and implements some missing functionality for these descriptor types, like NULL descriptors (trivial) and descriptor copies.
Closes #325.
> Rework RTV/DSV descriptors

- include/private/hashmap.h
- programs/vkd3d-compiler/main.c
Fixes warnings about implicit declaration of these functions
when building demos/programs which could be very bad on x64 if used.
> vkd3d: Include correct memory header in hashmap 

- README.md
- libs/meson.build
- libs/vkd3d/meson.build
- meson.build
- meson_options.txt
- package-release.sh
- tests/meson.build
Enables d3d12 on windows by default. 
`-Denable_standalone_d3d12=true` will cause a warning, but proton build scripts should keep working.
Tested on linux and with mingw64.
Closes: #335
> build: Replace enable_standalone_d3d12 with tristate enable_d3d12.

- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
This is useful for debugging when we receive SPIR-V from RADV crash dumps or Fossilize, where we do not have VK_EXT_debug_utils or VKD3D_SHADER_DUMP_PATH to lean on.
> Emit OpSource with shader hash

- libs/vkd3d/state.c
Avoids some unnecessary late compiles in Monster Hunter World, and probably others.
> vkd3d: Only care about DSV mismatch if the pipeline actually uses it.

- libs/vkd3d/command.c
Fixes a memory leak when inserting debug markers.
> vkd3d: Free string after PIX decoding

- libs/vkd3d/swapchain.c
- Implement DXGI_PRESENT_TEST properly with support for OCCLUDED.
- Fix a crash when minimizing in HZD
- Ignore ALLOW_TEARING
> Fix Horizon Zero Dawn Minimize Crash + Error Spam

- libs/vkd3d/device.c
The fix which enabled waveops detection broke HZD, since we never tested
with that feature enabled.
Keep it disabled until we can figure out what is going on.
> vkd3d: Disable waveops for time being.

- libs/vkd3d/command.c
> vkd3d: Use SHADER_READ for CBV visibility when using ROOT_VA CBV.

- libs/vkd3d/command.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
We have observed a lot of large GPU bubbles when using back-to-back
timeline semaphores to synchronize GPU submissions. Use prebaked
pipeline barrier command buffers instead.
To resolve queue sparse serialization, use two binary semaphore pairs to
resolve this. There is no need to use timeline semaphores in this case.
Fix https://github.com/HansKristian-Work/vkd3d-proton/issues/377.
> vkd3d: Use pipeline barrier command buffers for queue serialization.

- libs/vkd3d-shader/dxil.c
Allows us to capture dxil compiler messages in log.
> vkd3d-shader: Add debug log callback to DXIL.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Extends the initial resource transition framework to allow for query heap initialization, which is necessary because D3D12 queries are immediately considered available. Fixes `test_resolve_query_data_in_reordered_command_list`, but as a compromise, returned values for uninitialized timestamp queries are non-zero, thus breaking another test. `todo`s have been changed accordingly.
This also greatly simplifies our impementation of `ResolveQueryData`.
> Rework query initialization

- libs/vkd3d/command.c
> vkd3d: Fix uninitialized variable in initial WSI transition.

- include/private/vkd3d_threads.h
- libs/vkd3d/device.c
> vkd3d: Use static init for device map.

- libs/vkd3d/state.c
> vkd3d: Completely disable writes when it is not safe to enable color write mask.

- libs/vkd3d/resource.c
Silences misleading log spam in AC:Valhalla, which apparently uses UAVs to downsample 3D textures.
> vkd3d: Consider mip level for 3D UAV slice check.

- libs/vkd3d/command.c
Assassin's Creed Valhalla sets more than one viewport, and many of those are empty. As a result, we incorrectly ignore all those viewport updates - instead, we should pass empty viewports to Vulkan as well, which is legal as long as `width > 0.0`.
Fixes some major issues with AC:Valhalla only rendering to specific quadrants of the window.
> vkd3d: Handle empty viewports.

- libs/vkd3d/command.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/resource.c
- libs/vkd3d/shaders/cs_resolve_binary_queries.comp
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12.c
Replaces non-zero sample counts with 1 in order to match D3D12 behaviour.
> Binary occlusion query fixup

- libs/vkd3d-shader/spirv.c
- tests/d3d12.c
This came up in DXVK recently. The problem is that some Vulkan drivers (RADV+ACO, AMDVLK, Nvidia on *some* architectures) will return infinity when passing a number larger than `FLT16_MAX`, whereas DXBC requires us to return `FLT16_MAX` instead, so we need to manually fix that up in our shaders.
> vkd3d-shader: Fix infinity handling in f32tof16.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/cs_resolve_binary_queries.comp
- libs/vkd3d/vkd3d_private.h
Paves the way for a potential predication rework, and potentially improves performance in case the app directly resolves queries into host memory.
> Use scratch buffer for binary query fixup

- libs/vkd3d/cache.c
> vkd3d: Fix segfault when freeing pipeline library.

- libs/vkd3d/command.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/cs_predicate_command.comp
- libs/vkd3d/shaders/cs_resolve_predicate.comp
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12.c
This essentially solves three problems:
- D3D12 requires 64-bit predicates, whereas `VK_EXT_conditional_rendering` uses 32-bit conditions. This adds a resolve pass which emits a 32-bit predicate to a scratch buffer.
- Using the scratch buffer also means that changing the predicate value after enabling predication can no longer change the behaviour of predicated draws, as is required by D3D12. This seems to just work™ on Vulkan drivers, but should be undefined behaviour.
- Official AMD drivers do not support `VK_EXT_conditional_rendering`. To support predication on those drivers, we use indirect draws and dispatches (with indirect count for predicated indirect draws) instead.
Was a bit of a failed attempt to get AC:Valhalla to run on AMDVLK, which requires Predication support, …
> Rework predication

- libs/vkd3d/resource.c
> vkd3d: Bind WHOLE_SIZE when using null SSBO descriptor.

- include/private/hashmap.h
- include/private/vkd3d_atomic.h
- include/private/vkd3d_rw_spinlock.h
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
The goal here is to avoid the worst contention when the view map is hammered with texel buffers. Generally, the hit rate will be ~100% for texel buffers with offset, so optimizing for that case is a reasonable thing to do.
Tested on DS and HZD which hammer the view map constantly.
> Use RW spinlocks for view map.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Improves performance in Ghostrunner a bit (~47 -> 50 FPS in the very beginning of the game on my Polaris).
The next step would be to begin/end occlusion queries without interrupting the current render pass.
> Batch vkCmdResetQueryPool calls in separate command buffer

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
Mesa will assert if not, and the format must be known here.
Fix #418.
From spec: "The Image Format of an OpTypeImage declaration must not be Unknown, for variables which are used for OpAtomic* operations."
> vkd3d-shader: Emit typed format for UAVs which use atomics.

- tests/d3d12.c
> tests: Remove old is_bug for conditional rendering.

- README.md
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
RADV MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7967
> Add support for VK_VALVE_mutable_descriptor_type

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Further increases performance in Ghostrunner. This works by deferring `vkCmdBeginQuery` to draw time, and ending these queries 
We should probably do a lot of real-world testing before merging this and see if we ever hit the `FIXME`, since the behaviour in that case is technically incorrect. We can't easily virtualize queries like DXVK does since D3D12 queries work quite similarly to Vulkan query pools; it's not completely impossible to do some local remapping for any command list that runs into this problem and allocate multiple queries per d3d12 query, but doing so would make resolving queries significantly harder.
> vkd3d: Do not interrupt render pass for occlusion queries.

- libs/vkd3d/command.c
> vkd3d: Clarify comment about not using MEMORY_READ/WRITE.

- libs/vkd3d/vkd3d_private.h
Caused crash when using a driver that did not support
mutable_descriptor_type.
Was using the wrong enum bitfields ... Sigh, type safe enums would be nice.
Regression caused during refactor in review most likely.
> vkd3d: Fix embarassing enum bug.

- tests/d3d12.c
Fixed on Mesa master now (FMASK bug).
> tests: Remove is_bug for MSAA clear test.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Passes test suite. Needs testing w.r.t game stability and performance, thus marking as draft.
> vkd3d: Add fast path for mutable descriptor copies

- tests/d3d12.c
Otherwise we'll have two test failures.
> tests: Mark sparse depth image test as TODO on RADV.

- libs/vkd3d-shader/spirv.c
This is a patch from upstream vkd3d that we should pull in as well to avoid potential precision issues.
> Handle precise modifier

- libs/vkd3d/command.c
We currently never reset occlusion queries. For some reason, validation layers do not report this.
> vkd3d: Reset inline queries in BeginQuery.

- include/vkd3d_shader.h
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/device.c
- meson.build
We always build with DXIL, not using autotools anymore.
> vkd3d-shader: Remove DXIL being optional.

- libs/vkd3d/command.c
> vkd3d: Always align scratch buffer for query data to 8 bytes.

- libs/vkd3d/device.c
As far as I understand, there's no reason for us to enable it.
> vkd3d: Disable accelerationStructureCaptureReplay feature.

- libs/vkd3d/device.c
We somehow missed the fact that this even has a feature cap even though we support the function.
> vkd3d: Set WriteBufferImmediateSupportFlags properly.

- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Implement DXGI_FORMAT_B4G4R4A4_UNORM

- demos/demo_win32.h
- include/private/vkd3d_common.h
- include/private/vkd3d_debug.h
- include/private/vkd3d_utf8.h
- include/vkd3d.h
- include/vkd3d_d3d12.idl
- libs/d3d12/main.c
- libs/vkd3d-common/debug.c
- libs/vkd3d-common/string.c
- libs/vkd3d-common/utf8.c
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-utils/vkd3d_utils_main.c
- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- meson.build
- tests/d3d12.c
- tests/d3d12_crosstest.h
- tests/vkd3d_api.c
Achieves this with C standard stuff alone, and no compiler hacks.
> vkd3d: Eliminate wchar_size, use UTF-16 string literals

- .github/workflows/test-build-linux.yml
Uses my fork of gcc-problem-matcher to note down warnings and annotate them in files for pushes and PRs
> build: Add GCC problem matcher to build tests

- meson.build
Needed for 64-bit atomics on 32-bit architectures on Clang.
> build: Link against libatomic on x86 when using Clang

- tests/d3d12.c
- tests/d3d12_crosstest.h
Stress tests internal implementation details which we will hit internally with CreateCommittedResource and CreateHeap.
Creates many allocations, aims to either clear all of them to a fixed value, or does nothing, which should return 0.
Also verifies safety when attempting to free an idle ID3D12Heap, since it might be attempting to zero memory on a GPU queue.
> Add heap suballocation stress test

- include/private/vkd3d_atomic.h
Avoids alignment warnings on 32-bit.
> vkd3d: Use UINT64* instead of uint64_t* in 64-bit CAS.

- libs/vkd3d/swapchain.c
Silences a whole bunch of log spam in Control.
> vkd3d: Only print some swapchian FIXMEs once.

- libs/vkd3d/memory.c
The difference between a range's offset and the aligned offset may be greater than the size of that range.
> vkd3d: Fix integer underflow when checking for suitable free ranges.

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Drastically reduces the number of allocations in some games, which helps RADV performance.
We still use dedicated allocations if the driver sets the corresponding hint, or if we cannot create a buffer on the same memory type to clear the allocation.
> Suballocate committed textures if possible.

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Temporary workaround for release build to avoid causing vkCreateDevice failures on Ampere
with Steam Linux runtime.
> vkd3d: Do not attempt to enable anything RT related.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
If we're signalling and waiting on same physical queue (always true for
current SINGLE_QUEUE define), we can rely on submission boundary
synchronization which doesn't require any extra submissions to resolve.
Avoids awkward GPU driver bubbles with back to back signal -> wait pairs
with timeline.
Observed 2% GPU uplift on RE2 on AMD.
> vkd3d: Elide timeline semaphore waits which can be satisfied implicitly.

- include/private/vkd3d_memory.h
- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
This is required for DXR since we will need to be able to place table VAs directly in shader record buffers.
This is also a decent CPU optimization since we no longer need to make potentially cold derefs to resolve heap_offset when recording command buffers.
> Use virtual descriptor heap GPU VAs

- tests/d3d12.c
> tests: Remove some todo/is_bug()s for RADV.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
Instead, gather the necessary bits from the root signature. May be more efficient on some drivers.
> Don't use VK_SHADER_STAGE_ALL for push constants

- libs/vkd3d/device.c
These only clutter up validation in testing.
> vkd3d: Ignore known useless validation warnings.

- libs/vkd3d/command.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Gives a massive boost on NVIDIA for some reason.
RADV defers push constant update, so ALL_STAGES doesn't have
that much of a perf hit.
~20% uplift in RE2, ~5% uplift in CP77 from some quick and dirty testing.
Seems to be heavily content dependent either way.
Also a bug fix, since we would clobber graphics push constants from
compute and vice versa if both graphics and compute used the same root
signature.
> vkd3d: Redirect push constants to their bind point stages.

- include/vkd3d.h
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- meson.build
- meson_options.txt
- tests/vkd3d_api.c
Enabling VK_EXT_debug_utils comes at some overhead in Wine due to the object tracking required. There is also likely a non-zero overhead in some native implementations also.
By enabling this conditionally, we can also avoid additional overhead from apps that set debug labels on both the Vulkan and front-end side.
The default condition is to enable it when building with Renderdoc integration or in debug builds.
It's needless overhead to have control flow at the start of every entrypoint. Branch predictors are good but there's no reason to keep what is essentially dead code behind an if sitting around (especially given we aren't marking it as unlikely).
> Enable debug_utils conditionally, disable tracing for Release

- libs/d3d12/meson.build
- libs/vkd3d-utils/meson.build
- meson.build
Avoids a copy in the Wine loader as well as enables debug symbols to work in perf.
> build: Use --file-alignment=4096 with MinGW

- libs/vkd3d/resource.c
This seriously hurts performance in AC:Valhalla.
> vkd3d: Silence log spam around Min LOD Clamp.

- meson.build
Using consts for array sizes is a C++-ism, and in GCC in C-mode it won't fold literal constants, and will instead prefer to make a VLA.
> build: Warn about VLA usage

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Remove dead code from d3d12_command_list.

- libs/vkd3d-shader/dxil.c
Dump DXIL in reflection code as well in case the parser is broken.
> dxil-spirv: Trivial fix for parsing out-of-order INST_BR.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Detects updates of adjacent buffer tiles and full image subresource updates, which should reduce the number of `VkSparseMemoryBind` and `VkSparseImageMemoryBind` structures passes to the driver. We don't do anything fancy for adjacent image tile updates etc.
Passes tests and works with AC:Valhalla.
> Optimize sparse binding

- libs/vkd3d/acceleration_structure.c
> vkd3d: Convert RTAS geometry flags.

- libs/vkd3d/command.c
- tests/d3d12.c
> vkd3d: Ignore IASetVertexBuffers for NULL pViews.

- libs/vkd3d/command.c
Found while running the Windows version of our test suite with wine.
> vkd3d: Fix potential hang in d3d12_command_queue_Release.

- libs/vkd3d/vkd3d_private.h
Otherwise we can do an alligned_malloc with a non-aligned size as the descriptor size is 48 for a d3d12_rtv_desc otherwise.
> vkd3d: Align d3d12_rtv_desc to D3D12_DESC_ALIGNMENT

- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Fix stack overflow in debug_vk_memory_property_flags.

- README.md
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Enable VK_KHR_sampler_mirror_clamp_to_edge.

- libs/vkd3d/state.c
Fixes #613. The test app has both the depth test and stencil test disabled but depth-bounds test enabld, so we currently end up removing the depth attachment from the render pass.
> vkd3d: Use depth attachment when depth bounds test is enabled.

- package-release.sh
- setup_vkd3d_proton.sh
Hi.
We should go for the [portable shebang-form](https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)&oldid=878552871#Portability) to get the bash environment. /bin/bash is also not a real thing on most distros anymore¹. This will bring compatiblity for distros who don't create the compat-symlink.
¹ Most distros:
```
file /bin
/bin: symbolic link to usr/bin
```
Signed-off-by: Fabian Bornschein <fabiscafe@mailbox.org>
> Switch to the portable shebang

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
- tests/d3d12.c
Works around a lot of broken code in FH4.
The D3D12 runtime is verified to be robust against these bugs, so we also need to be.
Fix #618.
> Various PSO robustness fixes

- libs/vkd3d-shader/spirv.c
- tests/d3d12.c
When looking into https://github.com/HansKristian-Work/vkd3d-proton/issues/227, I found a few spirv-val errors in basically any hull shader we emit.
This fixes those, as well as hopefully the reported issue in which we were emitting SV_ClipDistance builtin arrays for hull shaders when they should really just be per-vertex state dealt with by DS.
> Misc. Hull Shader Fixes

- libs/d3d12/main.c
This was missed and somehow magically worked fine when running the test suite for me.
> d3d12: Initialize optional extensions

- CHANGELOG.md
- meson.build
Adds the changelog for this release and bumps the Meson version.
> Release VKD3D-Proton version 2.3.1

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Unless I miss something in the spec, `shaderDrawParameters` is an optional feature in 1.1 and should be enabled with `VkPhysicalDeviceShaderDrawParametersFeatures` before use. It seems like this was missed while porting from 1.0 to 1.1 because the original extension doesn't have a feature struct.
> vkd3d: Enable and require shaderDrawParameters.

- libs/vkd3d/raytracing_pipeline.c
> vkd3d: Fix missing trace arg in SetPipelineStackSize

- README.md
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
This is widely supported on desktop, and the non-robustness path is essentially completely untested at this point. For upcoming workarounds, having non-robustness2 in the picture is going to get more and more annoying, so it's time to flip it to required.
The non-robustness2 path is also broken for any robust UAV either way, since stores are not masked.
> Require robustness2

- libs/vkd3d-shader/spirv.c
Fixes root descriptors when BDA support is disabled.
> vkd3d-shader: Don't apply offset buffers for non-bindless resources.

- tests/d3d12.c
Found it while debugging driver issues. Doesn't actually fix any driver issue, but we need a barrier here regardless.
> tests: Add missing UAV barrier in bindless counter test.

- tests/d3d12.c
Was using 0x8000 / 0xffff instead of 0x200 / 0x3ff, rounded differently
on NV.
> tests: Fix Clear UAV test constant.

- libs/vkd3d/swapchain.c
In cases where acquire image is blocking, we should call that after
presentation to avoid latency when the app calls present.
This avoids weird inverse frame cadences with Mesa WSI right now,
as acquiring an image is always a blocking call until it is complete.
In cases when we aren't blocking, this kicks off the acquisition so
it can be waited upon by the next frame -- and in the future by
the submissions themselves as semaphores.
Documentation says that this should always be 3 without WAITABLE_OBJECT
unlike in D3D11 where it will use the DXGI device's frame latency.
This stops runaway presentations in the non-blocking acquire image case
with the new semaphore setup.
Use another set of semaphores to wait for the image acquisition on the
GPU.
In the non-blocking vkAcquireNextImageKHR …
> Low latency presentation and frame latency fixes

- libs/vkd3d/resource.c
> vkd3d: Fix descriptor QA checks for CBV_AS_SSBO.

- include/vkd3d_win32.h
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
This also updates subprojects/Vulkan-Headers to 1.2.180
This is needed for VK_NVX_binary_import and VK_NVX_image_view_handle.
Signed-off-by: Roshan Chaudhari <rochaudhari@nvidia.com>
Reviewed-by: Liam Middlebrook <lmiddlebrook@nvidia.com>
>  vkd3d: Enable binary import and image view handle extensions

- libs/vkd3d/command.c
Found some validation errors in UAV clear tests.
> vkd3d: Fix view object leak when creating fallback UAV clear view.

- libs/vkd3d/memory.c
We cannot use the memory requirement output, since we will zero-clear
memory with a size that might be larger than the VkBuffer size.
> vkd3d: Use correct allocation size for memory block.

- libs/vkd3d/device.c
Our internal copy shaders are fine, but we get benign errors about
sample count being wrong since we alias descriptors.
> vkd3d: Add validation error workaround.

- libs/vkd3d/debug_ring.c
- libs/vkd3d/descriptor_debug.c
If we destroy device right after creating it, we risk a deadlock.
> vkd3d: Fix potential deadlock in descriptor QA checks.

- libs/vkd3d/command.c
Fixes random broken AO in Necromunda on RADV.
> vkd3d: Invalidate binding state on query resolve.

- libs/vkd3d-shader/spirv.c
> vkd3d-shader: Emit NoContraction for MAD/DFMA.

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
This will be necessary to handle multi-plane images correctly, where the view format will be a color format (with `VK_IMAGE_ASPECT_COLOR_BIT`) while the image itself will have `VK_IMAGE_ASPECT_PLANE_{0,1}_BIT` set. Also removes some unnecessary warnings.
For depth-stencil images, this also behaves correctly: In order to sample the stencil aspect of a depth-stencil image, the plane index must be set to 1 in D3D12, and failing to do so crashes the AMD native driver.
> vkd3d: Handle plane index when creating image descriptors.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Yet another iteration of this.
- Honor resource barriers for resource states which cannot automatically
decay or promote. This includes COLOR_ATTACHMENT, UNORDERED_ACCESS and
VRS image. If SIMULTANEOUS_ACCESS is used, we can still promote, and
we handle that by setting common layout to GENERAL for these resources.
- Avoid redundant barriers in render passes since normal resource
barriers will always make sure we are already in
COLOR_ATTACHMENT_OPTIMAL.
- Do not force GENERAL layout if resource has UNORDERED_ACCESS flag set.
As this is not a promotable state, we have to explicitly transition
into it. I tested this on validation layers, where even COMMON state
refuses to promote to UAV state. The exception here of course is
SIMULTANOUS_ACCESS, but we handle that properly now.
- Verify that …
> vkd3d: Rewrite image layout transition handling

- libs/vkd3d/swapchain.c
Randomly appears in GravityMark, odd that validation didn't find this in
other cases.
> swapchain: Synchronize before resetting blit command buffer.

- libs/vkd3d/swapchain.c
This matches DXVK implementation behavior and fixes HZD alt-tabbing and alt+enter jank.
Fix #715.
> Recover window position when leaving fullscreen properly

- libs/vkd3d/device.c
Currently only format1 information is being returned for D3D12_FORMAT_SUPPORT.
Signed-off-by: Roshan Chaudhari <rochaudhari@nvidia.com>
> vkd3d: Return format2 information for d3d12_device_CheckFeatureSupport

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Separate out an explicit per_plane query for the cases where we need it.
> vkd3d: Handle multiple planes in d3d12_resource_get_subresource_count.

- README.md
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
We need separate depth stencil layouts to be able to use pipeline barrier with aspectMask != formatAspectMask. Without this, we cannot implement DiscardResource() correctly, so make it a required extension. It's widely supported and core Vulkan 1.2, so should be issue.
> vkd3d: Support discarding single DS aspect

- tests/d3d12.c
- Passes WARP.
- Expected failures on AMD native windows driver are marked. The range check behaves as expected if we were to ignore dynamic stride rules in Vulkan. Elements which should be OOB are not marked as such.
- Fails quite a lot of RADV. Will file bugs.
- (Need to test NV)
> tests: Test edge cases for VBO robustness with weird strides

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Not correct, will need spec additions to handle it properly.
Fixes ground rendering in DIRT 5.
> vkd3d: Add workaround for MinLODClamp.

- libs/vkd3d/command.c
This spams constantly in Dirt 5.
> vkd3d: Make invalid RTV for attachment FIXME_ONCE

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Goal here is to avoid unnecessary image layout transitions when render
passes toggle depth-stencil PSO states. Since we cannot know which
states a resource is in, we have to be conservative, and assume that
shader reads *could* happen.
The best effort we can do is to detect when writes happen to a DSV
resource. In this scenario, we can deduce that the aspect cannot be
read, since DEPTH_WRITE | RESOURCE state is not allowed.
To make the tracking somewhat sane, we only promote to OPTIMAL if an
entire image's worth of subresources for a given aspect is transitioned.
The common case for depth-stencil images is 1 mip / 1 layer anyways.
Some other changes are required here:
- Instead of common_layout for the depth image, we need to consult the
command list, which might promote the layout to …
> Promote and keep depth-stencil resources in OPTIMAL as long as possible

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/state.c
Avoids late pipeline compile in DIRT5. Use the meta struct instead of random scan entry point.
> Reflect HS patch count in DXIL

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/vkd3d_private.h
This was passing through flags of the root signature not the shader interface flags of it.
Need to get the shader interface flags of the root signature instead.
> vkd3d: Fix RT local root signature interface flags

- libs/vkd3d/device.c
FloatControlProperties struct appears to be broken, and it does seem to
work just fine.
> vkd3d: Allow SM 6.2 on NV.

- libs/vkd3d/state.c
Diablo 2 Resurrected creates all graphics pipeline with `RasterizedStream = D3D12_SO_NO_RASTERIZED_STREAM`.
This makes VKD3D-Proton disable rasterization, resulting in a black screen for that game.
Fixes #625
Props to DadSchoorse for pointing me at `rasterizerDiscardEnable`.
I've modified vkd3d gears to set `RasterizedStream = D3D12_SO_NO_RASTERIZED_STREAM` and it still rendered on Windows, so I assume it's ignored if the number of SO entries is 0. I don't know how stream output works (besides a super barebones understanding of it) so I'm not sure if that's the correct solution. As usual, the Microsoft docs aren't exactly in-depth about it.
It's certainly better than the current behavior though.
> vkd3d: Only disable raster based on SO stream if SO is used.

- libs/vkd3d-common/debug.c
Allows us to stay sane when correlating logs.
> vkd3d-common: Log TID in Wine's format.

- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_resource.c
- tests/d3d12_test_utils.h
- tests/d3d12_tests.h
Implement GetCopyableFootprints for depth-stencil, which fixes crashes when entering benchmark in F1 2021.
> Planar copyable footprints

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Emitting render pass clears while we're in the process of starting a render pass overrides dsv layout tracking info.
> vkd3d: Remove deferred clears.

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
There are titles clearing the same descriptors constantly.
This leads to unnecessary updates that can become costly.
This commit introduces a new flag to track when D3D12 descriptors are not null, and skips clearing them if they are already null.
Descriptors are assumed to be null by default.
This fixes a performance regression introduced by 9983a1720f683b6366a9cf7a864a6efc94978e1d
Signed-off-by: Rodrigo Locatti <rlocatti@nvidia.com>
> vkd3d: Optimize repeated null descriptor updates

- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Need to initialize the set mask so that copies happen properly
on default-initialized descriptors. Also, move the current_null_type to
metadata so that it's properly copied on descriptor copy.
> vkd3d: Fix regressions when introducing null-copy elision.

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
470.62.02 driver fixes the bug, but need to keep workaround for older 470 releases.
> Narrow scope of pipeline cache workaround

- libs/vkd3d/device.c
Works around a game bug. It uses texture() inside divergent control flow.
Can't believe I missed these. The shader uses two `texture` calls and the rest are `textureLod`... only saw one when I first looked then was surprised that it didn't fix anything. :v
> vkd3d: Add shader quirks for Psychonauts 2

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxbc.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d/state.c
- tests/d3d12_pso.c
- tests/d3d12_tests.h
F1 2021 attempts to create pipelines with blending enabled on R32_UINT, but we're supposed to validate this or ignore it explicitly depending on the output signature.
> Integer blend validation

- libs/vkd3d/command.c
```../../libs/vkd3d/command.c(2417,22): error: conflicting types for 'd3d12_command_list_get_depth_stencil_resource_layout'
static VkImageLayout d3d12_command_list_get_depth_stencil_resource_layout(const struct d3d12_command_list *list,
^
../../libs/vkd3d/command.c(63,17): note: previous declaration is here
static uint32_t d3d12_command_list_get_depth_stencil_resource_layout(const struct d3d12_command_list *list,```
> vkd3d: Fixing compile errors on Windows.

- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_profiled.h
- libs/vkd3d/heap.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- Move `impl_from`s into the header.
- Previously we were doing function calls for every single object cast from another compilation unit which is... no.
- Initial thoughts are that it's gross to require vtable exposed everywhere for the asserts, but C++ requires that for dynamic_cast so, meh.
- Remove `unsafe_impl_from`s. These can just be the normal one and the checks get optimized away now. (yay)
- Optimization for calling ResolveQueryData with zero queries.
- Moved `d3d12_query_heap_type_get_data_size` to header.
> impl_from overhead refactor

- libs/vkd3d/resource.c
Fix failure in test_create_heap where a TIER_2 host visible heap was
attempted, but failed due to recent DEATHLOOP fixes.
> vkd3d: Fix test suite regression on NV.

- libs/vkd3d/command.c
- tests/d3d12_command.c
- tests/d3d12_tests.h
Also refactor discards so that a complete discard does one barrier instead of one per subresource.
> Allow DiscardResource on UAVs

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_descriptors.c
- tests/d3d12_render_target.c
- tests/d3d12_tests.h
In DIRT5, the game attempts to rendering to RTV1, but RTV 1 is unbound. Based on testing on native drivers, this is supposed to work with no validation errors. The fix is to introduce fallback pipeline checks somewhat similar to DSV unknown tests, except this is in reverse. Rendering to NULL DSV is actually disallowed, but NULL RTV is allowed ... *shrug*
> Fix unbound RTV rendering scenarios

- libs/vkd3d-shader/spirv.c
> vkd3d-shader: Handle vectorized FIRSTBIT_HI.

- tests/d3d12_sync.c
> tests: Remove obsolete check for lack of wait-before-signal support.

- include/private/vkd3d_atomic.h
Previous check was not exhausting.
Closes: #830
> vkd3d: Use 64bit atomics on all 64bit platforms

- include/private/vkd3d_string.h
- libs/vkd3d/device.c
I encountered another game, Bus Simulator 22, which has the same broken shader as Necromunda, including the same hash.
Looks like a bunch of UE4 games are affected, so check if the exe name ends in `-Shipping.exe` and apply these quirks for these shader hashes going forward.
I reeeeally would have liked to have done a regex here, but it looks like there's nothing nice and portable in the std and pulling in some external dependency is kinda gross, there is this which was licensed nice and is small however https://github.com/kokke/tiny-regex-c if we want to consider it.
Fixes Bus Simulator 22
> Add a generic set of UE4 quirks

- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
If we need to fallback in both VRS and non-VRS scenarios, we need to key
on it. Fixes segfault in DIRT5 when toggling VRS.
Fix #837.
> vkd3d: Add static pipeline variant flag to pipeline key.

- libs/vkd3d/state.c
In d3d12, input element alignment needs to be the _minimum_ of 4 and the size of the type. See the D3D11 spec, section 4.4.6, which behaves similarly:
https://microsoft.github.io/DirectX-Specs/d3d/archive/D3D11_3_FunctionalSpec.htm#4.4.6%20Element%20Alignment
This is correctly taken into account when generating, e.g., the ``vertex_buffer_stride_align_mask`` used for validation, but is not taken into account when ``D3D12_APPEND_ALIGNED_ELEMENT`` is used to automatically place input elements. Currently, vkd3d always assumes the alignment is 4.
This means that, for example, bytes or shorts should be packed tightly together when ``D3D12_APPEND_ALIGNED_ELEMENT`` is used, but are instead padded to 4 bytes.
Fixing this makes units appear in Age of Empires IV (see vkd3d-proton issue #880 for …
> vkd3d: Handle D3D12_APPEND_ALIGNED_ELEMENT for <4 byte wide elements

- tests/d3d12_copy.c
> tests: Only check lower 24-bit when testing D24 copies.

- libs/vkd3d/descriptor_debug.c
- libs/vkd3d/vkd3d_descriptor_debug.h
It's hidden behind ifdef, so didn't show up in CI.
> vkd3d: Fix some type errors after idl update.

- tests/d3d12_device.c
> tests: Remove obsolete format feature check.

- libs/vkd3d/resource.c
- tests/d3d12_descriptors.c
Also, only emit MinLOD struct where actually needed. Simplifies some logic and shuts validation layers up for time being.
> Remove TODO for MinLOD test.

- libs/vkd3d/resource.c
We can bind texel buffers at scalar alignment now.
The warning is misleading for placed resources, since 64k never aligns
with a float3.
> vkd3d: Remove misleading FIXME.

- libs/vkd3d/resource.c
NVIDIA drivers apparently cannot support EXTENDED_USAGE linear
images for whatever reason, so attempt to create these images without
the creation flag.
Fixes crash in DEATHLOOP on NV.
> vkd3d: Attempt to create linear image without EXTENDED_USAGE.

- libs/vkd3d/command.c
> vkd3d: Consider query pool when merging query ranges.

- libs/vkd3d/device.c
Fixes artifacts in The Ascent.
> vkd3d: Enable quirk for further UE4 shaders.

- libs/vkd3d/command.c
Just consider them to alias any other resource.
> Handle sparse buffer aliasing for transfer overlaps.

- include/private/hashmap.h
- include/private/vkd3d_threads.h
- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This PR focuses on slight refactors which will be required for saving any SPIR-V in cache.
- First, move over to RW locks for pipeline libraries. It was supposed to be a big optimization, but then I realized that the lock was unlocked before create_pipeline_state(), so it's not as useful as initially thought. Still nice to have though.
- Then, add a hash which should be used for storing SPIR-V and deduplicated blobs. It's the same one as used for DXBC shader blobs, just make it more reusable.
- Finally, add concept of shader interface key. Given equivalent DXBC + root signature + device UUID + shader interface key, we should guarantee a 1:1 match with SPIR-V.
- Store the shader interface key in pipeline library as well and validate it.
> SPIR-V caching in pipeline libraries - Phase 1

- .github/workflows/test-build-windows.yml
I've wasted much more time on this than I'm willing to admit.
The build failing before #965 is merged is a feature, not a bug.
> build: Add workflow for MSVC builds

- libs/vkd3d/command.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/fs_copy_image_stencil.frag
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12_copy.c
Also cleans up a benign fixme that was misreporting in at least BF2042.
Also adds some additional tests for DS <-> DS copies and stencil <-> color copy.
> Implement COLOR -> STENCIL copies if stencil export is supported.

- libs/vkd3d/command.c
This is benign and easily gets spammed a TON.
We will warn if an indexed draw is actually made like this.
> vkd3d: Remove warning for setting NULL index buffer.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_render_target.c
Fixes crash in Guardians of the Galaxy.
Fix https://github.com/HansKristian-Work/vkd3d-proton/issues/937.
> Invalidate pipeline/render pass when changing NULL RT state.

- .github/workflows/test-build-windows.yml
If you can't beat them, avoid the confrontation?
I still have no idea why that one Meson call fails but whatever Meson wants to do there, the `vs2022` backend handles on its own.
The second commit pulls the acquisition of environment variables into the build step itself so they don't leak between x86 and x64 builds, otherwise MSBuild complains about paths being too long.
> Fix Meson breakage on Windows CI

- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/renderdoc.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_pso_blob.c
Builds on https://github.com/HansKristian-Work/vkd3d-proton/pull/980.
This became basically a rewrite in the end, and it got too awkward to
split these commits in any meaningful way.
The goals here were primarily to:
- Support serializing SPIR-V and load SPIR-V.
To do this robustly requires a lot more validation and checks to make
sure end up compiling the same SPIR-V that we load from cache.
This is critical for performance when games have primed their pipeline
libraries and expect that loading a PSO should be fast. Without this,
we will hit vkd3d-shader for every PSO, causing very long load times.
- Implement the required validation for mismatched PSO descriptions.
- Rewrite the binary layout of the pipeline library for flexibility
concerns and performance.
If the pipeline library is …
> SPIR-V caching - Phase 2 - Rewrite pipeline library implementation

- libs/vkd3d/state.c
Checking for pNext here is too brittle and causes crashes when dynamic
rendering path is added.
Also need to chain in existing pNexts.
> vkd3d: Fix potential crashes when VK_KHR_dynamic_rendering is added.

- libs/vkd3d/swapchain.c
> swapchain: Add env-var to override swapchain images.

- libs/vkd3d/resource.c
> vkd3d: Make error message for buffer alignment more direct.

- libs/vkd3d/device.c
The hooks are in the generic function.
Fallout from latest descriptor opts.
> vkd3d: Don't enable fast descriptor copy path for descriptor QA.

- include/private/vkd3d_common.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Optimize resource descriptors for cache access. From digging deep into how we implemented this stuff, the existing implementation is kinda horrible for cache. In this code, every nanosecond counts when games spam it 30k+ times per frame.
We have to remove the entire idea of a heap_offset / heap pointer being stored inside a d3d12_desc. This is almost a guaranteed miss and shows up clearly in perf.
Don't look at the destination descriptor metadata at all. Saves a cache miss. We don't need to be so conservative with eliding redundant copies. The older MUTABLE path never bothered with any of this, and it was fine.
Finally, optimize for single descriptor copies, since we don't have to look back into d3d12_device. If we can, just store things inline. When we have to copy many descriptors, we …
> Rewrite memory layout of d3d12_desc

- libs/vkd3d/resource.c
this removes them from the bitscan path
followup from 4b07535909ef369f3f976d8f5787d8e132101e8d
> vkd3d: optimize memory access pattern for sampler descriptors

- libs/vkd3d/raytracing_pipeline.c
See #990
As per the comment by @adamnv https://github.com/HansKristian-Work/vkd3d-proton/issues/990#issuecomment-1046087877
> vkd3d: Add case for D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE

- libs/vkd3d/device.c
Allows debug callbacks to go through in Wine.
> vkd3d: Enable debug_utils if vk_debug is enabled.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/meta.c
- libs/vkd3d/state.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Keeping this as a draft for now since merging without support from stable drivers is not an option.
Tests pass on Nvidia, requires Vulkan beta driver 470.62.12 or later.
Needs more testing on RADV as its implementation of the extension comes along, and testing in actual games, although for that we'll need some sort of working Proton build with winevulkan support for this extension. I haven't checked if this is provided by proton-experimental bleeding edge yet.
> Use VK_KHR_dynamic_rendering

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Required extension by VK_KHR_fragment_shading_rate and
VK_KHR_separate_depth_stencil_layouts, but we don't care about enabling
any features or use it directly.
Needed to silence validation errors.
> vkd3d: Enable VK_KHR_create_renderpass2.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
The idea behind this change is that some implementations don't really care if we use GENERAL layout, so might as well just use it to avoid having to carefully transition to correct image DSV layouts everywhere.
The key improvement here is in rendering passes which split depth-rendering over many parallel command lists. This is a very common pattern which we ideally want to avoid.
Also, since we're no longer doing transitions for DSV images, drop the somewhat redundant UNDEFINED transition in Clear*View() if we don't need to handle aliasing rules.
> Avoid implicit DSV layout transitions with GENERAL layout when feasible

- libs/vkd3d/cache.c
- libs/vkd3d/vkd3d_private.h
To prepare for a world where we could have device-internal pipeline libraries, reshuffle some things around as a first step:
- Refactor out serialization call to a separate function so that an outer call could atomically GetSerializedSize + Serialize.
- Instead of taking a big write lock on StorePipeline, take locks as necessary when registering SPIR-V / PSO cache blobs. This allows us to use read-writer locks in StorePipeline and avoids contention when we have duplicate SPIR-V / PSO objects. This will be particularly useful for internal magic caches.
- Make use of internal reference counts in pipeline library as well. This allows us to hold pipeline libraries inside the device as needed without creating cycles.
> Refactor pipeline library locking and ref-count strategy

- README.md
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This is basically required for not horrible stutter and performance and
is widely supported.
> vkd3d: Require VK_EXT_extended_dynamic_state.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Not sure if this is doing the right thing since this seemed a bit *too* simple, but it passes our tests on RADV.
> vkd3d: Do not create pipeline variants for NULL RTVs.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Make it more obvious what it's really trying to check.
> vkd3d: Rename DSV UNKNOWN workaround query.

- libs/vkd3d/state.c
There are strict limits on number of descriptors which can be used,
and we have to use MUTABLE + single set to make this work.
> vkd3d: Enable MUTABLE_SINGLE_SET for Intel GPUs.

- README.md
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12_streamout.c
- tests/d3d12_tests.h
IBStripCut only applies to strip primitive types. Use extended_dynamic_state2 when we can and fallback pipeline when we can't.
Builds on #1038.
> Disable primitive restart for list topologies

- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This was off by one, at some point, which could cause a stack buffer overrun which is naughty.
Replace this with just an ARRAY_SIZE on the dynamic_state_list for the array size.
> vkd3d: Remove VKD3D_MAX_DYNAMIC_STATE_COUNT

- libs/vkd3d/device.c
> vkd3d: Ignore cached SPIR-V if we're dumping SPIR-V.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
And make it a hard requirement since driver support overlaps fairly well with KHR_dynamic_rendering. Removes the need to create a whole bunch of dummy resources.
> Use VK_KHR_maintenance4.

- include/private/vkd3d_common.h
Found in review of https://github.com/HansKristian-Work/vkd3d-proton/pull/1065#discussion_r852864906
> common: Fix _BitScanForward usage on MSVC.

- include/private/vkd3d_platform.h
- libs/vkd3d-common/debug.c
- libs/vkd3d-common/meson.build
- libs/vkd3d-common/platform.c
- libs/vkd3d-common/profiling.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
getenv is deprecated on windows due to security and threadsafe issues. It also (for our purposes) will not reflect environment variables set after the program/dll has started. This is exposed via vkd3d_platform already present in vkd3d.
> Use Windows specific environment calls for better Windows compatibility

- libs/vkd3d/cache.c
> vkd3d: Fix MSVC warning about redundant snprintf argument.

- libs/vkd3d/cache.c
- libs/vkd3d/descriptor_debug.c
- libs/vkd3d/device.c
- libs/vkd3d/renderdoc.c
- libs/vkd3d/swapchain.c
Replace with the new vkd3d_get_env wrapper.
Fix #1081.
> vkd3d: Clean up straggling getenv() calls.

- libs/vkd3d/device.c
Found regressions in Deathloop FSR1/2.
> Disable native FP16 on NV for now.

- libs/vkd3d/resource.c
- tests/d3d12_descriptors.c
5.3.9.5 in D3D11 spec explicit outlines when we can
cast to R32{U,I,F}. The D3D12 validation layers
seem to have missed this.
Fixes assertions in RADV when running test under debug.
Fix #1119.
> tests: Avoid tripping out of spec UAV casts.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Break up CopyTextureRegion into three stages.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
The main idea is to introduce a "command list batch" system where it compares for the type of the previous and current command for every non render-pass command, and in the case there are consecutive CopyTextureRegion calls, batch them so we can issue layout transition barriers in bulk instead of interrupting after each copy.
See each commit for more details.
> Optimize consecutive CopyTextureRegion by batching the barriers

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Just use VK_NULL_HANDLE. We rely on the disk cache to exist anyways
here. We never serialize the global pipeline cache, so it might just
confuse drivers into disable disk cache if anything.
Also reduce memory bloat.
Also gets rid of very old NV driver workaround where we forced global
pipeline cache.
> vkd3d: Remove the global VkPipelineCache.

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Required by KHR_dynamic_rendering. Caught by updated validation layers.
> vkd3d: Enable VK_KHR_depth_stencil_resolve.

- demos/gears.c
This function doesn't indicate failure and the possibility of the early return
causes -Wmaybe-uninitialized warnings.
> demos: Don't pretend to handle allocation failure.

- libs/vkd3d/device.c
> vkd3d: Enable F1 2020 quirks on 2019 as well.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
This is the core meat of the implementation.
The basic gist is:
- CreateCommandSignature -> IndirectCommandLayoutNV. Translate the token types directly. Realign as required.
- Request a meta shader.
- Create a patch buffer with commands { type, src_offset, dst_offset }
- On ExecuteIndirect, allocate scratch buffers as needed, dispatch the patch CS and then ExecuteGeneratedCommands.
The follow-up after that focuses on batching the patching. The D3D12 specs mention this as an explicit optimization drivers should do, so might as well. The basic idea is that if we have not observed any transitions to INDIRECT in the current command list, we know for sure that there cannot be dependent writes to any indirect commands, so we can hoist the patching to the vk_init_command buffer instead.
Further …
> Execute indirect state - Phase 3

- libs/vkd3d/cache.c
Native Win32 does not like it.
Works fine in Wine, but ran into this while testing a bit on Windows.
> cache: Unmap files before attempting to delete.

- libs/vkd3d-shader/spirv.c
offset_component_count was set to 0 for cubes, but GRAD path also
uses the variable to check how many components to use for GRAD.
OFFSET is not supported for cubes, so that's likely why it was bugged.
Fixes Redout 2 asserts in https://github.com/ValveSoftware/Proton/issues/5921
> vkd3d-shader: Fix GRAD sample on cubes.

- libs/vkd3d/command.c
Transfer batch can clobber graphics pipeline for e.g. depth->color copies.
Hence, flushing the batches after applying the graphics pipeline set by the
app can cause correctness issues.
To prevent that, do the transfer batch flush first before we apply any
render-related states.
Signed-off-by: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
Closes: #1143
> vkd3d: Fix transfer batch clobbering state in begin_render_pass.

- libs/vkd3d/resource.c
Docs explicitly specify that placed RTV / DSV resource must be properly
initialized before use, either on first use or after aliasing barriers,
so there should be no need to perform initial layout transition.
Fixes spurious GPU hangs in Hitman III where application aliases
an indirect buffer and a DSV. The DSV is cleared after the indirect
buffer is consumed, but the initial_layout_transition is triggered and
HTILE init clobbered the buffer.
> vkd3d: Do not perform initial layout transition for placed RTV / DSV.

- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
Alignment and size requirements cannot be returned to application. Fall back to committed resources here instead.
Fixes weird GI flicker in Guardians of the Galaxy, since it ended up placing 3x 16x16x80 R32_UINT textures close to each other. In OPTIMAL tiling, the size was < 128 KiB, but ~300 KiB in linear tiling due to 256 byte aligned rows on AMD.
> Do not attempt to place linear host visible textures on heaps.

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/device.c
- Add some trace debug logs for RTAS info build.
- Check for index format != UNKNOWN instead of IBO VA != nullptr when deciding whether to use indexed or list build. UE5 hits this case.
- Update dxil-spirv to master with some CFG fixes.
> Misc RT improvements

- include/vkd3d_d3d12.idl
- libs/vkd3d/command.c
- tests/d3d12_sparse.c
- tests/d3d12_tests.h
In this test we attempt to bind a page to memory which is subsequently freed. We don't access the freed page in the normal path, and this passes on all drivers. (RADV with a tiny workaround).
With the exploratory path, we aim to figure out how the freed memory behaves, both with respect to values we read, and how sparse feedback behaves (is the page considered fully mapped or not).
NV / AMD / Intel all pass test. No D3D12 validation errors.
- NV: Faults. Device lost.
- AMD: Sparse feedback suggests the freed page is valid. Reads garbage value. Does not fault.
- Intel: Sparse feedback suggests the freed page is valid. Reads zero (instead of expected 42). Does not fault.
NV / AMD pass. Intel cannot run due to lack of dynamic rendering.
NV and AMD behave exactly the same as D3D12 …
> Add exploratory test for sparse mapping behavior.

- tests/d3d12_sync.c
> tests: Avoid potential UB in fence_wait robustness test.

- libs/vkd3d/device.c
This change will allow people to select whichever variant of the game
they want if the GPU supports DXR.
It is especially relevant for RTX owners as only the DX12 version
supports DLSS. DLSS currently requires PROTON_ENABLE_NVAPI=1 but may
start shipping as a default via Steam Play Manifest.
> vkd3d: Enable DXR for Control.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Apparently we hit a bug in Saint's Row where we clear an RTV that's bound to the D3D command list but wasn't used by any Vulkan pipeline, so it's not bound to the Vulkan command buffer.
> Fix clearing attachments that are not currently active

- libs/vkd3d/state.c
> vkd3d: Fix comment in d3d12_pipeline_state_can_use_dynamic_stride.

- libs/vkd3d/command.c
- tests/d3d12_render_target.c
- tests/d3d12_tests.h
This tweet suggested that there were bugs with rendering without attachments: https://twitter.com/SheriefFYI/status/1564830690977320960.
> "radv/amdgpu: The CS has been cancelled because the context is lost." Fellas, there's a good chance I'm running into a GPU hang on Steam Deck when rendering with neither color nor depth stencil targets attached (yes, that's actually valid for clustering etc.)
I had a look and I couldn't see we had any test coverage for this. The test checks layered rendering, since we had some questionable code when emitting rendering info, since layerCount was 1.
Both AMD and NV at least seem to ignore layerCount when using no attachments, but the spec is a little vague if this is legal. The closest I could find was:
> It is legal for a subpass to use no color or …
> Add test for rendering with no attachments

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Introduces a new enum rather than using VkPipelineBindPoint everywhere, and cleans up how D3D12 binding info is stored and accessed.
The plan is to add another value to the `vkd3d_pipeline_type` enum for mesh shading pipelines, so we can distinguish those from regular graphics pipelines.
> Clean up bind point handling

- libs/vkd3d/device.c
Not an ideal check, but it's the best we can do in a wine environment since we cannot observe the RenderDoc layer directly through VK_EXT_tooling_info.
> vkd3d: Auto-enable FORCE_HOST_CACHED when renderdoc is detected.

- libs/vkd3d/cache.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Begins the process of refactoring how PSOs are created.
The overall goal of the first PR phases is to refactor how we init the various interface structs for the vkd3d-shader compilation steps.
> Implement VK_EXT_shader_module_identifier - Phase 1

- libs/vkd3d/cache.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This continues the refactor, and focuses on splitting out the code as much as possible so that we can compile SPIR-V late as desired. Should also be a nice refactor in general, since the existing graphics pipeline creation is an insane mess.
Also sets up systems so that we can duplicate DXBC blobs in case we have to compile to SPIR-V late. This can happen if we get a successful module identifier compile, but a future fallback pipeline might not exist in driver cache. In this case we'll have to fall back to creating SPIR-V modules on demand. On future runs of the application, we should never miss in the driver cache (ideally).
> VK_EXT_shader_module_identifier - Phase 3

- libs/vkd3d/device.c
> vkd3d: Add VKD3D_CONFIG environment for disabling host memory imports.

- README.md
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Trivial alias, support both variants for now.
> vkd3d: Enable promoted VK_EXT_mutable_descriptor_type.

- libs/vkd3d/device.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Implements HDR display support.
Tested with Deep Rock Galactic + RE: Village on Windows.
For completeness, we also should get IDXGIOutput::GetDesc1 ColorSpace + metadata setup, I tested with that hardcoded with the values for my display for now. But this completes the vkd3d-proton part and enables HDR to at least be enabled.
> vkd3d: Implement HDR

- libs/vkd3d/cache.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Goal here is to shrink the vkd3d-proton.cache by 95% or so. I verified that I'm hitting "successfully created from identifier" in various scenarios.
I also verified the feasibility with Fossilize.
The basic idea we need to validate is that if we have the shader identifier cache, and a Fossilize archive of the pipelines, we can achieve 100% cache hits after a FOZ replay. I verified this in our test suite.
In the validation run, everything works as expected. In real games, pipeline_library_log confirms that all pipelines are created from identifier. I also verified that on a driver update, we fail to create from identifier, and we fall back to creating SPIR-V. The next run after that, we hit in the shader caches again, as expected.
```
#!/bin/bash
rm vkd3d-proton.cache*
rm -f …
```
> VK_EXT_shader_module_identifier - Phase 4/4

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
write_full_subresource may allow us to transition from UNDEFINED so that we can skip the initial layout transition, but not in the scenario where the resource has multiple subresources.
> vkd3d: Only skip initial layout transition if single subresource.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
Avoids invalidating a perfectly good cache and caches are kind of meaningless when capturing anyways.
Also adds some ad-hoc logging for descriptor heap allocations which affects capturing overhead by a lot.
> Disable shader caches as well when capturing

- libs/vkd3d/command.c
This whole situation was reported as a Vulkan CTS and then Mesa bug rather than Proton, this should hopefully fix things.
Storage buffers are used for query resolves.
> vkd3d: Add missing descriptor type to local descriptor pools.

- tests/d3d12_shaders.c
Spuriously started failing on NV.
> tests: Add missing UAV barrier in test_tgsm.

- libs/vkd3d/device.c
> vkd3d: Add another host memory import workaround.

- libs/vkd3d/swapchain.c
If application lowers the count, we might access resources out of bounds later.
> vkd3d: Reset current_buffer_index when changing swapchain size.

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
- .github/workflows/test-build-windows.yml
Fixes Node.js 12 deprecation warning.
> ci: Use github-checkout-action v3

- libs/vkd3d/cache.c
- libs/vkd3d/state.c
It's just a wrapper, but we should be consistent.
> vkd3d: Cleanup some mismatching uses of vkd3d_malloc.

- libs/vkd3d/device.c
Works around disasterous CPU performance during skeleton animations according to several users, especially on NVIDIA.
The game does not seem to benefit from ReBAR on UPLOAD heaps either way.
> vkd3d: Add NO_UPLOAD_HVV workaround on Elden Ring.

- libs/vkd3d/device.c
This reverts commit 53f00dfecc0332495ec899835c1581328a25af85.
The assertion that it did not affect GPU perf was wrong after all.
> Revert "vkd3d: Add NO_UPLOAD_HVV workaround on Elden Ring."

- libs/vkd3d/descriptor_debug.c
> debug: Mark initial descriptor heap as containing NULL descriptors.

- .github/workflows/test-build-linux.yml
- .github/workflows/test-build-windows.yml
- package-release.sh
This resolves the following meson warning:
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
> build: Declare setup command explicitely

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Rather than storing VkBuffer / offset / size, we now store:
- VA
- Range (32-bit)
- Format
This accomplishes several things:
- Prepares for a world where VkBufferView is not created in the heap itself (i.e. no offset buffer).
- The metadata struct can now be shrunk to a neat 16 bytes instead of 32 before the refactor began.
- Allow UAV clears to operate without a dependency on offset buffers.
Hoisted CBV table descriptors (barely used, if ever) need to deref the VA late, but it's okay.
Hopefully we get the option to push descriptors with VA later, but it's not critically important now.
ClearUAV paths need to be rewritten to account for this.
Rather than reusing VkBufferViews and reading the offset buffer,
we can just create the buffer view on-demand instead.
A VA deref is fortunately not …
> vkd3d: Rewrite how buffers are stored in desc heap metadata

- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Fixes validation warning.
Signed-off-by: Tatsuyuki Ishi <ishitatsuyuki@gmail.com>
> vkd3d: Remove IdentifierCreateInfo in late compile.

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/device.c
Fix #1282.
As identified in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19910, the shader relies on an extremely weird arithmetic expression to not refactor.
```
r1.z = r1.x * 3.3219280242919921875;
r1.z = exp2(r1.z);
r0.w /= r1.z;
r0.w = floor(r0.w);
```
If this is written as:
```
r1.z = r1.x * 3.3219280242919921875;
r1.z = exp2(r1.z);
precise float tmp = r0.w / r1.z;
r0.w = tmp;
r0.w = floor(r0.w);
```
It works.
Adds a quirk config to force NO_CONTRACT on all math.
> Workaround questionable damage shader in Borderlands 3

- libs/vkd3d/breadcrumbs.c
- libs/vkd3d/command.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/descriptor_debug.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
For descriptor buffers to work optimally, we need to consider:
- Applying the ReBAR budget is problematic. We really want descriptors in ReBAR regardless of what app did with UPLOAD heaps.
- Remove the global mask. Allows some allocations to use BAR and some to skip.
- Add ~5GB limit. Avoids OOMing 4 GB cards in some cases where they work with no_upload_hvv.
- Refactor memory properties for UPLOAD / descriptor heaps to be resolved up front.
- Rename vkd3d_allocate_buffer_memory is only used for internal private allocations, so clarify that in code.
- For smol BAR, do not use BAR for UPLOAD heap, but allow it for internal descriptor allocations.
Fix #1273.
> Refactor how we allocate ReBAR memory.

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Trivially support WaveSize on GPUs with min == maxSubgroupSize.

- libs/vkd3d/device.c
Causing instant DEVICE_LOSTs on PRIME setups by just having the extension enabled.
Fix #1315.
Fix #1317.
> vkd3d: Disable KHR_present_wait on NV 525.x drivers.

- libs/vkd3d-common/meson.build
This is needed to build in Mesa CI, which uses Debian testing and mold.
Signed-off-by: Martin Roukala (né Peres) <martin.roukala@mupuf.org>
> meson/vkd3d-common: add lib_dl / threads_dep to the list of dependencies

- include/private/vkd3d_atomic.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_sync.c
- tests/d3d12_tests.h
Idea is fairly simple, we pass an atomic integer around that acts as a (reference) counter and has a signal bit that's mostly needed for `WAIT_ANY`.
Fixes #1330.
> Implement SetEventOnMultipleFenceCompletion

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Reimplements SetDescriptorHeaps.
Rather than binding N descriptor sets, binds descriptor buffers, and sets up N offsets.
The N offsets are always bound in one go. We don't have to consider NULL descriptor set or any holes here since we always bind a descriptor buffer (fallback to global), so we don't need the bit iteration we have to do for plain descriptor sets.
Also adds a descriptor buffer path for setting up descriptor set layouts. The only real difference here is that we just use VARIABLE_COUNT instead of UPDATE_AFTER_BIND, drop the host layout entirely and reuse the VALVE_host_mapping path to set up mapping offsets and strides.
Also, set up null descriptor templates, which is just queried once per descriptor types which we can then rapidly memcpy in as needed.
> Implement VK_EXT_descriptor_buffer - Phase 3

- libs/vkd3d/resource.c
Witcher 3 uses a maxAnisotropy value of 0.0 which is illegal and crashes the Nvidia Vulkan driver.
Docs:
> Clamping value used if D3D12_FILTER_ANISOTROPIC or D3D12_FILTER_COMPARISON_ANISOTROPIC is specified in Filter. Valid values are between 1 and 16.
Alternatively we could also disable anisotropy when a game passes a value of 0.0.
> vkd3d: Clamp maxAnisotropy.

- libs/vkd3d-shader/dxil.c
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
Most of this just fixes validation errors that seem to be benign in practice.
586d228 fixes Hairworks.
> Various fixes for Witcher 3

- libs/vkd3d/raytracing_pipeline.c
Fixes out of bounds descriptor heap accesses in Witcher 3 with ray tracing enabled.
Unfortunately, it still hangs. :(
> vkd3d: Set descriptor_size for each entry point.

- libs/vkd3d/command.c
> vkd3d: Fix silly regression in Witcher 3 copy fix.

- libs/vkd3d/resource.c
We can't make the assumption that the heap will be aligned to the image alignment in case the image alignment needs to be larger than the default alignment.
Signed-off-by: Bas Nieuwenhuizen <bas@basnieuwenhuizen.nl>
> vkd3d: Take into account heap offset for image offset alignment.

- libs/vkd3d-shader/dxil.c
No idea why this ended up without checking it, since the DXBC path did actually check this after all.
Fix #1355.
> vkd3d-shader: Do not match root constant without checking visibility.

- include/vkd3d_d3d12.idl
- libs/vkd3d/device.c
A Win32 app on Win32 bundling Agility SDK 1.608 would see feature checks for up to OPTIONS16 never fail, but currently when running that app under Proton checks for anything beyond OPTIONS11 would return a failure HRESULT - something that never happens on Win32. This patch prevents seemingly unreachable code paths from triggering under Proton.
> Added Agility SDK 1.608 level feature checks.

- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/command.c
One leak on error path and one memcpy against NULL issue (technically UB), found with ASan while running tests.
> ASan fixes

- libs/vkd3d/resource.c
We somehow already deal with this heap type in all other relevant spots, just not during query heap creation. Fixes #1381.
> vkd3d: Handle copy queue time stamp queries properly.

- libs/d3d12/main.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
VkInstance creation is expensive and even for singleton device, we end up creating an instance for no good reason.
Move to a global singleton that is released if application releases last ID3D12Device reference.
> d3d12: Allocate VkInstance as a global singleton.

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
Apparently, we are required to do this (but not for reserved resources). Docs seem to have been updated at some point to require this.
> vkd3d: Hold reference to ID3D12Heap in placed resource.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Saves a ton of memory on first run of an application.
Two pieces are required to make this work:
- Assume that dynamic VBO stride problems are not real in practice. They don't work quite like how you expect on native AMD drivers either.
- Handle dynamic patch control points. We can fallback and retain SPIR-V if we are at risk of fallback compile.
> vkd3d: Get rid of held SPIR-V code in 99.9% in cases.

- libs/vkd3d/cache.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
Similar logic as for pipeline library.
> Add vkd3d_config path for ignoring CachedPSO failures as well.

- libs/vkd3d-shader/dxil.c
Otherwise it's pretty difficult to find problems with the DXIL parsing.
> vkd3d-shader: Setup dxil-spirv logging when parsing library.

- libs/vkd3d/device.c
The final release did not need it after all.
> vkd3d: Remove pipeline library ignore workaround for Dead Space.

- libs/vkd3d/state.c
Built-ins (like depth, sample mask etc) all have a register index of -1, which would cause us to fail pipeline compilation.
Fixes a crash when opening the map in Dead Space.
> vkd3d: Properly ignore built-ins when validating blend state.

- libs/vkd3d/state.c
So apparently I fucked up testing the previous one and it wasn't using my actual build. Sorry about that.
This one works. Built-in outputs do not have a sysval semantic anyway.
> vkd3d: Actually fix blend state validation v2

- ISSUE_TEMPLATE/bug_report.md
A simple issue template based on the one used for dxvk. Can be expanded as needed
> meta: Create a simple issue template

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/meta.c
- libs/vkd3d/resource.c
- libs/vkd3d/shaders/cs_clear_uav_image_3d_float.comp
- libs/vkd3d/shaders/cs_clear_uav_image_3d_uint.comp
- libs/vkd3d/vkd3d_private.h
Fix some other issues while at it.
- Found 3D bug in UAV fallback copy path. Use imageOffset.z instead of baseLayer.
- Use 4x4x4 workgroup when UAV clearing 3D images.
- Consider WSize/WOffset when clearing UAV.
test_uav_3d_sliced_view now Passes RADV.
> Add support for VK_EXT_image_sliced_view_of_3d

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Catches things like UNKNOWN DSV with depth test as well as undefined primitive topology.
Tests pass on Nvidia and SotTR works.
> Use graphics pipeline libraries for fallback pipelines

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
- Do similar DXR promotion as all other recent RE Engine titles.
- Force-disable weird custom shuffle code in CACAO shaders to work on wave64.
Fix #1460.
> Add some small workarounds for RE4 Chainsaw demo

- include/private/copy_utils.h
- include/private/vkd3d_common.h
- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/command.c
- libs/vkd3d/command_list_profiled.h
- libs/vkd3d/device.c
- libs/vkd3d/device_profiled.h
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This introduces the idea of "embedded" mutable descriptors.
In this descriptor model, we can embed all information we need for
a given descriptor within the descriptor buffer payload itself.
This requires that the descriptor buffer implementation of the driver
supports some key properties:
- Size >= 32 (we need to reserve 5 LSBs to signal log2 offset to planar
metadata in case that exists)
- Texel buffer and SSBO can be placed side by side in the mutable
payload (these are usually 16 bytes each)
- Descriptor buffers can be bound at SSBO descriptor size alignment.
We are clever here and bind the same descriptor buffer at an offset
to achieve the packed texel buffer + SSBO descriptor.
- RTAS SRVs is implemented by viewing the descriptor buffer as an SSBO
directly and shader applies a stride …
> Embedded mutable descriptors

- libs/vkd3d/resource.c
If it's build-time enabled, but not runtime enabled, it was possible to crash.
> vkd3d: Fix descriptor QA potential crash.

- include/vkd3d_device_vkd3d_ext.idl
- include/vkd3d_vk_includes.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
This allows DXVK to use an existing Vulkan device and instance from vkd3d-proton and implement the basic [ID3D11On12Device](https://learn.microsoft.com/en-us/windows/win32/api/d3d11on12/nn-d3d11on12-id3d11on12device) interop interface.
There's also `ID3D11On12Device2` which allows importing resources from the D3D11 side into D3D12, and while DXVK currently does not implement this (in part because MinGW headers do not support that interface at this time), an easy way to do so would be to create all eligible resourcs as D3D12 resources on our end and just import them into D3D11 in the same way we do with `CreateWrappedResource`, so we would not need to extend the interface further.
The tricky part is command submission, as this requires a bunch of synchronization on both sides. D3D11On12 …
> Add interop interface for D3D11On12

- include/meson.build
- include/private/vkd3d_debug.h
- include/private/vkd3d_string.h
- include/private/vkd3d_threads.h
- include/vkd3d.h
- include/vkd3d_core_interface.idl
- include/vkd3d_d3d12.idl
- include/vkd3d_sonames.h
- include/vkd3d_unknown.idl
- include/vkd3d_win32.h
- include/vkd3d_windows.h
- libs/d3d12/main.c
- libs/d3d12/meson.build
- libs/d3d12core/d3d12core.def
- libs/d3d12core/main.c
- libs/d3d12core/meson.build
- libs/meson.build
- libs/vkd3d-common/debug.c
- setup_vkd3d_proton.sh
- tests/d3d12_device.c
- tests/d3d12_tests.h
Move the main bulk of the code to d3d12core, and expose an interface to access.
This allows us to pass the new test that prove that the vtable is resident in d3d12core going forward.
Essentially turns d3d12 into a slim wrapper.
> d3d12, d3d12core: Refactor to move main code to D3D12Core 

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Fix #1461.
Saves size of captures by almost 50% and reduces memory requirements significantly during capture.
> Global buffer tweaks

- libs/d3d12/main.c
Fallback from CI being broken at the moment.
> d3d12: Fix MSVC build.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_sync.c
- tests/d3d12_tests.h
`VKD3D_TEST_FILTER=test_concurrent_signal_stress VKD3D_CONFIG=skip_driver_workarounds ./tests/d3d12`
```
test_concurrent_signal_stress:1662:Test 2: Test failed: Failed to wait for event. GPU likely hung.
On driver 530.30.02 with RTX 3070 I get:
[21600.846408] NVRM: Xid (PCI:0000:08:00): 32, pid=225396, name=d3d12, Channel ID 00000036 intr0 00040000
[21600.846870] NVRM: Xid (PCI:0000:08:00): 32, pid=225396, name=d3d12, Channel ID 00000036 intr0 00040000
```
The test completes fine with workaround. Similar issue can be observed in test_fence_wait_multiple.
> Workaround spurious GPU hangs on NV with concurrent submissions to different queues

- libs/vkd3d/device.c
Another FORCE_INITIAL_TRANSITION workaround, for issue #1492.
> vkd3d: Workaround menu freeze in Deus Ex: Mankind Divided

- libs/vkd3d/command.c
- libs/vkd3d/device.c
Need to disable caching so we get full debug information when emitting labels.
> vkd3d: Ensure debug labels are properly emitted with profiling.

- include/vkd3d_d3d12.idl
- include/vkd3d_windows.h
This brings the native headers in line with the official DirectX headers and dxvk
> Remove use of ms_abi for native builds

- libs/d3d12core/main.c
Minecraft Legends depends on this behavior. I've checked and this is how native D3D12 behaves.
> d3d12core: Set the interface pointer returned by GetDebugInterface to NULL.

- libs/vkd3d/device.c
Add shader hash used in RE2 and RE7 to list of workaround hashes. Remove RE4 demo as it has a new shader with a fix.
> vkd3d: Add RE2 and RE7 to CACAO workaround and remove RE4 demo

- tests/test-runner.sh
the test suite here is a bit minimal and runs itself synchronously, which is problematic for cases where:
* a test runs itself for any amount of time
* a test crashes
in the former case, all 511 other threads of the user's powerful supercomputer are sitting idle instead of being put to work
in the latter case, the entire test process stops and no further test results can be gathered without either starting a new run that filters out the crashing test(s) or fixing the crash
this test runner solves both issues by running one test case per cpu and then tracking the failures such that all cores are always in use and any crashes don't affect the rest of the tests
obviously I gotta talk about perf, so here's some rough data:
|Num CPU threads|Driver|Normal runtime (seconds)|Runner runtime …
> tests: add a multi-threaded test runner

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12_depth_stencil.c
- tests/d3d12_tests.h
We are apparently required to handle this. Fixes #1547.
> Handle dynamic depth-stencil write masks based on DSV descriptor

- libs/vkd3d/device.c
- tests/d3d12_device.c
Turns out that the runtime will return `E_INVALIDARG` when the app passes in an unrecognized or unsupported root signature version, which makes this whole function a bit... weird.
Fixes #1548.
> Fix root signature feature check

- libs/vkd3d/swapchain.c
This should be a multiply instead of a divide. Values are 1/10000th of a nit (0.0001 nit).
> vkd3d: Fix min luminance of HDR Metadata

- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
In a memory constrained environment this is a good idea, and Deck should have everything primed in disk$ either way, so the value of memory cache is greatly diminished.
> vkd3d: Apply curb memory pso cache globally on Deck.

- libs/vkd3d/device.c
- libs/vkd3d/heap.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
The goal is to:
- Enable pageable memory, a.k.a. heap migration (VK_EXT_pageable_device_local_memory)
- Implement explicit D3D12 API residency+prioritization hints on top of VK_EXT_memory_priority
- Closely match the implicit D3D12 prioritization given to resources by default based on usage etc, insofar as publicly documented
**Notes**:
Practically speaking, it's not a panacea for when you're chronically oversubscribed (it may be a better experience... or it may not); the main win is that it recovers a lot more gracefully from transitory oversubscription.
Without VK_EXT_pageable_device_local_memory you can end up with rendertargets (or anything else vital) spilled to a system heap and stay there forever.  That can drive an app off an invisible performance cliff from which it's hard to …
> Improve behavior when VRAM is oversubscribed.

- tests/d3d12_query.c
VRS can affect it because it's all flat shaded.
> tests: do not require the exact number of pixel shader invocations

- libs/vkd3d/device.c
It should be fixed now, for realsies.
> vkd3d: Re-enable KHR_present_wait on NV 535.xx+.

- libs/vkd3d/device.c
See https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20573 for reference.
> vkd3d: add MESA_VK_TRACE=rgp as a trigger for RADV RGP captures

- libs/vkd3d/vkd3d_private.h
Fixes unaligned memory access issue in packed metadata. No functional issue on x86, but still very dumb to rely on.
> vkd3d: Mask embedded metadata VA.

- libs/vkd3d/command.c
There's a risk that if descriptors are copied in the thread that records commands (common case), if submission happens in a completely different thread, it's plausible that memory order does not hold.
This does not fix any known bug, so it's a hallucinated fix, but might as well be defensive about it for more peace of mind.
> vkd3d: Issue sfence on command list close as well.

- tests/d3d12_enhanced_barriers.c
- tests/d3d12_tests.h
- tests/meson.build
Adds tests.
- RGBA8 / R32 casting.
- Use new style of DSV casting. Verify rendered result.
- Extensive checks for resource creation validation. Found lots of weird and wonderful behavior ...
- Verify weird things you can do with resource casting on buffers (cast to DXGI_FORMAT_UNKNOWN :frog:).
- To validate resource casting more exhaustively, I ran it through Vulkan validation to make sure there were no validation errors regarding missing formats in the VkImageFormatList.
"Features" that were left out from testing:
- Apparently you can cast between unrelated BC formats. Validation does not complain. This is not technically allowed in Vulkan since BC formats live in their own format class, but it's one of those things that will "just work" I'd imagine if any application is crazy enough to …
> Implement Enhanced Barrier format casting - Phase 2

- .github/workflows/test-build-windows.yml
vulkan-sdk is over 2 years old, and breaks now. We only need glslangValidator.exe, so just download a .exe we have handy. KISS.
> ci: Workaround choco breaking vulkan-sdk package.

- libs/vkd3d/device.c
Related to this dxvk PR: https://github.com/doitsujin/dxvk/pull/3550 which has all the background and should ideally be synced in some way.
In short, D3D11_RESOURCE_MISC_SHARED_NTHANDLE flag alone is illegal on Windows, it is a modifier to D3D11_RESOURCE_MISC_SHARED or D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX.
> vkd3d: Set correct MiscFlags in d3d12_device_CreateSharedHandle().

- meson.build
Fixes the CI failing with the name change.
https://github.com/KhronosGroup/glslang/releases/tag/12.3.0
Even though that is a bug, since a symlink is supposed to be created, it seems fine to change the name anyway and have a fallback.
Edit: Symlink now fixed on Arch with glslang 12.3.1-2
> build: Use new glslang name with fallback

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_command.c
- tests/d3d12_tests.h
Gets rid of the "active" mask. It's vestigial and useless and only serves to push garbage data from stack to GPU.
Should fix spurious GPU hangs in SF6, which hits this scenario.
> Workaround games which forget to set SetRootDescriptorTable

- include/vkd3d_command_list_vkd3d_ext.idl
- libs/vkd3d/command.c
- libs/vkd3d/command_list_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
Specify `ID3D12GraphicsCommandListExt1` which contains a new function for creating CuBINs with smem usage. This function mirrors the api of the NvAPI function `NvAPI_D3D12_CreateCubinComputeShaderEx`.
This functionality is needed for CuBINs that use smem.
> Specify + Implement ID3D12GraphicsCommandListExt1 with CuBIN smem Support

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/vkd3d_private.h
Significantly improves Raytracing performance on RADV in a number of games, especially Hitman 3.
Handling WriteBufferImmediate is a bit janky as always, since we want to maintain correct command ordering with `BOTTOM` markers.
> Batch raytracing acceleration structure builds

- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
Finally resolves the bizarre rendering glitches in MHR in certain scenes.
Game bug, and practically relies on full NoContract math to work as expected.
> Add NOCONTRACT quirk path to DXIL as well.

- libs/vkd3d/command.c
Useful for RGP which will unroll the individual events inside the dispatch.
> vkd3d: Add marker region for NV_dgc.

- libs/vkd3d/resource.c
> vkd3d: Workaround NV driver bug with TIMESTAMP query heap.

- libs/vkd3d/bundle.c
- libs/vkd3d/state.c
Some trivial boilerplate code for now, we should probably make it a habit to do this right away when bumping interface versions since this is otherwise easily forgotten about.
Barrier() remains unsupported on bundles.
> Implement missing functions for bundles

- include/private/vkd3d_debug.h
WARN is a bit too spammy for this.
> debug: Make FIXME_ONCE fallback to TRACE after first message.

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/breadcrumbs.c
- libs/vkd3d/command.c
- libs/vkd3d/command_list_vkd3d_ext.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/meta_commands.c
- libs/vkd3d/shaders/cs_predicate_command_execute_indirect.comp
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12_command.c
- tests/d3d12_tests.h
**NOTE: The meaning of this PR, potential perf impact and the problem it tries to solve is being grossly misrepresented on other sites.**
The goal of this refactor is to optimize for cases where games (Starfield in particular) uses advanced ExecuteIndirect in very inefficient ways.
- Indirect count, but indirect count ends up being 0.
- Non-indirect count, but none of the active draws inside the multi-draw indirect actually result in a draw. Multiple back-to-back ExecuteIndirects are called like this, causing big bubbles on the GPU.
In RADV, a special optimization was added which uses indirectCount in DGC as a predicate when possible. This lets us skip over the prepare cmdbuffer as well as the INDIRECT_BUFFER execution which is about 10x faster than spawning a small CS, adding extra sync …
> Add special game perf workaround for Starfield and other DGC junkies

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- Works around NV_dgcc having extremely large preprocess buffers on NV. We were spamming allocations.
- Adds warnings in this area so we can spot issues here later.
- Scratch buffer count was way too low. Avoids allocation churn on RADV.
The extremely large block sizes is likely a driver bug though, but we do indeed observe 27 MB preprocess buffer requirements in Starfield on NV vs 180 KiB on RADV.
> Scratch pool refactor

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
Pioneers of Pagonia requires RGB32 texture support, which isn't supported with `OPTIMAL` tiling on AMD/NV.
This also reworks the way we deal with format features a bit to get rid of some unnecessary GetFormatProperties calls, and just to make reporting of format support more consistent with what can actually work.
This alone is not enough to fix the game since there is an unrelated crash somewhere, but it lets us actually test the thing without immediately running into some error pop-up.
> Implement linear tiling fallback for weird image formats

- libs/vkd3d/utils.c
Nvidia exposes *only* HOST_TRANSFER_BIT for R32G32B32_FLOAT with optimal tiling, which means we accidentally assume optimal tiling support.
> vkd3d: Only consider basic format features for linear tiling fallback.

- libs/vkd3d/device.c
> vkd3d: Remove CURB_MEMORY_PSO_CACHE workaround on RADV 23.2.

- README.md
WineHQ has started using GitLab. Update the upstream git URL in README.md to use the link to their GitLab project.
> Update upstream git URL to WineHQ GitLab

- libs/vkd3d/device.c
Fixes random black screen flicker due to buggy transitions.
> vkd3d: Disable UAV compression in Plague Tale.

- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/cs_sampler_feedback_decode_buffer_min_mip.comp
- libs/vkd3d/shaders/cs_sampler_feedback_encode_buffer_min_mip.comp
- libs/vkd3d/shaders/cs_sampler_feedback_encode_image_min_mip.comp
- libs/vkd3d/shaders/cs_sampler_feedback_encode_image_mip_used.comp
- libs/vkd3d/shaders/fs_sampler_feedback_decode_image_min_mip.frag
- libs/vkd3d/shaders/fs_sampler_feedback_decode_image_mip_used.frag
- libs/vkd3d/shaders/sampler_feedback_decode.h
- libs/vkd3d/shaders/sampler_feedback_encode.h
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
Contains the meta implementation for resolve.
There are 6 shader variants here:
Buffer decode/encode is only supported for MIN_MIP under restricted circumstances. No arrays, etc.
For decode, I went with fragment shaders, since we already add COLOR_ATTACHMENT for R8_UINT for stencil -> color copies anyways. ResolveSubresourceRange also only works in DIRECT queue, so there's no worry about having to support compute paths.
For encode, it's all compute, since there was no need to avoid it.
> Sampler feedback implementation - Phase 8

- libs/vkd3d/device.c
Workaround for glitches and hangs in Starfield introduced with DGCC-enabled 545-drivers.
> vkd3d: Disable NV_dgcc on 545 drivers.

- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
Works around some horrible codegen in Jurassic World Evolution 2 that ends up generating statically invalid code.
Also gets rid of some horrible unrolls in Starfield.
> Pass down subgroupSizeMin/Max to dxil-spirv

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_raytracing.c
- tests/d3d12_tests.h
Forgot about this cursed RTPSO flag. Warhammer: Darktide uses this.
Works now on RADV (but Xid 109 on NV, but probably not our bug).
> Implement DXR local -> external dependencies

- libs/vkd3d/command.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/fs_copy_image_stencil_no_export.frag
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12_copy.c
Unblocks R8->stencil copies on NV. We'll need the same trickery for stencil resolves anyway, so might as well support this as well.
> Implement stencil copies without stencil export

- libs/vkd3d/device.c
The shader hash changed in Update 2.1. The bug remains, so add it to the quirk table.
> vkd3d: Extend CP2077 workaround to shaders from 2.1

- tests/d3d12_mesh_shader.c
Mesh shaders are supported now, only task shaders remain.
> tests: stop skipping Mesh DGC tests with RADV

- libs/vkd3d/breadcrumbs.c
- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Arma: Reforger hits this scenario where it resolves to RG8_UNORM with MAX, but only declares UAV use.
Consider it better to resolve something (indistinguishable most likely) rather than nothing (corrupt textures).
Also make breadcrumb cookies slightly easier to grep for which was needed to track this down.
> Attempt AVERAGE fallback when MIN/MAX resolve is not available.

- libs/vkd3d/command.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/shaders/cs_resolve_color_float.comp
- libs/vkd3d/shaders/cs_resolve_color_sint.comp
- libs/vkd3d/shaders/cs_resolve_color_uint.comp
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
- tests/d3d12_copy.c
Extends the extsiting resolve implementation by *yet another* code path, so that we no longer require render target usage for the destination image.
~~Draft becasue always enabling `STORAGE_IMAGE_BIT` for non-render target images seems a bit scary, this should probably be tested somewhat extensively on Nvidia.~~
> Add compute shader fallback for multisample resolves

- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- tests/d3d12_shaders.c
Addresses the following issues:
- `precise` flags can be set on this instruction, but this would lead to the uint path not working properly.
- if the queried mip level is out of bounds, the returned width, height and array size is specified to be 0. AMD Windows drivers do not seem to implement this, but Nvidia passes the relevant test.
- `_rcpfloat` was not supported. FXC never seems to emit this, but I've seen this in the wild with DXVK, probably from custom DXBC emitters.
The first issue was encountered in Avatar Frontiers of Pandora.
> Fix various problems with the resinfo instruction

- libs/vkd3d/device.c
Seems to fix a GPU hang on RADV.
> vkd3d: Enable descriptor heap robustness for Pioneers of Pagonia.

- include/vkd3d_d3d12.idl
- libs/d3d12core/debug.c
- libs/d3d12core/debug.h
- libs/d3d12core/main.c
- libs/d3d12core/meson.build
Fixes Atlas Fallen crashing on launch. Nothing too sophisticated.
> Add ID3D12DeviceRemovedExtendedDataSettings stub

- include/meson.build
- include/vkd3d_dxcapi.idl
- include/vkd3d_windows.h
- programs/meson.build
- programs/vkd3d-hlsl-build/dxbc_library.cpp
- programs/vkd3d-hlsl-build/dxbc_library.h
- programs/vkd3d-hlsl-build/dxil_library.cpp
- programs/vkd3d-hlsl-build/dxil_library.h
- programs/vkd3d-hlsl-build/main.cpp
- programs/vkd3d-hlsl-build/meson.build
As discussed on Discord, this could be used to make writing tests less painful by allowing us to simply run the exe within a directory that contains HLSL shaders and spits out plain C headers. Draft for now to gauge whether this is going in the right direction.
Currently, this works as follows:
- For DXIL, `dxcompiler.dll` must be in the search path (either next to the exe or in the wine prefix). As for headers, I added a new IDL with the necessary interfaces, but it does not cover the entire DXC API.
- For DXBC, we require `d3dcompiler_47.dll` as the latest version. I haven't added a custom IDL for the d3dcompiler APIs since MinGW ships the necessary headers anyway, but I can add a minimal IDL here as well if we want to go that route.
- Input directory defaults to CWD, can be changed via …
> RFC: Add application to compile batches of HLSL shaders

- libs/d3d12/main.c
- libs/d3d12core/main.c
- meson.build
This mirrors changes at DXVK [1], [2].
The intent in [1] was to prevent 32-bit export function names from containing @Ordinals at the end.
This also turns out to be useful for compatibility with LLVM-based toolchain, in particular when using LLD, because LLD does not recognize --add-stdcall-alias but does recognize --kill-at.
As in [1], we use the system-provided d3d12 dependency instead of the
implib we generated, because MinGW LD insists on emitting implib with
ordinal suffixes (LLD does the correct thing here).
Another part of the change is to remove __declspec(dllexport). The .def
files we use specify the linkage already, so the attributes are obsolete.
This fixes LLD warnings like:
ld.lld: warning: duplicate /export option: D3D12CreateDevice
There is another LLD compatibility issue …
> build: Replace stdcall-alias with kill-at, remove __declspec(dllexport)

- libs/d3d12core/main.c
- libs/vkd3d/device.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
VkFence wait on Mesa is not a noop after all.
There can be very long stalls leading to very strange frame pacing graphs when GPU is rendering slower than refresh rate in windowed modes.
Waiting for semaphores fixes this and with present_wait, there is little reason to not use semaphores when there's a meaningful improvement in jitter.
> vkd3d: Implement EXT_swapchain_maintenance1 and replace fence wait with semaphore

- libs/vkd3d-shader/dxbc.c
- libs/vkd3d-shader/vkd3d_shader_private.h
The limit is 4096 four-component vectors, but the size is given in dwords. Rename the constant to make this more clear.
> vkd3d-shader: Fix maximum ICB size.

- tests/d3d12_crosstest.h
- tests/d3d12_test_utils.c
That explains some weird results ... :frog:
> tests: Actually use WARP when we enable it.

- meson.build
d3d12.exe will conflict with d3d12.lib when exporting AgilitySDK.
> build: Don't export IMPLIB/EXP.

- libs/vkd3d/swapchain.c
Checking for pNext is not longer valid with swapchain_maint1.
Missed case during development since I didn't test with non-FIFO apparently.
> vkd3d: Only mark present ID as valid when it is valid.

- include/private/vkd3d_debug.h
- include/shader-debug/debug_channel.h
- libs/vkd3d-common/debug.c
- libs/vkd3d/breadcrumbs.c
- libs/vkd3d/debug_ring.c
Pull in some simple commits from https://github.com/HansKristian-Work/vkd3d-proton/pull/1544.
> Misc debug ring improvements

- libs/vkd3d/resource.c
If application uses castable formats, we might have to do this.
Fixes GPU hang on NV in Lyra UE5 demo.
Fix #1858.
> vkd3d: Add BLOCK_VIEW_COMPATIBLE in disable_compression path.

- libs/vkd3d/command.c
Forgot to do this similar to compute.
> vkd3d: Clear active_flags to 0 when binding RT pipeline as well.

- libs/vkd3d/device.c
Does not run acceptably outside the very beginning of the game. The feature is enabled by default, and should not be considered verified in that state.
> vkd3d: Disable RT by default on Deck for Persona 3 Reload.

- include/private/vkd3d_string.h
- libs/vkd3d-common/debug.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/heap.c
- libs/vkd3d/memory.c
- libs/vkd3d/meson.build
- libs/vkd3d/queue_timeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
A coarse system-level profile method.
The goal here is to be able to see at a glance D3D12 submissions along with presents and when they complete (with present wait). It dumps out a trivial JSON format that Chromium can consume in chrome://tracing.
There are some useful features that can help track down things:
- Command list reset/close is marked as an instantaneous event
- Various heavy creation calls are marked as well (to see if it causes stutter, etc)
- DXGISwapchain::Present time blocking is marked
- vkQueuePresentKHR time is marked
- Present wait blocking is marked
- CPU submission time
- GPU active time for a submission (ends when submission fence is signalled) not as accurate as gpuviz or something like that.
- Present blit on GPU timeline is displayed
- HANDLE signal from fence …
> Add a system for tracing GPU timeline work

- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_device.c
Found a game engine that was doing it's initial checking of formats fail because E_INVALIDARG was returned for DXGI_FORMAT_R1_UNORM. This format is unspecified in the required and optional format list in msdn but D3D12 returns E_FAIL instead of E_INVALIDARG.
This diff returns E_INVALIDARG if the format is not a valid DXGI_FORMAT but E_FAIL if vkd3d does not support it.
Updating test_format_support to check all formats for valid HR results.
> vkd3d: proper return values for formats that are valid but not supported.

- include/vkd3d_dxgiformat.idl
- libs/vkd3d/utils.c
- tests/d3d12_device.c
A game engine is relying on these returning S_OK or E_FAIL and not E_INVALIDARG.
This builds on #1906.
> Adding support for ASTC extension formats

- libs/vkd3d/device.c
Seems to work with recent Vulkan dev driver (550.40.53) on my setup without issues (tested using Granite's `tests/latency-test` and resizing/fullscreening its window, KDE Plasma 6.0, Wayland, PRIME setup with Intel iGPU).
With this, the only 550 driver on which it will stay disabled should be initial R550 beta release (550.40.07).
> vkd3d: Also enable VK_EXT_swapchain_maintenance1 on Nvidia R550 Vulkan beta/dev drivers.

- libs/vkd3d/swapchain.c
This should workaround the problems discovered in https://github.com/HansKristian-Work/vkd3d-proton/issues/1929. The root cause of the issue is most likely a driver synchronization bug that we will have to fix on our end.
> vkd3d: Don't update low latency state if it isn't going to change

- include/private/vkd3d_common.h
While __x86_64__ is defined when targeting ARM64EC, x86 intrinsics aren't available so fallback to vkd3d_get_current_time_ns.
> vkd3d: Don't attempt to use rdtsc on ARM64EC

- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- Missed case where a swapchain is recreated. If a new swapchain becomes the low latency chain, inherit the device-global mode.
- Add some extra debug logging when latency debug is enabled.
- Fix some odd scenarios with internal frame latency handle + low latency. If GPU queue is deemed to be too deep, and low latency is enabled, don't try to sleep ourselves, as it seems to throw LL2 off, where it starts thinking it shouldn't sleep.
The heuristic here is pretty simple, but works well in practice. Query the blit timeline semaphore if number of requested submits is significantly larger than the completed counter, it means the GPU queue is deep.
There are some scenarios where we trigger latency limiter ourselves:
- We are FIFO bound. Low latency (at least not NV's implementation of it) will …
> Fix some nagging low_latency2 issues.

- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_sparse.c
Relevant for DS sparse on RADV. Convert to a committed resource and pretend all pages are mapped at all times.
Technically out of spec, but should be good enough to work around games until we have proper support.
Fixes #1924.
> vkd3d: Implement fallback when 2D sparse is not supported.

- tests/d3d12_pso.c
See #1938. We need to fix our SPIR-V when there are multiple GS streams.
> tests: Disable streamout tests for I/O mismatch for now.

- tests/d3d12_pso.c
Derp, my Windows build ran the DXBC test twice so this went unnoticed. Fixes a test crash on Windows.
We should probably validate that all shaders within a pipeline use compatible shader models as well.
> tests: Fix DXIL ATOC test on Windows.

- include/vkd3d_vk_includes.h
- libs/vkd3d/command.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
Some applications use app IDs in "random" order which completely breaks the existing implementation.
> vkd3d: Ensure monotonic frame ID order for Reflex.

- include/vkd3d_device_vkd3d_ext.idl
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Motivation for adding this is to support OpenXR extension XR_KHR_D3D12_enable.
The way OpenXR is designed, the application gets an array of swapchain images from the runtime, and renders into them. (Unlike OpenVR, with which the application will submit textures to be displayed in the VR environment). This means we need to convert the VkImages we get on the unix side to ID3D12Resources on the PE side.
* * *
I hope I am doing this correctly. I tried the `hello_xr` demo on D3D12 which works, and I didn't see any warnings from the validation layer.
> vkd3d: Introduce interface for creating d3d12 resources from VkImages

- libs/vkd3d/device.c
To handle the trend of Ubisoft games shipping separate executables for subscribers of their Ubisoft+ thingy.
Although I can't verify this myself because I'm playing via `ACMirage.exe`, this is how the binary is called exactly:
```
$ ls -1 *.exe
ACMirage.exe
ACMirage_plus.exe
```
> vkd3d: Also enable AC Mirage shader quirk for ACMirage_plus.exe.

- libs/vkd3d/swapchain.c
This prevents possibly destroying the d3d12 device while releasing the frame_latency_fence if the device ref count hits zero.
> Release swapchain command queue reference after swapchain decref

- include/vkd3d.h
- include/vkd3d_device_vkd3d_ext.idl
- libs/vkd3d/command.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
OpenXR's vulkan extension expects a queue index instead of a VkQueue handle directly, so we need to expose this information from vkd3d-proton to support that.
> vkd3d: Add an interface for getting all information about a VkQueue

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_streamout.c
Brought up by @rlocatti-nv . `KHR_maintenance6` doesn't seem overly interesting for us, but it does allow us to handle this edge case properly. Tested on both RADV and Nvidia.
> vkd3d: Support indexed draws with NULL index buffer.

- libs/vkd3d/device.c
Fixes #2001. The game hits some weird fallback path if we don't report `MULTISAMPLE_RENDERTARGET` for D32.
There generally are major differences between what we report vs what Windows drivers report in general especially regarding `TYPELESS` formats, might need to revisit this whole thing at some point, but for now this band-aid fix should do and makes the game work.
> vkd3d: Improve reporting of rendering-related format features.

- libs/vkd3d/shaders/cs_resolve_query.comp
RenderDoc ran into a crash here since the SSBO is part of OpEntryPoint in SPIR-V 1.6 and thus static use.
> vkd3d: Fix stray invalid SSBO being generated.

- libs/d3d12core/main.c
- libs/vkd3d/command.c
- libs/vkd3d/command_list_vkd3d_ext.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/meta.c
- libs/vkd3d/meta_commands.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
:broom:, but I dumped most of it into a single commit so let me know if you want this stuff to be split differently.
* Adds missing newlines
* Adds some dots where appropriate
* Removes some stray spaces, in particular at the end of message just before newline and when there was more than one space in the middle of format string
* Changes some specifiers to better match argument types
* Fixes some conversion specifiers missing their arguments or arguments missing their conversion specifiers
* Adds extra arguments to log messages in two places where it would make sense to log them
Two places I'm not sure about are
* `ERR("DSV: %p\n", graphics->dsv_format);` where I don't know if there's any value in logging the pointer value and maybe we should log `graphics->dsv_format->dxgi_format` or …
> Fix multiple issues and inconsistencies in log message formats

- libs/vkd3d/device.c
Continuing https://github.com/HansKristian-Work/vkd3d-proton/pull/2017#discussion_r1642580774:
We indeed can't detect if the build was from a dirty tree based on `vkd3d_build` alone so check `vkd3d_version` for that instead. With this, we will always print 15 digits but with a `+` appended on dirty trees.
```
info:vkd3d_instance_init: vkd3d-proton - build: e20011164ce2450.
```
or
```
info:vkd3d_instance_init: vkd3d-proton - build: e20011164ce2450+.
```
> vkd3d: Print build commit using a fixed width format.

- include/private/vkd3d_common.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/bundle.c
- libs/vkd3d/cache.c
Probably not too helpful right now, but probably good to do going forward.
Added it to the flexi-array members I found that had a member associated with their size, and checked the size was set before their use.
> Add vkd3d_counted_by

- include/vkd3d_swapchain_factory.idl
- libs/vkd3d/swapchain.c
Implements necessary functionality for `IDXGISwapChain::GetFrameStatistics` to return somewhat meaningful data. Without it, we pretend that a present operation completes immediately, which is bad in case the app uses this for frame pacing purposes, and worse if it makes assumptions on whether or not it is safe to free GPU resources. There are a couple of games using this (albeit for unknown purposes), most notably Nixxes ports.
TL;DR is that the API quite literally counts successful presents, and we happen to have an internal timeline doing exactly that in a robust manner already so we can just expose that to the app. Some refactoring was needed since this requires us to always have the waiter thread active, even if present wait is not used for a given present.
Additionally, this adds a …
> Implement frame statistics

- libs/vkd3d/command.c
Not super useful without state updates due to lack of DrawIndex, but it is what it is.
> vkd3d: Handle multiple direct draws for mesh shaders.

- tests/d3d12_mesh_shader.c
Happened to work since same max_commands was used.
> tests: Check correct uav_offset in amplification indirect state test.

- tests/d3d12_mesh_shader.c
RADV is passing them now.
For reference https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29935
> tests: stop skipping Task+Mesh DGC tests with RADV

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
This is a fairly invasive refactor, so I'm doing this as a separate PR.
The goal here is to unify all the different ways in which we compute the size of a subresource to make it a) more consistent and b) correct w.r.t. subsampled planes. Currently it's all over the place and largely broken.
Another change is that we now store the aspect flag that is used to create a view in the view info. This is important in cases where we need to reconstruct the exact subresource of the image that the view covers, since it can be something like `PLANE_1_BIT` even if the format's aspect mask is `COLOR_BIT`.
> Planar formats, part 2: Handle subsampled planes and plane view aspects

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/utils.c
Draft for now since this depends on #2028.
Adds support for NV12, P010 and P016 formats, which are pretty much all the planar formats available in D3D12 (`420_OPAQUE` exists, but can only be used with video APIs).
Should fix #2021.
> Planar formats, part 3: Implement planar formats

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
We should nop out the draw call, but it happens after this check.
> vkd3d: Avoid assertion if attempting to render with compute shader.

- include/vkd3d_device_vkd3d_ext.idl
- include/vkd3d_vk_includes.h
- libs/vkd3d/breadcrumbs.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_crosstest.h
- tests/d3d12_dxvk_interop_device.c
- tests/d3d12_tests.h
- tests/meson.build
Add functionality for grabbing the `VkCommandBuffer` which is internal to a `ID3D12CommandList` object. This allows for applications to do interop using DX12 synchronization primitives but enqueue work onto queues which are otherwise not exposed through traditional DX12 APIs.
This will be used as a basis for `dxvk-nvapi` to create a DX12 offering of the `VK_NV_optical_flow` functionality. Tagging @jp7677 and @Saancreed from that project as any feedback received here will be relevant to a follow-up pull request I will be making there.
Should this be called `ID3D12DXVKInteropDevice1` ? It has a high overlap in functionality with `ID3D12DXVKInteropDevice` so it seemed appropriate for it to inherit the methods. Saancreed suggested via Discord that it may make sense to rename …
> Extend `ID3D12DXVKInteropDevice` into `ID3D12DXVKInteropDevice1` to add `VkCommandBuffer` interop

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Doesn't fix all our problems with staggered submissions, but batches a bunch of submissions (command buffers just doing a single clear / copy or literally just doing barriers without any GPU work). This helps FF16 a bit as well.
Basic idea here is to assume that any draw / dispatch is expensive enough to warrant a dedicated submission, but copies, clears etc typically aren't unless there's a whole bunch of them.
> Add GPU cost heuristic for staggered submissions

- libs/vkd3d/device_vkd3d_ext.c
Oversight when `ID3D12DXVKInteropDevice1` was added which causes a crash with 11on12 interop.
> vkd3d: Check format pointer in GetVulkanResourceInfo1.

- libs/vkd3d/command.c
- libs/vkd3d/memory.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
Suppose we have two virtual queues `A` and `B` both sharing the same `vkd3d_queue`, and the application does something like this:
```
A->ExecuteCommands(...);
B->ExecuteCommands(...);
A->Signal(fence, ...);
```
then actually signaling the fence may be delayed until work submitted to `B` completes, which can delay both app threads waiting on the fence as well as command submissions to any queues that wait on said fence. To solve this, we instead queue up a CPU-side wait on the last submission performed by the signaling command queue and signal the fence manually.
This also takes the early signal idea from #2075 and queues up a CPU signal in case the virtual queue has no pending submissions.
This expands upon the per-queue submission tracker introduced in …
> Signal fences on CPU to reduce delays on muxed queues

- libs/vkd3d/command.c
Dramatically improves performance in HZD with single_queue. Might be useful for Intel devices which only expose one queue family since there is a certain expectations for compute queues to actually be asynchronous, and we shouldn't ever hit path this on any AMD/Nvidia hardware.
Sort of depends on #2082 to work well, hence the draft.
> vkd3d: Stagger submissions in single-queue scenarios.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Builds on the more pecise submission tracking and half-reverts the CPU signal thing by removing the timeline semaphore from non-shared fences and just using queue timelines instead to reduce submission spam.
I had some concerns about semaphore lifetimes initially since we can use the timeline semaphore belonging to a `vkd3d_queue` can be used on *any other* `vkd3d_queue` now, but since D3D12 command queues ref the device and vkd3d queues have the same lifetime as the device, this should be a non-issue for now.
> Signal rework

- libs/vkd3d/meta_commands.c
Works around geometry explosion in FF XVI on NV as well. This one looks and smells like a driver bug and not a game bug.
> Awkward non-sensical barrier before dstorage to workaround FF XVI vertex explosion.

- libs/vkd3d/resource.c
This is required to prevent issues with GPUs that have a buffer image granularity that is larger than the memory alignment returned from vkGetImageMemoryRequirements2. Without this alignment linear and optimal tiled resources could alias each other resulting in memory corruption.
> Align suballocated committed textures to the device buffer image granularity

- README.md
- include/private/vkd3d_test.h
- tests/test-runner.sh
TEST_FILTER is not ideal for anyone wanting to run exactly one test where that test name may a substring of another test
this is particularly noticeable with the test runner script, which is intended to only run one test per thread but will actually run many tests due to inaccurate substring matching
> tests: add VKD3D_TEST_MATCH

- libs/vkd3d/shaders/cs_emit_nv_memory_decompression_regions.comp
Untested since I currently don't have my NV card in the system.
> vkd3d: Drop subgroup code in memory decompression pre-process shader.

- libs/vkd3d/utils.c
- tests/d3d12_device.c
Git is having a bit of an aneurism with this one because I had to move one function around, but TL;DR
- ignore planar (including stencil) formats for sparse since that's banned in d3d12 anyway
- actually set up sample count properties for depth/stencil formats
Also added a test. 4xMS is required for all renderable formats in D3D12.
> Fix reporting supported sample counts depth-stencil formats

- libs/vkd3d/device.c
Game has two executables, one of which seems to be used for legacy CPUs with no AVX2 support, hence the `STARTS_WITH`.
> vkd3d: Disable staggered submissions for The Last of Us Part 1.

- tests/d3d12_resource.c
- tests/d3d12_sm_advanced.c
Use cpu handle of non-shader-visible descriptor heap for `ClearUnorderedAccessView*` 
Related tests: `test_planar_video_formats` `test_sm68_draw_parameters`
Related issue :https://github.com/HansKristian-Work/vkd3d-proton/issues/2122
> Fix cpu handle of descriptor heap used in ClearUnorderedAccessView

- libs/vkd3d/device.c
Apparently Reflex forces the game into the unsupported dcomp path?
Fixes #2099.
> vkd3d: Add NV reflex workaround for Skull and Bones.

- tests/d3d12_resource.c
Same issue as https://github.com/HansKristian-Work/vkd3d-proton/pull/2123.
Related tests: `test_large_texel_buffer_view`
> tests: Fix cpu handle of descriptor heap used in ClearUnorderedAccessView for test_large_texel_buffer_view

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
The christmas tree certainly contributed to this one going unnoticed, `format` isn't our dsv format....
Explicitly pass the DXGI format instead to avoid confusion.
> vkd3d: Fix wrong format being used for depth bias representation.

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Avoid going through vtable just to do internal addref/release. Also splits up the logging so we can distinguish between public and private ref-counts.
> vkd3d: Refactor device ref-count logic.

- libs/vkd3d/command.c
When I was playing The Witcher 3, I found that moving the mouse quickly would cause blocky corruption. After investigation, I found that it was because vkd3d did not correctly convert the d3d12 call, resulting in a missing barrier in the use of a certain image.
System info:
OS: Ubuntu 22.04
GPU: AMD RX 7800XT
DRIVER: AMDVLK or amdvlk-pro
Proton: Experimental, 9.0-3, 8.0-5
Steps to reproduce:
1. Launch The Witcher 3: Wild Hunt in Steam, select New Game
2. Move or rotate the mouse quickly and watch the blocky corruption
If the image has general layout and render target state, then add color attachment access masks for its resource barrier.
Witcher 3 - Corruption
Witcher 3 - D3D Capture
Witcher 3 - Proton debug (d3d-proton)  
Below is my detailed debugging process for the above problem: You …
> Fix the missing access flags of image resource barrier conversion

- libs/d3d12/d3d12.def
> vkd3d: Export D3D12GetInterface from d3d12.dll as well.

- libs/vkd3d/command.c
> vkd3d: Fix silly DGC EXT validation error.

- include/vkd3d.h
- libs/vkd3d/device.c
It's not 100% safe to enable by default,
but should be okay in 99.99% of cases.
> vkd3d: Add config flag for true TRANSFER queue.

- libs/vkd3d/resource.c
> vkd3d: Handle out of range maxAnisotropy values for static samplers.

- include/vkd3d.h
- libs/vkd3d/device.c
- libs/vkd3d/heap.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_crosstest.h
- tests/d3d12_resource.c
God of War Ragnarok appears to use it.
Not 100% sure about the interaction with the existing system that promotes the regular UPLOAD_HEAP to rebar based on a budget.
I decided to go for the following:
- We only report support for the GPU_UPLOAD_HEAP if the existing logic has decided that we have a Rebar budget. Otherwise the same problem of potentially taking VRAM from other resources which need it more applies even if the application itself decides to put it in Rebar.
- When actually allocating memory the budget is ignored if it was the application that decided to put it into Rebar instead of our automatic promotion logic.
- After feedback: Once we allocate memory for either GPU_UPLOAD_HEAP or an equivalent custom heap, the automatically promotion logic gets disabled.
-  Resource …
> Implement GPU upload heap.

- libs/vkd3d/resource.c
While this matches what the docs say, it breaks Halo Infinite.
The heap Halo creates is on `D3D12_HEAP_TYPE_CUSTOM`, `D3D12_MEMORY_POOL_L0` and `D3D12_CPU_PAGE_PROPERTY_WRITE_BACK`.
The flags are: `D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER | D3D12_HEAP_FLAG_SHARED | D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES | D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES`.
Both the [spec for the GPU upload heap](https://microsoft.github.io/DirectX-Specs/d3d/D3D12GPUUploadHeaps.html#restrictions) as well as the [documentation for shared heaps](https://learn.microsoft.com/en-us/windows/win32/direct3d12/shared-heaps) say this is illegal.
Cross Adapter heaps are even more specific:
> Either D3D12_HEAP_TYPE_DEFAULT must be set or D3D12_HEAP_TYPE_CUSTOM with D3D12_MEMORY_POOL_L0 and D3D12_CPU_PAGE_PROPERTY_NOT_AVAILABLE must be …
> vkd3d: Remove shared heap CPU visible check.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
Avoids pessimizing performance when no_upload_hvv is used.
> vkd3d: Use GPU upload heap for internal scratch allocations.

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
If game explicitly asks for GPU_UPLOAD we should honor it. Also allows our internal scratch allocations for uniform memory to use ReBAR on more modest VRAM configurations as well.
> vkd3d: Allow exposing GPU_UPLOAD heap on smaller VRAM as well.

- libs/vkd3d/command.c
- libs/vkd3d/queue_timeline.c
- libs/vkd3d/vkd3d_private.h
- Add queue profiling support for sparse.
- Remove old compaction workaround for NV drivers. Reported to be fixed on r535.
> Misc smaller sparse improvements

- libs/vkd3d/device.c
Multiple reports of this causing some sort of memory corruption that leads to crashes for unknown reason. Since I cannot reproduce that at all, it's essentially not debuggable.
This will disable MSAA for the game again.
> vkd3d: Revert programmable sample position override for Pagonia.

- include/vkd3d_d3dcommon.idl
- libs/vkd3d/bundle.c
- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/heap.c
- libs/vkd3d/meta_commands.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_device.c
- tests/d3d12_tests.h
I lost multiple brain cells writing this code, but the TL;DR is that *every* D3D12 COM object supports this interface, and according to the docs it's supposed to fire any registered callback *before* references to other objects are released, hence the jank around objects that we keep alive internally.
Apparently this is needed by The Forever Winter, although I haven't seen it use the interface myself while testing.
> Implement ID3DDestructionNotifier

- libs/vkd3d/cache.c
- libs/vkd3d/vkd3d_private.h
FF XVI attempts to serialize back to same pointer that unserialized. This is not legal, but it would work if we guaranteed stable serialization, which we don't. Workaround it by detecting overlapping memory and serializing to temporary memory.
> vkd3d: Workaround buggy API usage patterns with pipeline libraries.

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/device.c
Should fix glitched graphics due to game bug.
> Force precise vertex shaders in Hunt: Showdown

- libs/vkd3d/device.c
Game suffers from performance dips (on my end from 165 fps to 82 [lowest] and then back up to 165) with Rebar on while cutscenes are playing. no_upload_hvv fixes the issue. Tested with 7900 XTX-RADV-Mesa 24.2.5.
Fixes https://github.com/HansKristian-Work/vkd3d-proton/issues/2178
> Add NO_UPLOAD_HVV workaround for Red Dead Redemption

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Latest beta fixes this, and there's no need to carry around workarounds for developer betas.
> vkd3d: Revert EXT_dgc workaround on NV.

- libs/vkd3d/device.c
Fixes an error popup + subsequent crash in Monster Hunter Wilds, tldr on Nvidia we're reporting `TILED` resource support for depth-stencil by accident, which is bogus because D3D12 does not support this and we error out in resource creation anyway.
> vkd3d: Do not report tiled resource support for depth-stencil formats.

- libs/vkd3d/device.c
- libs/vkd3d/state.c
Two things that have been bothering me for a while:
- There's absolutely nothing about the `stencilTestEnable` thing that's worth logging, it is however something we hit in countless games in thousands of pipelines, so we might as well get rid of it. Also removed the `depthTestEnable` one since this can only really happen if the DSV format is not a depth-stencil format, which gets validated and logged in a different place anyway.
- The `Invalid plane index 0 for format 0.` thing is fallout from the NV12 work quite a while back. Now the fix of just making the aspect non-zero is rather lazy, but the entire function seems a bit lazy to begin with given that we're shoehorning buffers onto the image path by defining a custom `UNDEFINED` format anyway and it silences the message.
The …
> Silence some log spam

- tests/test-runner.sh
Avoids test flakes in test_object_interface due to a race condition on private interface being destroyed in pipeline objects.
> tests: Disable shader cache for test runner.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
When misusing `UpdateTileMappings`, I experimented a bit on Windows drivers and got wildly inconsistent results. Two main scenarios are scary:
Binding valid memory to out-of-bounds tile indices:
- WARP removes the device
- AMD wraps around (???) and starts binding early tiles, at least for buffers
(unless the base tile is out of bounds, in which case it silently ignores  the call)
- Nvidia only ignores out-of-bound tiles, but otherwise succeeds
Binding out-of-bounds heap memory to a valid tile:
- WARP and Nvidia remove the device
- AMD silently ignores the call
With other invalid / questionable uses, such as passing invalid subresource indices, out-of-bounds image coordinates, setting `UseBox` when mapping a buffer etc I've seen all sorts of combinations of driver segfaults, calls getting …
> vkd3d: Perform minimal validation on page table updates.

- libs/vkd3d/device.c
...turns out doing this before actually doing anything queue-related at all doesn't exactly work.
> vkd3d: Fix queue family logging in device creation.

- libs/vkd3d/command.c
Recently I found that `test_renderpass_rendering` failed with RADV.
The failures are in the `render pass resolve` and the results may be the clear values of resolved render target. Just like the draw calls for `rt_ms` do not take effect.
(It seems there are 2 bug_if here....)
After investigation, I think the root cause is that this test uses incorrect `srcAccessMask` of pipeline barrier between multi-sample target and resolved target. (the pre_resolve barrier)
Since `srcAccessMask = VK_ACCESS_2_NONE`, thus CB cache would not be flushed.
https://github.com/HansKristian-Work/vkd3d-proton/blob/a187ec876edf5dcd1736d027c0b9e2fba6a01f8e/libs/vkd3d/command.c#L9101-L9118
While `outside_access` here is `VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT`, so we could …
> Fix the incorrect access mask of barrier for render pass resolve

- tests/d3d12_render_target.c
It was a vkd3d-proton bug, not RADV.
> tests: Remove bug_if for render pass resolves.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Fixes a potential issue where we might submit a wait on another queue's submission semaphore that has already been destroyed.
Ran into this while testing #2202 on AMDVLK.
> vkd3d: Properly flush waiters before destroying queues.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Reserve a queue similar to internal compute queue.
Also, make sure that the internal sparse queue attempts to use something other than the graphics queue if possible.
> Make sure that our internal sparse queue does not alias with other user queues

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Workaround for #2215.
This moves fence wait tracking from `vkd3d_queue` to the virtual queues and optimizes away most of the empty submissions that only do a semaphore wait and a semaphore signal, which is what caused the massive performance degradation in Cyberpunk since AMDGPU does not handle this very well.
Additionally, sparse binding serialization now uses the queue's timeline instead of the binary semaphore. At worst, there will now be one extra `vkQueueSubmit` on the first sparse binding call in order to flush waiters, rather than doing a round-trip over the graphics queue each time.
One potential concern is that this may delay fence signals in scenarios where we set `NO_STAGGERED_SUBMIT` in case the app does something like `queue->Wait(...); nothing for quite some time; …
> Rework semaphore waiting

- tests/d3d12_depth_stencil.c
Recently I found that `test_depth/stencil_load` failed with AMDVLK.
The results of compute shader sometimes are the clear values of last iteration which are incorrect. Just like the cs executed before the depth/stencil clear. (depth/stencil would be used as SRV here)
After investigation, I think the root cause is that these tests use incorrect dst resource state for depth/stencil.
Since only `D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE` is used, the sync is correct for ps but incorrect for cs.
Thus `D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE` is also required.
> tests: Fix resource state of compute SRV in test_depth/stencil_load

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Fallout from the Stalker 2 thing. Unclear if we want to add validation since ANV worked around the problem for now, but I think having the numbers in one place is good practice.
D3D12 behaviour is a mess, all drviers allow creating view descriptor heaps with >1M descriptors, but creating a heap *too* large can either return `E_OUTOFMEMORY` or remove the device entirely.
> vkd3d: Clean up reporting and checking maximum descriptor counts.

- include/vkd3d.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
Fix #2092.
This doesn't make much sense, but it seems to fix the hang for me.
Breadcrumbs are pointing to "nothing", suggesting that the hang happens in internal driver code which does who knows what. Hopefully this is a viable workaround and we can report something actionable to NV.
> Attempt to workaround Outlaws hang on NV

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_copy.c
- tests/d3d12_tests.h
Basically changes `vk_image_copy_from_d3d12` to do all the relevant math on compressed blocks rather than texels in order to fix various issues with copies between different formats.
> Fix RGBA <-> BCn image copies

- libs/vkd3d/device.c
Ever since commit 40e4b22fdc6d34a8b05334835c5d77c12c7feaf3, vkd3d would try and allocate a sparse queue unconditionally even if the hardware didn't support sparse. The cause of this comes from the logic inside of `d3d12_device_create_vkd3d_queues` which would skip any queues that were `VK_QUEUE_FAMILY_IGNORED` but was initializing `queue_family_indices` to zero. Zero is a valid queue index which would cause logic later to always try and allocate a queue unconditionally. The simple fix is to initialize these indices to be VK_QUEUE_FAMILY_IGNORED (which is ~0U) instead of zero.
Fixes a crash on Turnip (and any other driver that doesn't support sparse), when running any d3d12 game.
> vkd3d: Fix crash on hardware that doesn't support sparse.

- libs/vkd3d/memory.c
Matches DXVK behaviour and should fix #2258, but needs testing.
The idea here is that if we want to allocate system memory (as a fallback or otherwise, e.g. `UPLOAD` heaps in an app that also uses GPU upload heaps), we should never try to allocate from device-local memory unless all supported memory types for a given allocation are device-local.
Also fixes the possible case where a fallback allocation with no property flags would attempt to allocate from `DEVICE_LOCAL` again. This only hasn't been an issue so far because most drivers allow oversubscribing VRAM, but this is not guarateed.
> Only allocate device memory if explicitly requested

- libs/vkd3d/command.c
- libs/vkd3d/queue_timeline.c
- libs/vkd3d/vkd3d_private.h
Adds more actionable information to queue profiles.
- Shows overhead done in the submission threads for QueueSubmit
- Marks regions for all submission thread operations such as waiting, signalling, etc.
- Adds the VkQueue pointer to the capture, making it easier to figure out which queues alias.
> Queue profile improvements rebase

- libs/vkd3d/device.c
Fixes #2270 at the cost of some runtime performance.
Game seems to have a bunch of different executables, so let's be conservative here.
> vkd3d: Enable no_upload_hvv for ArmA Reforger.

- libs/vkd3d/command.c
It's possible to use SKIP tiles for everything and that leads to error on NV driver due to DEVICE_LOST following invalid usage with bindCount == 0.
> vkd3d: Avoid VVL error when game binds nothing.

- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
Fixes crashes when Buffer type resources are used for UAVInfo collection and CUDA Surface/Texture object retrieval.
This fixes a launch-time crash for Cyberpunk 2077 reported in https://github.com/jp7677/dxvk-nvapi/issues/245#issuecomment-2611149566
> Fix Buffer Resource UAV collection + Cuda Surface Object Retrieval

- libs/vkd3d/command.c
this avoids renderpass copies for allowed formats, though only DIRECT/GRAPHICS queue is supported by maintenance8
> vkd3d: enable ds<->color copies using maintenance8

- tests/d3d12_sm_advanced.c
> tests: Disable overzealous SM 6.0 Quad op test.

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
Non coherent host visible memory touched from the host needs to be flushed before it gets used on the device.
Fixes VKD3D_TEST_FILTER=test_execute_indirect ./build/tests/d3d12 on Anv/Meteorlake which appears to be the only platform to have a memory type that is HOST_VISIBLE | HOST_CACHED memory type (without HOST_COHERENT).
Found-by: José Roberto de Souza <jose.souza@intel.com>
> vkd3d: add missing memory flush on cpu clear operations

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
The callback refactor moves all the hardcoded stuff that we do in the fence worker to callbacks, and stores callback data within the `vkd3d_fence_wait_info` structure. 
For fence waits it doesn't look like there was any reason at all to keep the fence objects alive, so I removed that part.
Lastly, this adds some tracking to keep sparse resources alive through page table updates; otherwise, Monster Hunter Wilds screws up synchronization somewhere and will either crash or hang on Nvidia when starting the benchmark with DLSS FG enabled.
> Fence worker callback + work around MHW sparse bug

- libs/vkd3d/device.c
@Blisto91 found a regression from #2336. TL;DR we leave `real_driver_props` uninitialized when maintenance7 isn't supported (e.g. current Proton), but then use it to override the real driver ID.
This just always zero-inits everything to be safe.
> vkd3d: Properly initialize layered driver info.

- libs/vkd3d/device.c
The game updated today.
The shader hash in question changed to f6ce99fa20cc4da2 for reference, and it seems like the game now adds a proper UAV barrier.
> vkd3d: Remove shader quirk for Rebirth.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
Exactly same bug, but now it's in a different shader. Triggers on the central ocean in chapter 12. Likely caused by only terrain being present, so it doesn't have a chance to barrier on normal meshlets.
> vkd3d: Reintroduce shader quirk barrier for Rebirth.

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
- libs/vkd3d/device.c
Until we understand what is going on, this seems to be needed.
> vkd3d: Add heap robustness workaround to MHW.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
There's some jank with how xfb is supposed to work, the TL;DR here is that every xfb buffer referenced by `BeginTransformFeedbackEXT` needs to have a valid binding, and we can't bind `NULL` buffers (not allowed per spec, even with null descriptors enabled).
Additionally, the spec explicitly bans changing pipelines while xfb is active, so just end the render pass when that happens. The most common usage pattern by far is to do a single draw per xfb pass anyway, so this won't suddenly become a source of perf issues in the few games that use xfb.
Fixes ##2368.
> Fix xfb validation errors

- setup_vkd3d_proton.sh
This will make it work with wine >=10.2 and older
Some "major" changes to wine-10.2 dropped the usage of `wine64` binary, so a lot of scripts broke as they depended on checking system32/syswow64 usage when using wine64/wine respectively.
This should do some checks to verify folder structures so it is useful again.
> script: Update installscript

- libs/vkd3d/command.c
Silences VVL errors in #2373. This is another test that deliberately tests broken things, but we can just add the missing stage flags.
> vkd3d: Sanitize stage flags for enhanced barriers.

- libs/d3d12/main.c
> vkd3d: Get rid of VVL issue 9613 exception.

- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d/device.c
Same story as with Wu Long, the game renders extremely over-tessellated terrain for no reason at all.
In the main menu, the singular draw that renders terrain goes from ~3ms to ~0.6ms on my 6900XT.
> Limit tessellation factors for Rise of the Ronin

- libs/vkd3d-shader/spirv.c
- tests/d3d12_clip_cull_distance.c
Fixes #2379.
Highly cursed in that we simply didn't support clip/cull as shader input at all, and multi-dimensional arrays were also not really supported - except in PS because PS inputs use different instructions compared to everything else, but we weren't declaring it correctly there either.
Can't really reuse any of the existing code for clip/cull either because outputs are handled very differently from inputs.
Domain shaders are entirely excluded here because we simply pass vec4 arrays around without checking for semantics. The only thing that's semi-interesting there is tess factors.
Should probably be tested with real games as well; test suite passes though and I'm not seeing any spirv-val errors.
> vkd3d-shader: Fix cull/clip distance used as shader input.

- libs/vkd3d/device.c
War Thunder doesn't render anything otherwise.
Should be safe to do this since min16 stuff doesn't *really* have any guarantees, and we implement this properly in DXIL if the device supports 16-bit things anyway.
> vkd3d: Expose 16-bit min precision support.

- tests/d3d12_pso.c
VVL doesn't seem to understand when pointmode is set in TESC.
> tests: Add VVL mute for PointMode tessellation.

- tests/d3d12_resource.c
- tests/d3d12_test_utils.h
This fix tries to address failures on Adreno (via Turnip) in the `test_suballocate_small_textures_size` test case. Failures were initially observed on very narrow textures, but there's enough other conditions at play (15% of tests were failing) that it might not make sense to provide specific exceptions for expected failures.
Adreno-specific computation of the expected size is provided. It follows Freedreno's layout computation, but doesn't necessarily address different cases we don't hit in this test. The computation is used for both Adreno blob and Turnip, though it was only tested on the latter (vkd3d doesn't run cleanly on blob last I heard).
> tests: fix small-texture allocation size tests for Adreno

- libs/vkd3d/device.c
It uses DGC now for ... some reason.
> vkd3d: Add raw CBV VA for Eve Online.

- libs/vkd3d/device.c
For vkd3d, Turnip enables D3D round-to-even behavior for texcoords, making exposing PointSamplingAddressesNeverRoundUp incorrect.
> vkd3d: Don't expose PointSamplingAddressesNeverRoundUp on Turnip

- tests/d3d12_copy.c
Adjust the test_multisample_resolve_strongly_typed unit test to address Adreno drivers ignoring sRGB during multisample attachment resolves, which is allowed per spec.
> tests: expect bugged sRGB multisample resolves on Adreno

- libs/vkd3d/memory.c
AMDVLK has already enabled `AMDGPU_GEM_CREATE_VRAM_CLEARED`. And KMD would eventually do it once the bug is fixed.
> vkd3d: add amdvlk to vkd3d_driver_implicitly_clears

- tests/d3d12_mesh_shader.c
- tests/d3d12_tessellation.c
VVL tries to report the spirv-val VUID now instead of generic SPIR-V vuid.
> tests: Update VVL mutes to reflect recent VVL update.

- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Raw BDA access, even with NonWriteable, is terrible. This can sometimes be mitigated if the CBV offset is uniform over the whole draw via prefetching, but when that isn't the case then performance really suffers.
> vkd3d: Use push descriptors for root CBV on Qualcomm

- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_resource.c
- tests/d3d12_tests.h
Not exhaustive. TLDR this tests a 6GB heap with:
- UAV + copies involving small placed buffers at large offsets
- UAV + copies involving one large placed buffer covering the entire allocation
- binding tiles to a small sparse buffer
This currently doesn't test other buffer uses, or creating placed images.
Heap creation is allowed to fail (and does so on WARP), however Assetto Corsa EVO crashes if we do that, so not supporting large heaps isn't exactly an option.
Creating a placed buffer to cover the entire heap seems to be required in D3D12 and does work, however AMD native crashes when trying to create view descriptors at ≥4GB *buffer* offsets. Smaller placed buffers on a large heap work as expected.
On the vkd3d-proton side, we exceed `maxBufferSize` on mesa drivers as well as amdvlk …
> Test and fix some large heap behaviour

- libs/vkd3d/device.c
There was an [update](https://store.steampowered.com/news/app/1874880/view/529845510803031624) for the game with the next changelog
> ### Stability and Performance
> Changed: Optimization of memory usage in rendering
I decided to check if it did anything, loaded game with GE-Proton9-10 which should contain old vkd3d version without this fix and I couldn't reproduce it anymore. I guess there's no issue with asset loading so we can drop this workaround in order to increase performance.
> Revert "vkd3d: Enable no_upload_hvv for ArmA Reforger."

- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/meta_commands.c
- libs/vkd3d/shaders/cs_emit_nv_memory_decompression_regions.comp
- libs/vkd3d/shaders/cs_gdeflate.comp
- libs/vkd3d/shaders/cs_gdeflate_prepare.comp
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
Now that the upstream implementation is dual-licensed as Apache/MIT, we can finally do this.
This allows us to always expose the metacommand rather than relying on the fallback shader in DStorage itself, which is a) slow and b) broken in version 1.2.3, which has famously been causing us issues in Monster Hunter Wilds.
Draft for now because this could do with some testing on more hardware; RDNA2 works in real games and Lavapipe passes our test so it *probably* should work on anything Mesa at least.
This is quite heavily modified in that I put everything into one file and rewrote all the wave op fallbacks to be subgroup size-agnostic, so this *heavily* relies on driver constant-folding at least `gl_SubgroupSize` for good code gen (i think on Intel we even get `gl_NumSubgroups` as a …
> Add decompression shader for DirectStorage metacommand implementation

- libs/vkd3d/device.c
The executable of Satisfacory is FactoryGameEGS-Win64-Shipping.exe on Epic Games
> vkd3d: Add EGS exe name for Satisfactory quirks

- include/vkd3d_d3d12.idl
- libs/vkd3d/device.c
- tests/d3d12_pso.c
- tests/d3d12_tests.h
Checked the agility SDKs and this was added in 610, and the field was always there, so don't think there's any risk of there having been a break.
Closes #2511.
> Options struct size fix

- libs/vkd3d/device.c
It's the only `vr %u` in the entire repo and I still ran into it. Such is my luck I guess.
> vkd3d: Fix VkResult print format in d3d12_device_create_query_pool.

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d/device.c
Fixes #2530
Basically the idea is that if we encounter a derivative instruction which uses one of the input registers as the src without dynamic indexing and we're in the main function, put the derivative instruction at the beginning of the function.
It's not pretty but it seems to work for Dead Space and the shader that caused the bug validates fine. I've not really tested it beyond that. It would serve as a temporary solution until there's a proper compiler.
There's probably a bunch of edge cases I'm not thinking of right now, so consider this PR more of an RFC.
> Band-aid fix for Dead Space derivatives

- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
These warning messages are stricter than necessary. This change removes warnings when we receive repeated PRESENT or RENDER markers with the same frame id, and removes warnings for SIMULATION markers entirely.
For more context see the discussion on this dxvk-nvapi pull request to remove their filtering of doubled markers: https://github.com/jp7677/dxvk-nvapi/pull/307.
Many apps send doubled present markers in the pattern below. This behavior is widespread even in Vulkan native apps, and not worth logging a warning for. The NVIDIA driver handles this case reasonably.
VK_LATENCY_MARKER_PRESENT_START_NV
VK_LATENCY_MARKER_PRESENT_START_NV
present
VK_LATENCY_MARKER_PRESENT_END_NV
VK_LATENCY_MARKER_PRESENT_END_NV
On top of that I see that Hitman World of Assassination issues two SIMULATION …
> Reduce NVIDIA latency marker warnings in acceptable cases

- libs/vkd3d/device.c
> vkd3d: Remove amdgpu zerovram workaround on 6.15.9+.

- libs/vkd3d/command.c
D3D12 validation allows garbage if size is 0.
> vkd3d: Ignore every other IBV field if SizeInBytes is 0.

- libs/vkd3d/device.c
Fixes https://github.com/HansKristian-Work/vkd3d-proton/issues/1623.
> vkd3d: Enable dxbc-spirv for Red Dead Redemption 2.

- libs/vkd3d/resource.c
Fixes a bug where the last descriptor doesn't show up in RenderDoc since we're technically accessing mutable descriptor out of bounds.
> vkd3d: Make sure to allocate padding area for embedded mutable.

- libs/d3d12/meson.build
- libs/d3d12core/meson.build
- meson.build
Makes it possible to link against vkd3d-proton via pkg-config properly. The old code only worked with the now defunct private API that doesn't go via D3D12CreateDevice and friends.
> meson: Fix pkg-config build.

- tests/d3d12_sampler_feedback.c
Using 0.01 for epsilons causes some gradients to be integer +/- epsilon, which made QueryLOD behave very slightly differently on NVK, leading to a test failure. Just use a more FP friendly epsilon to fix.
> tests: Tweak sampler feedback aniso test to reduce precision errors.

- libs/vkd3d/device.c
Missing UAV barrier between custom clear shader and light injection.
Closes #2561.
> vkd3d: Add sync workaround for Wuthering Waves.

- libs/vkd3d/timestamp_profiler.c
Only affects builds with profiling enabled.
> vkd3d: Fix trivial crash if timestamp profiling is not enabled.

- include/vkd3d.h
- include/vkd3d_device_vkd3d_ext.idl
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vkd3d_private.h
LockCommandQueue() is currently used in Proton's vrclient / wineopenxr to wrap the calls where VR runtime may be accessing Vk queue backing d3d12 queue.  LockCommandQueue, besides locking access to Vulkan queue, does much more of heavy syncing: drains and locks d3d12 queue. In the majority of cases in vrclient and wineopenxr the latter is excessive: apart from select call where we do need to make sure d3d12 queue contents has reached Vulkan queue we just need to synchronize access to Vulkan queue while we don't care about the d3d12-side queued contents.
The second patch also avoids queue draining in GetVulkanQueueInfo[Ex], those are used in vrclient twice each frame (as there is no generally configured d3d12 queue, the queue is passed as a part of texture data in each call to …
> vkd3d: Add vulkan queue locking methods.
