- libs/vkd3d-shader/spirv.c
Need to report back actual bindings, not 0/0.
> Fix regression with UAV counters.

- libs/vkd3d-shader/spirv.c
Makes adding new capabilities significantly easier, and we're going to add quite a lot of them with bindless (as well as future features).
> vkd3d-shader: Rework SPIR-V capability enablement.

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxbc.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d/state.c
> Binding model: Shaders

- configure.ac
- include/private/vkd3d_common.h
- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Root signature refactor part 1

- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Root signature refactor part 2

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Root signature refactor part 3

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Root signature refactor part 4

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Root signature refactor part 5

- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Binding model: Bindless part 1

- libs/vkd3d/command.c
Fixes an oversight of the previous PR. This just happened to work since AMD drivers treat descriptor pools as a contiguous block of memory without checking individual descriptor type counts.
> vkd3d: Allocate descriptor pool space for inline uniform blocks.

- libs/vkd3d/resource.c
Avoids overflowing vkCreateFramebuffer later with UINT_MAX layers.
> vkd3d: Clamp RTV/DSV array sizes to their real array lengths.

- Makefile.am
- include/private/vkd3d_common.h
- include/private/vkd3d_spinlock.h
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
> Replace descriptor mutex with spinlocks

- libs/vkd3d/command.c
> vkd3d: Fix compilation warning on 32-bit.

- libs/vkd3d-shader/spirv.c
Fixes #81, which is a classic case of unnecessary code duplication causing problems.
> vkd3d: Rework vkd3d_dxbc_compiler_get_resource_binding.

- libs/vkd3d/resource.c
Title. When mapping resources on a non-coherent heap, flush/invalidate the memory range as requested by the application, instead of falling back to uncached memory.
While there's no immediate need for this, some older Intel GPUs as well as MoltenVK do not provide `HOST_CACHED | HOST_COHERENT` memory types, in case anyone is mad enough to run vkd3d on that, and it allows us to get rid of some annoying debug messages.
> vkd3d: Do not require host-coherent memory for readback heaps.

- libs/vkd3d/device.c
Unblocks some games that request Feature Level 12.0, such as Anno 1800, Monster Hunter World, The Talos Principle. May cause issues if games use unsupported features.
> vkd3d: Add VKD3D_FEATURE_LEVEL override.

- include/private/vkd3d_common.h
- include/private/vkd3d_spinlock.h
- libs/vkd3d/command.c
> vkd3d: Replace dummy atomic_fetch_add with atomic loads.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Title; should make it significantly easier to add an extra queue family for sparse binding later on.
> Queue cleanup

- libs/vkd3d/command.c
Title. I'm adding more stuff here for tiled resources that can fail, so it won't hurt to have a somewhat clean code path.
> vkd3d: Improve error handling in d3d12_command_queue_init.

- libs/vkd3d/command.c
FIxes issues in the new AMD demos.
> Misc. Fixes

- libs/vkd3d-shader/spirv.c
Works around a driver bug on NV which affected RE2 in particular, but
probably other titles as well.
Fixes flashlight in RE2, and also seems to have fixed the firefly bug as well. I can no longer reproduce it with this patch.
Fix #79.
> vkd3d-shader: Only sample with the required number of components.

- libs/vkd3d/command.c
D3D12 apparently does this implicitly. Fixes rendering issues in the AMD COCOA demo on Polaris with RADV, which does not emit a barrier between the AO compute passes and the tone mapping pass in the next command buffer.
> vkd3d: Issue full barrier at the end of command lists.

- libs/vkd3d-shader/dxbc.c
This is a set of flags, so we should treat it as such.
> vkd3d-shader: Fix modifier handling.

- include/private/vkd3d_utf8.h
- libs/vkd3d-common/utf8.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
> Implement PIX Debug markers

- libs/vkd3d-shader/spirv.c
Does not fix any bugs, just reduces the number of misleading log messages in Anno 1800 and potentially other games.
> vkd3d-shader: Introduce vkd3d_dxbc_compiler_find_register_info.

- demos/gears.c
- demos/triangle.c
Fixes some problems when building the demos under MSVC on Windows.
> vkd3d: Demo fixes for Win32

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
With timeline semaphores, we can reasonably implement this feature.
> Support fence rewinding

- include/private/vkd3d_spinlock.h
Tell the cpu that we are spinning.
> vkd3d: use pause while spinning on x86

- libs/vkd3d/meta.c
> vkd3d/meta: Initialize flags variable.

- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
These were spotted while I was reading the code to learn more about it...
> Fix misc. obvious bugs I spotted

- .gitlab-ci.yml
- meson.build
- package-release.sh
- Don't depend on xcb, etc when not building demos
- Disable some warnings that were somehow left out of the ``warning_level=2`` PR (I had them locally but they got lost, oops!)
- Add a helper script for packaging releases
- Add .gitlab-ci.yml for froggi.es
- Make a repo on https://git.froggi.es
- Push code there
- It will build and the artifacts will be there forever for bisecting
> Meson work + setup froggi.es CI

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
> Implement null descriptors

- libs/vkd3d/vkd3d_main.c
Make this code more extensible too...
> vkd3d: Add support for serializing root signature version 1.1

- libs/vkd3d-common/utf8.c
Why is this not an error in C, sigh ...
> vkd3d: Fix pointer type mismatch.

- README.md
> vkd3d: Update README.md.

- README.md
> vkd3d: Update clone link in README.md.

- libs/vkd3d/swapchain.c
The output here is actually for secure presentation and restricting a swapchain to a certain output.
Correctly handle NULL (desktop) targets that we used to have.
Fixes crashes with titles that use fullscreen via an initial fullscreen desc.
> vkd3d: Correctly handle output + fix NULL old targets for fullscreen 

- README.md
- package-release.sh
This also makes that the default behaviour, which is what we want for end users.
> Update package-release for cross building

- libs/vkd3d/command.c
> vkd3d: Fix warnings in calibrated timestamp implementation.

- libs/vkd3d/command.c
Fixes a crash in Shadow of the Tomb Raider.
> vkd3d: Handle pRegion == NULL in DiscardSubresource.

- tests/descriptor_performance.c
- tests/meson.build
Tests CPU descriptor creation as well as copies in various scenarios.
> tests: Add a simple micro-benchmark for descriptor performance.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Remove packed descriptors

- meson.build
- tests/meson.build
> meson: Target native d3d12 for Windows test binaries.

- README.md
- libs/vkd3d/device.c
- libs/vkd3d/utils.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Load VK_LAYER_KHRONOS_validation if we enable debug mode.

- tests/d3d12.c
> tests: Fix uninitialized Layout member.

- libs/vkd3d/resource.c
Only bother if nullDescriptors are supported.
> vkd3d: Zero out descriptor heaps on allocation.

- Makefile.am
- README.md
- include/shader-debug/debug_channel.h
- libs/vkd3d/command.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
This is the end-game of in-app debugging support.
> Add support for a shader debug ring.

- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/resource.c
- libs/vkd3d/shaders/fs_swapchain_fullscreen.frag
- libs/vkd3d/shaders/vs_swapchain_fullscreen.vert
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vkd3d_shaders.h
The first step is to add various pipelines to the meta system. It will be used by swapchain module in later parts.
> Swapchain blitting rewrite - part 1

- package-release.sh
- setup_vkd3d.sh
> build: Add install script to packaged releases

- include/private/vkd3d_threads.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/command.c
- meson.build
I'm not sure if we care enough about to actually enable the warning. I'm okay either way.
> Declaration after statement fix

- include/private/vkd3d_debug.h
- libs/vkd3d-common/debug.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/device.c
- libs/vkd3d/renderdoc.c
> Add INFO logging level.

- include/private/hashmap.h
- include/vkd3d_shader.h
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
Title, basically.
Closes #326.
> vkd3d-shader: Fix hard-coded UAV and sampler limits

- libs/vkd3d/command.c
Closes #347 (requires RTV rework as well though).
> Minor fixes for StarsX samples

- demos/meson.build
- include/meson.build
- libs/vkd3d-common/meson.build
- libs/vkd3d-shader/meson.build
- libs/vkd3d/meson.build
- tests/meson.build
Fixes MSVC build.
Closes: #343
> build: Merge vkd3d_headers into vkd3d_common

- libs/vkd3d/resource.c
> vkd3d: Init hashmap in vkd3d_create_image_resource

- package-release.sh
I'm sorry I made that mistake in the first place.
> build: Fix quotes in package-release.sh.

- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
> Support creating pipelines with NULL root signature.

- meson.build
> Mark version 2.0.

- libs/vkd3d/device.c
> vkd3d: Fix shader model-related feature detection.

- libs/vkd3d/resource.c
> vkd3d: Fix validation spam for null descriptor buffers

- libs/vkd3d/resource.c
> vkd3d: Handle reserved resources in host barrier code

- libs/vkd3d/device.c
dxil-spirv update fixed the issue for me.
Fix #382.
> vkd3d: Re-enable wave ops.

- libs/vkd3d-shader/spirv.c
This is undefined behaviour in SPIR-V, but well-defined in DXBC, so we should explicitly 'and' the shift amount with 31.
> vkd3d-shader: Correctly handle bit shifts greater than 31 bits.

- include/private/vkd3d_atomic.h
- libs/vkd3d/device.c
Supersedes #390 and should hopefully avoid any sort of race condition.
> Singleton devices v2

- tests/d3d12.c
Fixes some random test failures.
> tests: Add missing UAV barriers in test_cs_uav_store.

- libs/vkd3d/command.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Separate root VA use for CBV and SRV/UAV.

- libs/vkd3d/command.c
Signed-off-by: Philip Rebohle <philip.rebohle@tu-dortmund.de>
> vkd3d: Fix offset for predicate buffer.

- libs/vkd3d-shader/spirv.c
> vkd3d-shader: Fix saturates of fp64 types

- libs/vkd3d/command.c
Timestamp queries are not scoped, so ending the render pass is only necessary if we need to reset the query late.
> vkd3d: Do not interrupt render pass for timestamp queries.

- include/private/hashmap.h
- libs/vkd3d/resource.c
> Fix latent bug in hashmap implementation

- CHANGELOG.md
> meta: Slight modification to CHANGELOG.

- meson.build
> meta: Bump Meson build version to 2.1.

- README.md
- libs/vkd3d/device.c
The same as `DXVK_FILTER_DEVICE_NAME`.
> vkd3d: Introduce VKD3D_FILTER_DEVICE_NAME.

- libs/vkd3d/command.c
> vkd3d: Fix warning in query logging

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
Supercedes: #471
Will add a MSVC build test down the line -- need to figure out the glslang logistics there.
> build: Add Github Actions workflows

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12.c
> vkd3d: Implement TIER_1 variable rate shading

- libs/vkd3d/device.c
> vkd3d: Refactor vkd3d_physical_device_info_init

- meson.build
> build: Enable --quiet on glslangValidator

- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Fix validation errors with KHR_fragment_shading_rate.

- libs/vkd3d/resource.c
> vkd3d: Fix SetName for inline query types

- libs/vkd3d/raytracing_pipeline.c
- tests/d3d12.c
Also adds some minor test fixes while I was testing Windows behavior.
> Add more tests to stress allocation with multithreading

- libs/vkd3d/resource.c
Allows us to not allocate device memory for certain render targets on Polaris GPUs.
> vkd3d: Align images manually to meet Vulkan requirements if necessary.

- libs/vkd3d/swapchain.c
> vkd3d: Account for front buffer in swapchain image count

- tests/d3d12.c
Validates that we can create RTVs at 64k alignment without issues.
> tests: Add image placement alignment test.

- CHANGELOG.md
> changelog: Update for 2.2.

- libs/vkd3d/device.c
There are pragmatic reasons for not following spec 100% here.
The only known case where UpdateAfterBind robustness is not exposed
seems to be somewhat bogus, and we cannot run D3D12 correctly without
robustness either way.
> vkd3d: Do not disable robustness, ever.

- .gitlab-ci.yml
Github Actions replaced the frogs.
> meta: Remove .gitlab-ci.

- libs/vkd3d/command.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Can successfully run the (albeit simple) RT test on NV now. :tada:
> Implement DispatchRays

- libs/vkd3d-shader/spirv.c
> Small DXBC control flow fixes

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12.c
- Implement RTAS copy operations for CLONE and COMPACT. Serialization is FIXME, but according to docs, it's only supposed to work in developer mode OS and PIX, so ... :shrug:
- Verifies that all required VBO formats and IBO formats work as expected.
Cleans up the ray tracing test a bit to make it a little less insanely hardcoded.
> Implement more DXR features and tests

- tests/d3d12.c
Worked as-is in our implementation as well.
> tests: Add test for RTAS update.

- libs/vkd3d/command.c
Signed-off-by: Philip Rebohle <philip.rebohle@tu-dortmund.de>
> vkd3d: Optimize unmapping adjacent resource regions.

- tests/d3d12.c
Runtime behavior here is extremely weird and contradicts spec wording in
many ways:
- Default local root signatures can override explicit ones.
- Runtime silently fails if the associated subobject is not part of the
PSO array.
- Order of default local root signatures doesn't appear to matter at
all.
All in all, very confusing, and there is zero help from validation
layer, so we'll have to deduce this from whatever applications want.
Hopefully they are somewhat sane, and don't try to rely on very awkward
matching rules.
> tests: Tests multiple local root signatures.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Fixes GPU bubbles in some games with multi-queue mode enabled.
> Create one fence worker per command queue

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/vkd3d_private.h
Fixes some extremely bizarre CPU hangs in Control.
> Ensure that physical timeline values are updated in order.

- include/private/vkd3d_test.h
> tests: Default VKD3D_TEST_DEBUG to 1

- libs/vkd3d/command.c
Previously this incremented and indexed before the loop checked this.
> vkd3d: Fix out of range in UpdateTileMappings

- include/vkd3d_d3d12.idl
- libs/vkd3d/command.c
> vkd3d: Implement ClearState.

- tests/d3d12.c
> tests: Don't crash if WRITE_WATCH is broken

- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Fix https://github.com/HansKristian-Work/vkd3d-proton/issues/568
Fix https://github.com/HansKristian-Work/vkd3d-proton/issues/592
> Implement DXR object collections

- tests/d3d12.c
Proves that shader-defined root signatures get ignored if one is provided by the API. Our implementation already behaves correctly.
> tests: Test root signature priority.

- libs/vkd3d/bundle.c
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Apparently fixes #604.
Edit: Marking as draft because there may be some ref counting weirdness left to test.
> Implement Bundles

- README.md
- include/private/vkd3d_test.h
> tests: Add env var to exclude tests.

- include/private/vkd3d_rw_spinlock.h
- include/private/vkd3d_spinlock.h
I was unreasonably annoyed by the detection duplication when I randomly opened one of the headers. :frog:
> vkd3d: Unify _mm_pause detection.

- tests/d3d12.c
> tests: Test that we can safely read ClipDistance in DS.

- demos/demo_xcb.h
- include/vkd3d.h
- include/vkd3d_shader.h
- libs/d3d12/main.c
- libs/vkd3d-shader/dxil.c
- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
- libs/vkd3d-utils/meson.build
- libs/vkd3d-utils/vkd3d_utils_main.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_main.c
- package-release.sh
- tests/d3d12_crosstest.h
- tests/vkd3d_api.c
- tests/vkd3d_shader_api.c
Remove the next/type stuff from our interfaces as they aren't very useful at all and just seem to cause more issues than they are worth.
> VKD3D and VKD3D-Shader Interface cleanup

- meson.build
Might help some people on debian or ubuntu.
> build: Conditionally enable --quiet for glslang.

- libs/vkd3d/command.c
test_update_tile_mappings fails if we don't do this.
> vkd3d: Workaround buggy NV driver in sparse update.

- CHANGELOG.md
> meta: Add some extra stuff to the 2.3 CHANGELOG

- libs/vkd3d-utils/vkd3d-proton-utils.def
> vkd3d-utils: Fix .def version.

- meson.build
> meson: Update to version 2.3.

- libs/vkd3d/state.c
DXR requires buffer_device_address, so it's meaningless to attempt a
fallback.
> vkd3d: Don't try to use fallback SRV aux heap.

- package-release.sh
> build: Don't strip binaries when doing a --dev-build

- tests/d3d12.c
Found validation errors while refactoring resource state stuff.
> Various test fixes

- libs/vkd3d/device.c
> vkd3d: Fix leak of command pools on device destruction.

- tests/d3d12.c
Runtime validates resource size.
> tests: Add test for placed resource runtime validation.

- libs/vkd3d/command.c
GravityMark ends up using ClearView with too large dimensions.
This is a validation error in Vulkan, so just clamp the extents.
To make full rect detection a bit more robust, do a range check instead
of memcmp().
> vkd3d: Be more robust with out of bounds clear/discard rects.

- libs/vkd3d/swapchain.c
> vkd3d: Fix top-most handling when restoring from fullscreen

- tests/d3d12.c
> tests: Add a test for MinLODClamp

- libs/vkd3d/command.c
- libs/vkd3d/meta.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
Leaving it as draft since there are some dubious validation warnings which don't make much sense.
> Handle separate DS layouts in ClearDSView and CopyTexture

- CHANGELOG.md
> meta: Update CHANGELOG for 2.4.

- meson.build
> meta: Update version to 2.4.

- libs/vkd3d/command.c
- tests/d3d12_raytracing.c
Attempts to make the RT test modular enough that it's possible to cover a larger API surface without me going insane.
> RT test refactor

- tests/d3d12_sm_advanced.c
> tests: Check for Native16Bit support before testing dot2add.

- include/private/vkd3d_common.h
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/vulkan_procs.h
> vkd3d: Fix MSVC build.

- libs/vkd3d/command.c
- tests/d3d12_copy.c
- tests/d3d12_test_utils.h
- tests/d3d12_tests.h
> Add test and fixes for footprint -> depth-stencil copy.

- libs/vkd3d/cache.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> vkd3d: Workaround huge memory overhead for individual VkPipelineCaches.

- libs/vkd3d/utils.c
> vkd3d: Add 12_2 to list of valid feature levels.

- libs/vkd3d/vkd3d_private.h
Somehow the rebase got really screwed up :\
> vkd3d: Fix compile error introduced by bad rebase.

- libs/vkd3d-shader/spirv.c
Width + offset must not overflow in SPIR-V. SM 5+ is well-defined here.
It's enough to just clamp the width against 32 - offset in all cases.
Fixes #829.
> vkd3d-shader: Avoid undefined result for Ibfe/Ubfe/Bfi.

- libs/vkd3d/command.c
This function fails if the counter overflows.
CP77 hits this case a lot and we should just warn the specific failure
instead of a random error.
> vkd3d: Don't spam error if ReleaseSemaphore fails.

- CHANGELOG.md
> meta: Update CHANGELOG for 2.5.

- tests/d3d12_shaders.c
> tests: Only test FP64 if device supports it.

- libs/vkd3d/resource.c
> vkd3d: Handle 64KB_UNDEFINED_SWIZZLE.

- include/vkd3d_d3d12.idl
- libs/vkd3d/bundle.c
- libs/vkd3d/command.c
- libs/vkd3d/command_list_profiled.h
- libs/vkd3d/debug_ring.c
- libs/vkd3d/device.c
- libs/vkd3d/device_profiled.h
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
Lots of boilerplate here since D3D12_RESOURCE_DESC1 was introduced for sampler feedback.
> Bump interfaces to ID3D12Device9 and ID3D12GraphicsCommandList6

- libs/vkd3d/device.c
This is now allowed according to
https://microsoft.github.io/DirectX-Specs/d3d/RelaxedCasting.html
> vkd3d: Allow B8G8R8A8 UAVs.

- tests/d3d12_descriptors.c
- tests/d3d12_test_utils.h
- tests/d3d12_tests.h
> tests: Add detailed meta-test for CastFullyTypedFormat.

- libs/vkd3d/device.c
The creation with those extensions fails in a few cases:
* older 32 bit drivers
* missing or inaccessible /dev/nvidia-uvm
I believe that DXVK has a workaround for the first problem.
There's also a mysterious crash that some Debian users experience with 64bit titles and a correct /dev/nvidia-uvm, see https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-982356716 and preceding comments. I believe we've checked everything else that could possibly cause the issue and the build with the NVX extensions disabled worked for the user. The bad  performance observed by @fezie was due to force enabled trace logging in the build.
> vkd3d: Retry to create Vk device without NVX extensions.

- libs/vkd3d/resource.c
For 64-bit image atomics, we should at the very least add 64-bit format
to compatibility list to avoid potential problems.
> vkd3d: Add R64_UINT to format compatibility list when needed.

- tests/d3d12_descriptors.c
> tests: Add additional test cases to minLOD test.

- libs/vkd3d/resource.c
This is something we discussed a while ago.
> vkd3d: Only use VK_IMAGE_CREATE_EXTENDED_USAGE_BIT if necessary.

- libs/vkd3d/command.c
- tests/d3d12_resource.c
- tests/d3d12_tests.h
Apparently aliasing barriers don't do what you'd expect ...
Continues PR #946 and supersedes it.
> Improve handling of aliasing barriers

- tests/d3d12_descriptors.c
- tests/d3d12_sm_advanced.c
> tests: Remove RADV bugs which have been fixed.

- libs/vkd3d/vulkan_procs.h
We need MSVC CI at some point to avoid trivial build derps like these :\
> vkd3d: MSVC build fix.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Also fix a long standing derp bug in CopyTiles.
> Bump suballocator limit to 2 MiB.

- libs/vkd3d/swapchain.c
Just like handling min/maxImageExtent of 0, we can just fall back to
user buffers.
Elden Ring hits this case on application teardown.
> swapchain: More gracefully handle SURFACE_LOST.

- libs/vkd3d/device.c
> vkd3d: Recycle command pools in Elden Ring.

- include/vkd3d_d3d12.idl
> cache: Fix sign mismatch warning.

- CHANGELOG.md
> meta: Add CHANGELOG for 2.6.

- meson.build
> meta: Update version to 2.6.

- include/private/vulkan_private_extensions.h
> khronos: Update Vulkan headers.

- README.md
> meta: Add KHR_dynamic_rendering to list of required features.

- libs/vkd3d/command.c
- tests/d3d12_depth_stencil.c
- tests/d3d12_tests.h
Add an extensive test to verify our implementation of DSV plane tracking. Fix some bugs with our barrier code in this area.
> Handle DSV plane decay correctly

- include/shader-debug/GNUmakefile
- include/shader-debug/debug_channel.h
- libs/vkd3d/command.c
- libs/vkd3d/debug_ring.c
- libs/vkd3d/vkd3d_private.h
Rewrites the debug ring to be useful in device lost scenarios.
Based on https://github.com/HansKristian-Work/vkd3d-proton/pull/993.
> Improve GPU hang debugging experience

- libs/vkd3d/command.c
- libs/vkd3d/state.c
Similar to the RTV thing. Hope I caught everything.
> Don't create pipeline variants for NULL DSV

- libs/vkd3d/command.c
- tests/d3d12_command.c
But preserve marker semantics if we can support them, and also add buffer write tracking that was previously missing.
Supersedes #983. @rlocatti-nv can you test if this has the desired effect in the games you mentioned?
> Optimize WriteBufferImmediate

- README.md
Update notes about drivers and breadcrumb/debug-ring changes.
> meta: Update README

- libs/vkd3d/device.c
Signed-off-by: Denis Barkar <dbarkar@nvidia.com>
> vkd3d: Force non-invariant position for Serious Sam 4.

- include/private/vkd3d_common.h
- include/private/vkd3d_file_utils.h
- include/private/vkd3d_profiling.h
- include/vkd3d_windows.h
- libs/vkd3d-common/file_utils.c
- libs/vkd3d-common/meson.build
- libs/vkd3d/cache.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Splits out the first 6 commits from https://github.com/HansKristian-Work/vkd3d-proton/pull/973 for easier review.
> Magic shader cache preparation

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
> ci: Workaround safe directory errors in vkd3d_build generation.

- libs/vkd3d-common/platform.c
> common: Fix missing include.

- libs/vkd3d/command.c
Some dynamic state is at risk of being spammed with same arguments many
times. For the dynamic state that is trivial to check, do so.
Ghostwire: Tokyo has been observed to spam the same OMSetStencilRef
value causing some context rolls, also RSSetShadingRate has been set
redundantly.
> vkd3d: Check for redundant dynamic state in some cases.

- include/private/vkd3d_memory.h
- tests/d3d12_command.c
- tests/d3d12_device.c
> Small ASan fixes

- libs/vkd3d/command.c
> vkd3d: Clear SUSPENDED flag properly.

- libs/vkd3d/command.c
- libs/vkd3d/shaders/cs_execute_indirect_patch.comp
- libs/vkd3d/shaders/cs_execute_indirect_patch_debug_ring.comp
- Use Index LUT feature.
- Try to reuse application indirect buffer when possible.
Builds on phase 5.
> Execute indirect - Phase 6 - Optimizations

- tests/d3d12_test_utils.c
- tests/d3d12_test_utils.h
> tests: Add headless D3D12 RenderDoc capture support.

- include/private/vkd3d_common.h
- include/private/vkd3d_profiling.h
- programs/vkd3d-profile.py
RDTSC and --delta support in parsing tool.
--delta is useful for copying the profile before and after a test region to extract iteration / tick counts over the region instead of since bootup of application.
> Profiling improvements

- libs/vkd3d/command.c
- tests/d3d12_command.c
Don't crash when errors occur. Avoids fallout in CI and avoids random crashes on NV when we forget to enable the config flag for testing.
> tests: Be more robust if DGC is not supported / partially supported

- libs/vkd3d/command.c
> Flush queued waiters before waiting for the sparse binding semaphore

- libs/vkd3d/command.c
Temporarily abandons the idea to fuse waiters with execution.
For whatever reason, this seemed to cause random flicker in Halo Infinite
with async compute on, and I have failed to figure out exactly why.
By playing around with how commands are fused, the results changed
dramatically, which means I doubt vkd3d-proton was actually at fault
here.
There is some questionable code around UpdateTileMappings in the game
where a COPY queue is used, and it does not seem to synchronize this with other
queues as far as I can tell. It is uncertain at this time if D3D12
requires a tile update to synchronize with *every* queue or just the
queue being submitted to. We assume the latter, as it's the only
behavior that makes sense.
It is possible that submitting waits as they are queued up
affects …
> vkd3d: Resolve fence waiters early.

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
> vkd3d: Small warning fixes.

- libs/vkd3d/device.c
Fixes Control in environment without shared fence support
> Fall back to regular fences when shared timeline semaphores aren't supported by the host.

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
Fixes safe directory stuff giving invalid version info.
> ci: Use arch-mingw-github-action v8

- libs/vkd3d/command.c
If DONT_CARE is used, driver (or renderdoc) is free to damage the
aspect. Use the dynamic rendering capability of binding the aspect as a NULL
aspect.
> vkd3d: Do not falsely discard DS aspects in fallback copies.

- libs/vkd3d/command.c
PIX Events Markers ( https://devblogs.microsoft.com/pix/winpixeventruntime/ ), which is the most used and the only recommended way to insert Perf Markers, see ( https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-beginevent )
PIXEventType enum values, masks, offsets, and encoding can be extracted from the source code in the original package
https://www.nuget.org/packages/WinPixEventRuntime
at \Include\WinPixEventRuntime\, mostly in PIXEventsCommon.h
> vkd3d: BLOB PIX markers decoding

- libs/vkd3d/renderdoc.c
> vkd3d: Fix build with renderdoc support enabled.

- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> VK_EXT_shader_module_identifier - Phase 2

- tests/d3d12_win32_exclusive.c
FileMapping import does not work atm since we cannot import anything that is backed by file descriptors. Verified that the normal test passes as-is in Wine.
> tests: Add TODO for file mapping heap import test.

- libs/vkd3d/memory.c
In some cases for some resources, implementations might not expose:
- DEVICE_LOCAL | HOST_VISIBLE
- CACHED
If we return from try_allocate without having actually tried to allocate the fallback logic makes wrong assumptions and might think that we have already exhausted all options available. If we never tried to allocate anything, do fallback logic inside the try function.
> Fix scenarios where resources don't support certain memory property flags at all

- libs/vkd3d-shader/spirv.c
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d-shader/vkd3d_shader_private.h
Should fix https://github.com/HansKristian-Work/vkd3d-proton/issues/1279 when done.
Undefined behavior, but games rely on this :(
> Implement robustness for indexable temps in DXBC.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/vkd3d_private.h
From the reead/write subresource branch.
> Memory clear queue refactor

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Fixes #1281
It's good enough to make Gears 5 launch but mostly untested beyond that.
Mostly a port from the same DXVK code.
> vkd3d: Implement SetEventOnCompletion for shared fences

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/swapchain_new.c
> Some `printf` format fixes

- libs/vkd3d/device.c
- libs/vkd3d/resource.c
Prepares for descriptor buffers. Found some bugs along the way that's good to get out of the way before the grand rebase.
> Misc descriptor fixes

- libs/vkd3d/swapchain_new.c
Fix issues with GPU starvation on Deck.
This wait on blit fence is after all unnecessary and was a somewhat questionable addition to begin with.
It was added before I reintroduced the wait on vkAcquireNextImageKHR completing on non-present-wait path.
> vkd3d: Do not block on blit fence completing.

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
https://github.com/HansKristian-Work/vkd3d-proton/pull/1297 is a full chunky 15 patches. To make review process a little smoother, here's the first 6 patches that should be fairly straight forward.
> VK_EXT_descriptor_buffer - Phase 2

- libs/vkd3d/swapchain_new.c
Fix https://github.com/HansKristian-Work/vkd3d-proton/issues/1318.
Some behavior thought to be arbitrary in the legacy swapchain was actually kinda important after all ... oh well.
> Misc new swapchain fixes

- libs/vkd3d/command.c
Observed in Witcher 3.
Signed-off-by: Robin Kertels <robin.kertels@gmail.com>
Co-authored-by: Hans-Kristian Arntzen <post@arntzen-software.no>
Supersedes https://github.com/HansKristian-Work/vkd3d-proton/pull/1345
> vkd3d: Make sure texture copies don't exceed the mip extent.

- libs/vkd3d/device.c
This reverts commit ac7e7de701ad336887c1cb38f8adc4e588005962.
Works on latest stable and latest Vulkan betas, little reason to keep this workaround around.
> Revert "vkd3d: Disable KHR_present_wait on NV 525.x drivers."

- libs/vkd3d/command.c
> vkd3d: End transfer batch before AS build and RT.

- libs/vkd3d/resource.c
- tests/d3d12.c
- tests/d3d12_vrs.c
> Workaround broken VRS in Dead Space remaster

- libs/vkd3d/vkd3d_private.h
Fairly trivial but this was confusing me while looking at things.
> vkd3d: Remove unused viewport_count field.

- include/private/hashmap.h
- libs/vkd3d-shader/vkd3d_shader_main.c
- libs/vkd3d/cache.c
- libs/vkd3d/command.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Reportedly helps Elden Ring on some GPUs.
Next thing to look into would be to get rid of unnecessary compute invocations where possible, but it's probably useful to land this first.
> Batch query resolves and WBI

- libs/vkd3d/command.c
- libs/vkd3d/meta.c
- libs/vkd3d/resource.c
- libs/vkd3d/shaders/cs_resolve_binary_queries.comp
- libs/vkd3d/shaders/cs_resolve_query.comp
- libs/vkd3d/vkd3d_private.h
And some additional minor cleanups. Builds upon #1411.
> Use BDA for query resolves

- include/vkd3d_d3d12.idl
- libs/vkd3d/bundle.c
- libs/vkd3d/command.c
- libs/vkd3d/command_list_profiled.h
- libs/vkd3d/device.c
- libs/vkd3d/device_profiled.h
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
I based this on https://github.com/sherief/vkd3d-proton/commit/9185edb42a3219113e86e3a48f84ce271ac65b17.
> vkd3d: Implement ID3D12GraphicsCommandList9 and ID3D12Device10.

- libs/vkd3d/command.c
Derp regression from the 3D UAV slice implementation.
> vkd3d: Fix broken layer_count computation in 3D uav copy.

- include/private/vkd3d_threads.h
Works around Like a Dragon: Ishin! which unloads d3d12.dll before device references have been freed. This leads to a segfault inside the internal worker threads.
Fix #1436.
> vkd3d: Hold references to d3d12.dll / dxgi.dll in threads.

- libs/vkd3d/command_list_profiled.h
- libs/vkd3d/device_profiled.h
- libs/vkd3d/swapchain.c
Fallout from interface bump since we don't test all build combinations in CI.
> vkd3d: Fix profile enabled build.

- libs/vkd3d/device.c
> vkd3d: Use correct name for the RE4 demo.

- libs/vkd3d/device.c
- libs/vkd3d/state.c
Mostly small stuff. The calloc seemed a bit scary and found some corruption when running test suite with multiple back to back device creations.
> Misc validation fixes

- libs/vkd3d/device.c
Also remove some stray whitespace.
> vkd3d: Add missing printf arguments.

- libs/vkd3d/device.c
> vkd3d: Add PSO cache fix to Uncharted: Legacy of Thieves Collection

- libs/vkd3d/state.c
Fixes listening mode in The Last of Us - Part 1.
Fixes #1498.
> vkd3d: Fix A8 color write masks and blending.

- include/private/vkd3d_threads.h
The portable way is to use SEH magic exceptions, but SetThreadDescription works on Wine fortunately.
MinGW does not support this in headers yet apparently (Win10+ API), so we dynamically load it.
> vkd3d: Implement vkd3d_set_thread_name on Windows.

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
> Shader workaround for The Last of Us

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
> Add wave size heuristics from dxil-spirv

- tests/d3d12_sm_advanced.c
> dxil-spirv: Update submodule.

- .github/ISSUE_TEMPLATE/bug_report.md
Clarification of the log file procedure. Ported from dxvk.
> meta: Clarify issue template log file procedure

- libs/vkd3d/resource.c
Just spotted a little oversight. I didn't test it, except that it builds.
> vkd3d: Protect access to the view map with the spinlock.

- libs/vkd3d/command.c
Allegedly fixes a deadlock in Ashes of the Singularity.
> vkd3d: Resolve shared semaphore waits on the CPU.

- libs/vkd3d/device.c
UE5 is broken and assumes that if mesh shaders are supported, barycentrics are supported. It does not check for this, so PSOs will start failing.
Work around this by disabling mesh shader support unless barycentrics are also supported. RADV supports barycentrics now, so this is only a real problem on older Mesa stable.
> vkd3d: Apply UE5 workaround for mesh / bary support.

- libs/vkd3d/command.c
More general, and fixes potential bugs where VS and MS pipelines share root signature, we need to change the VkPipelineLayout here due to different push stages.
> vkd3d: Invalidate root parameters when changing pipeline type.

- include/shader-debug/GNUmakefile
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/cache.c
Fixes some horrible, horrible, horrible, horrible bugs in UE5 ... ;_;
> Include MS/AS stages in PSO hash

- libs/vkd3d-shader/spirv.c
Xenia emits questionable DXBC code that is dead and does not exist at the appropriate scopes. Continue -> Break inside a switch for example ...
Fix #1657.
> vkd3d-shader: Mask DXBC code that is statically unreachable.

- libs/vkd3d/command.c
For meta shaders, they may push constants, clobbering the sibling domain, and we have to perform the same consideration as SetPipelineState, where a domain change may require push constants to be re-emitted.
To ensure this is not missed in the future, adds a new argument to invalidate_root_parameters.
> vkd3d: Invalidate push constants in sibling binding domain.

- libs/vkd3d/command.c
Helpful when debugging driver perf.
> vkd3d: Report more marker regions for profiling tools

- libs/vkd3d/command.c
This primarily focuses on global / buffer barriers.
Mainly, we're concerned with translating stages and access masks here.
> Implement Enhanced Barriers - Phase 2

- libs/vkd3d/command.c
Adds various utility functions for TEXTURE_BARRIER instead of subresources.
> Enhanced barriers - Phase 3

- libs/vkd3d/command.c
- libs/vkd3d/device.c
Implements image barriers and exposes the feature.
> Enhanced Barrier - Phase 4/4

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
Supersedes https://github.com/HansKristian-Work/vkd3d-proton/pull/1710.
> Workaround GPU hangs in RE4 DLC on RADV

- docs/sampler_feedback.md
- include/vkd3d_win32.h
- libs/vkd3d/meta.c
- libs/vkd3d/vkd3d_private.h
- meson.build
Mostly focuses on refactors to prepare for tests to land and bumps dxil-spirv submodule.
Also adds a detailed doc about the implementation in a pseudo-blog format outlining all the pain and suffering I encountered.
> Sampler feedback implementation - Phase 1

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/device_profiled.h
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
Implement some of the more trivial things:
- UAV Clear
- CopyResource
- Descriptor creation
- Adjust image create info
> Sampler feedback implementation - Phase 7

- libs/vkd3d/command.c
- libs/vkd3d/device.c
- tests/d3d12_sampler_feedback.c
We ultimate now. Complicated part here is the RESOLVE implementation which is mildly cursed as expected.
> Sampler feedback implementation - Phase 9/9

- .gitmodules
- build-win32.txt
- build-win64.txt
- meson.build
Fixes some deprecation warnings.
> Meson fixes

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Workaround game bugs in Windjammer 2 where game is releasing command allocator while there are pending submissions in flight.
This is obviously broken, but workaround it by repurposing the pending submission counter into private refcounts instead.
> vkd3d: Add internal refcounts to command allocator.

- include/vkd3d_shader.h
- libs/vkd3d-shader/dxil.c
- libs/vkd3d/device.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
Work around GPU hang on CP77 RT on RADV.
> Descriptor heap robustness

- libs/d3d12core/main.c
Like the original PR (#1823), this should fix situations where multiple Vulkan adapters get assigned the same LUID, but with comparing device names this should also be robust against DXVK-side vendor ID overrides, which are still sometimes needed.
This is a situation that generally *shouldn't* happen and is probably some sort of winex11 issue in combination with systems that have multiple GPUs that can all output to the same display in one way or another.
Pinging @Etaash-mathamsetty , @TechnoPorg
Supersedes #1823.
Fixes #1809.
> d3d12: Be more robust with LUID-based adapter selection.

- COPYING
Someone also forgot to update it for 2023 so I guess I have to update the date myself then 🐸.
> meta: Update COPYING year.

- libs/vkd3d/device.c
> vkd3d: Query for SPARSE_RESIDENCY as well.

- libs/vkd3d/state.c
Provides more info when drivers refuse to compile something for whatever reason.
> vkd3d: Log pipeline state when pipeline creation fails.

- tests/d3d12_render_target.c
Fixes benign test failure on Nvidia.
> tests: Fix tolerance in render pass tests.

- include/meson.build
- include/vkd3d_command_queue_vkd3d_ext.idl
- include/vkd3d_device_vkd3d_ext.idl
- include/vkd3d_vk_includes.h
- libs/vkd3d/command.c
- libs/vkd3d/command_queue_vkd3d_ext.c
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/meson.build
- libs/vkd3d/swapchain.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
Supersedes https://github.com/HansKristian-Work/vkd3d-proton/pull/1739.
Already approved in that PR.
> Merge VK_NV_low_latency2 support

- libs/vkd3d/device.c
The bug has been fixed game-side. Yay!
> vkd3d: Remove Cyberpunk 2077 shader quirks

- CHANGELOG.md
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/vulkan_procs.h
- tests/d3d12_render_target.c
> Use dynamic rasterization samples for multisampled PSOs

- include/private/vkd3d_string.h
- libs/vkd3d/cache.c
> Improve shader cache path selection when using explicit VKD3D_SHADER_CACHE_PATH.

- libs/vkd3d/device.c
Fixes grass: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10976
> vkd3d: Add shader quirk for Grounded

- libs/d3d12core/main.c
Same idea as #1964, but for OpenXR this time.
> vkd3d: Enable required extensions for OpenXR

- .github/workflows/artifacts.yml
- .github/workflows/test-build-linux.yml
- .github/workflows/test-build-windows.yml
Silences the CI deprecation warnings
> ci: Update CI actions

- libs/vkd3d/swapchain.c
Fallout from #2014. Implementation matches that of DXVK.
The `SetTargetFrameRate` function is called with:
- A **positive** value if there's a DXVK app profile (or user config). Hopefully won't ever be relevant for us since this is only really used to work around broken games that don't understand the concept of high-refresh monitors and just break at >60 FPS.
- A **negative** value if the app is running in fullscreen mode (i.e. app calls `SetFullscreenState(TRUE)`) and presents with SyncInterval > 0. The target frame rate is equal to the refresh rate of the selected display mode, and the intention is to only engage the frame rate limiter if we can't do a mode switch and display at a higher rate. Again *mostly* relevant for older games, but also makes things like the "fullscreen" mode and …
> Implement frame rate limiter

- tests/d3d12_copy.c
- tests/d3d12_test_utils.h
- tests/d3d12_tests.h
Attempt copies with esoteric formats.
> tests: Add copy test for depth <-> color edge cases.

- libs/vkd3d/command.c
> Validate that resolve format is actually supported before we try creating views.

- libs/vkd3d/swapchain.c
There are various cases now observed in the wild where BufferCount = 2 was causing problems. The problem is obvious in games with reasonably high CPU and GPU subscription. Since present wait events come in at a different alignment than presentation, it can happen that the CPU is delayed just long enough for a GPU frame to end up being falsely dropped.
This is quite bad on Deck since GPU clocks will start dropping as a result and then CPU clocks drop, and we have a really bad time.
The risk here is that some games will get more latency, but we have to err on the side of caution here unfortunately. Ideally, the internal latency handle should be more adaptive in nature. It's currently unclear which system component should be responsible for implementing that however.
> vkd3d: Get rid of default BufferCount latency optimization in swapchain.

- libs/vkd3d/swapchain.c
It's dumb and breaks horribly in some games that use it for esoteric frame pacing reasons. We should use timer instead as a fallback in lieu of proper display timing support.
We'll get a similar effect using DXVK's SetTargetFrameRate. That is updated accordingly with present interval.
> vkd3d: Remove multi-blits for present interval.

- README.md
Closes #2062.
Text mostly copied from DXVK repo. Many thanks to the contributors from there.
> meta: Add frame rate limiter to README

- .github/workflows/test-build-linux.yml
- libs/vkd3d/device.c
- libs/vkd3d/device_vkd3d_ext.c
- libs/vkd3d/resource.c
- programs/vkd3d-rs-parse/main.c
- tests/d3d12_copy.c
- tests/d3d12_depth_stencil.c
- tests/d3d12_descriptors.c
- tests/d3d12_mesh_shader.c
- tests/d3d12_pso.c
- tests/d3d12_pso_blob.c
- tests/d3d12_render_target.c
- tests/d3d12_resource.c
- tests/d3d12_sampler_feedback.c
- tests/d3d12_shaders.c
- tests/d3d12_sm_advanced.c
- tests/d3d12_sparse.c
- tests/d3d12_vrs.c
~Draft for now because there are still some dragons hiding in the land of tests and programs. I'll try to get to them tomorrow.~
> Enable reporting of format warnings in CI builds and fix some of them

- libs/vkd3d/swapchain.c
Allows for a bit more leniency w.r.t. swap chain buffering and timing errors, but still triggers early if the delivered frame rate is significantly higher than expected (e.g. 144 vs 60 fps).
Fixes situations where we engage the limiter in Elden Ring despite the game bringing its own 60 FPS lock.
> vkd3d: Implement better heuristic to enable frame rate limiter.

- libs/vkd3d/device.c
> Expose programmable sample positions Tier 2 for Pioneers of Pagonia

- tests/d3d12_command.c
- tests/d3d12_mesh_shader.c
> Skip more DGC tests when not supported.

- libs/vkd3d/device.c
> vkd3d: Add UAV compression workaround for MHW Beta.

- tests/d3d12_shaders.c
Weird that it started failing now though ...
> tests: Workaround MSVC build failure.

- libs/vkd3d/command.c
- tests/d3d12_sparse.c
Scary bug, although by some miracle we haven't run into this in practice. Added a test to make sure we don't screw this up again, we implement the same behaviour as native AMD and NV.
> Fix stale pointers in sparse look-up table

- libs/vkd3d/resource.c
We cannot suballocate in any meaningful way, so just allocate more VA space in the mildly non-sensical cases like this.
> vkd3d: Ensure that sparse buffers don't end up in fallback VA mapper.

- libs/vkd3d/command.c
- libs/vkd3d/queue_timeline.c
- libs/vkd3d/vkd3d_private.h
As discussed on Discord, the first two commits with fixes.
> Rework semaphore waiting Pt. 1

- libs/vkd3d/resource.c
Builds on #2237. Seems like Stalker 2 is fine with us erroring out for descriptor heaps with >1M entries, so let's do that to avoid some invalid Vulkan.
The `E_INVALIDARG` return code matches current agility SDKs, whereas on older runtimes we'd get `E_OUTOFMEMORY` or `DXGI_ERROR_DEVICE_REMOVED`. The somewhat scary part here is that all real drivers support more than 1M, whereas we currently can't without breaking fossilize DBs.
> Validate descriptor counts

- include/private/vkd3d_platform.h
- libs/vkd3d-common/platform.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/vkd3d_private.h
> Workaround bugged zerovram code on AMDGPU

- libs/vkd3d/command.c
Avoids an apparent NV performance bug on CPU.
Fixes #2256.
> vkd3d: Skip redundant wait for fences in queue workers.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Required for https://github.com/HansKristian-Work/vkd3d-proton/pull/2280 since after approving I theorycrafted a potential image layout issue.
> Fixups for barrier batch / copy batch sizes.

- libs/vkd3d/command.c
- libs/vkd3d/vkd3d_private.h
Draft for now because it needs more testing.
> Batch barriers for texture copies from CopyTextureRegion

- libs/vkd3d/command.c
- libs/vkd3d/raytracing_pipeline.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
> Experimental workgraphs - Phase 3

- libs/vkd3d/device.c
Adds an opt-out of the generic UE5 workaround.
> vkd3d: Add feature filter for mesh without barycentrics.

- libs/vkd3d/command.c
Most (all?) drivers would conflate COMPUTE and RT, but we need to be correct obviously.
> vkd3d: Include RT stage in barrier shader stages.

- libs/vkd3d/device.c
Reported by users to help CPU perf a bit.
> vkd3d: Add no_upload_hvv for MHW.

- include/vkd3d_core_interface.idl
- libs/d3d12/main.c
- libs/d3d12core/main.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/state.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12.c
- tests/d3d12_clip_cull_distance.c
- tests/d3d12_command.c
- tests/d3d12_copy.c
- tests/d3d12_crosstest.h
- tests/d3d12_mesh_shader.c
- tests/d3d12_pso.c
- tests/d3d12_query.c
- tests/d3d12_render_target.c
- tests/d3d12_resource.c
- tests/d3d12_sm_advanced.c
- tests/d3d12_tessellation.c
- tests/d3d12_test_utils.c
Fixes #2377.
Fixes #2372. (by muting)
Fixes #2382
> Sketch out debug control interface.

- tests/d3d12_command.c
Missed it when the bug was fixed.
> tests: Remove another mute exception.

- libs/vkd3d-shader/dxil.c
Gets rid of code duplication for normal entry points and exports.
> vkd3d-shader: Hoist out the mess that is DXIL options.

- libs/d3d12core/main.c
Rockstar's launcher unloads d3d12.dll before initializing it a second time, but d3d12core remains loaded. That causes us to retain stale pointers to VUID strings and explanations, which in turn leads to a segfault when setting up VVL exceptions again.
The easy way out is to simply retain a local copy of the strings involved and also allow duplicates.
> vkd3d: Create local copy of muted VUID strings.

- libs/d3d12core/main.c
When capturing some games, we cannot use a global env-var, since there might be launchers that explode when trying to be captured in unrelated APIs. If we defer this env-var to when vkd3d-proton is loaded, we can work around certain annoying cases.
> vkd3d: Add method to set Linux env-var from vkd3d.

- libs/vkd3d/device.c
Matches Windows drivers on ancient hardware (Maxwell, Pascal).
Should hopefully fix #2447, at least I was able to reproduce the crash when exposing min precision but *not* native 16-bit support.
> vkd3d: Only expose min precision support if 16-bit ops are supported.

- libs/vkd3d/device.c
> vkd3d: Workaround missing color -> resource barrier in Satisfactory.

- libs/vkd3d/device.c
Optiscaler relies on this for dx11 interop, otherwise we'll fail resource desc validation.
Verified that this matches Windows behaviour; `ALLOW_SIMULTANEOUS_ACCESS` is still set for all non-DSV usages.
> vkd3d: Do not set SIMULTANEOUS_ACCESS for shared DSV.

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/device.c
- libs/vkd3d/memory.c
- libs/vkd3d/resource.c
- libs/vkd3d/vkd3d_private.h
- tests/d3d12_raytracing.c
- tests/d3d12_tests.h
Should resolve GPU hang in SottR.
> Implement NULL RTAS heap descriptors correctly.

- libs/vkd3d/command.c
The predication fixup shader was being predicated away, which made it so that the new indirect count was uninitialized in memory. Yay ... The test was flaky because the expected result was that memory was 0, which it would be in almost all situations.
Fixes a 1.5 year old flake in test suite.
> vkd3d: Fix random flake in indirect_state_predication test.

- libs/vkd3d/device.c
See https://github.com/HansKristian-Work/vkd3d-proton/issues/1502
Config comment was taken from https://github.com/HansKristian-Work/vkd3d-proton/issues/1502#issuecomment-1532772932
> vkd3d: Disable color compression for Rise of the Tomb Raider

- .github/workflows/test-build-linux.yml
> ci: Install 32-bit libs for x86 builds.

- libs/vkd3d/acceleration_structure.c
- libs/vkd3d/command.c
> tests: Fix segfaults introduced in OMM merge.

- meson.build
> meson: Emit a fallback vcs so it's possible to build tarball.

- include/vkd3d_shader.h
- libs/vkd3d/command.c
- libs/vkd3d/device.c
- libs/vkd3d/meson.build
- libs/vkd3d/meta.c
- libs/vkd3d/vkd3d_private.h
- libs/vkd3d/workgraphs.c
This is basically a "draw-the-rest-of-the-owl" PR.
I'm not sure how to introduce the implementation in piecemeal form since it's all so interconnected. A 3 ksloc new file isn't exactly reviewable. If you have any ideas how you'd like to split up the implementation to make the review less hopeless, I can give it shot.
> Experimental workgraphs - Phase 6/6

- include/meson.build
- meson.build
(it's not super pretty but seems to work)
> Make sure idl generated headers get installed

- tests/d3d12_raytracing.c
Not sure why this passed before. Blind luck?
> tests: Use proper quad layout for RT.

- libs/vkd3d/command.c
> vkd3d: Fix theoretical sync bug with discard barrier.
